### ISSUE TITLE
Fringe page- invite submissions

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/Mozfest2016_production#10]
Invite partners, friends and other festivals taking place at the same time to submit their fringe events
https://mozillafestival.org/fringe

- [ ]  Sessions@
- [ ] Partners
- [ ] Sister festivals

**Comment by edrushka** [comment]
Have we reached out to these groups? Shall I close this?

**Comment by Saallen** [comment]
Yes- I will
