### ISSUE TITLE
Design table wrapper/cloth 

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Mozfest2016_production#101]
#### Info:

Last year we used Webmaker ones which we should not be using anymore. We should update to MozFest branded or just a solid color. It would go around the registration table and the info booths.

@marcwalsh This is a new asset, would you be able to find a supplier?

**Comment by marcwalsh-zz** [comment]
@kristinashu - It would be easier and cheaper to use solid colors that are in keeping with the style guide. 

Printed versions could be something like [this...](https://www.pixartprinting.co.uk/printing-flags-textiles/flags/) - I'd say either the 95GSM or the 115GSM so it's light enough to drape? - I'll need to double check this though.

**Comment by kristinashu** [comment]
Solid works for me, thanks!

**Comment by kristinashu** [comment]
First choice for table cloth color is purple but if they don't have something similar then blue would work as well.
<img width="276" alt="screen shot 2016-09-15 at 3 24 17 pm" src="https://cloud.githubusercontent.com/assets/1068783/18569611/83be35ae-7b58-11e6-8b5e-9cf59b8d308a.png">

@marcwalsh how should we work flow this? Should I remove the design label and assign to you to purchase?
