### ISSUE TITLE
Design Wayfinding: Space banners - Deadline Oct 11

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Mozfest2016_production#102]
#### Info:

Based on icons design in https://github.com/MozillaFoundation/Mozfest2016_production/issues/88 and epic ticket - Design Wayfinding #131 

We need flags to hang in each of the spaces:
- Digital Arts and Culture
- Journalism
- Open Science
- Open Badges
- Fuel The Movement
- Localisation
- Youth Zone
- Demystify the Web
- Dilemmas in Connected Spaces
- MozEx

These hang off rails and can be seen from main congregating areas on Foyer and Speaker floor. People also run around with these at the start of the festival. They're printed on lightweight, nylon fabric. 3 grommets attached to the top of each banner for hanging. 

Last year, we had the intention of cutting them at an angle but this didn't happen.
#### Specs from last year:

<img width="1058" alt="dbae86c6-78af-11e5-9ec7-3f002620dcea" src="https://cloud.githubusercontent.com/assets/1068783/17940283/3c4f630e-69e3-11e6-903f-92503fe0e4d2.png">
<img width="885" alt="7122b19c-7b3e-11e5-9805-394de4ab5f40" src="https://cloud.githubusercontent.com/assets/1068783/17940282/3c4d90c4-69e3-11e6-8932-0aac405ad515.png">
#### Last year's:
- Working files in Drive https://drive.google.com/open?id=0B2qu3ExKWIlvcTluMHIweHRnT0k
- GitHub ticket https://github.com/mozilla/mozillafestival.org/issues/267

<img width="331" alt="screen shot 2016-08-23 at 1 45 46 pm" src="https://cloud.githubusercontent.com/assets/1068783/17909195/3fdf9ff8-6938-11e6-97b5-328d8358e59c.png">

<img width="1073" alt="screen shot 2016-08-23 at 1 46 08 pm" src="https://cloud.githubusercontent.com/assets/1068783/17909211/4bbf4e5e-6938-11e6-8399-7dda2280ff50.png">

<img width="529" alt="screen shot 2016-08-23 at 12 58 19 pm" src="https://cloud.githubusercontent.com/assets/1068783/17908873/01a79f52-6937-11e6-82ca-f476ba5ba9a8.png">

**Comment by marcwalsh-zz** [comment]
I would stick with the same printers again for this. 

It's Pixart and the info is available [here](https://www.pixartprinting.co.uk/printing-flags-textiles/flags/) in terms of specs

**Comment by kristinashu** [comment]
Thanks @marcwalsh, I've added a little more info above. Do you know the deadline for this?

**Comment by sabrinang** [comment]
@ed-yau You can focus on iterating on banners with one space's name and icon first. For example start with:

Localisation
Icon (outlined): https://drive.google.com/file/d/0B4Q8pzCpDS_eWXZQV3NNaGVWVzA/view
Icon (paths if you need to adjust widths to work with type when scaled): https://drive.google.com/file/d/0B4Q8pzCpDS_eY0tBcVlveW9hVG8/view

Localisation has a shorter title and narrower icon than most. It is also worth noting to test the design with longest space name which is “Dilemmas in Connected Spaces” (we are removing the “A Tale of Two Cities:” part) and testing the icon that has full width and height which would be: 

Science
Icon (outlined): https://drive.google.com/file/d/0B4Q8pzCpDS_eaEd0cGM0TV95Q0U/view
Icon (paths): https://drive.google.com/file/d/0B4Q8pzCpDS_eQWozTDNIUzdwcDg/view

**Comment by sabrinang** [comment]
@ed-yau
Did you try to use the display font on the banners? This may help make them appear larger and more united with the other two. I noticed this when I was taking a screenshot of my progress of the space icons that you we're using fira for the titles and display type appeared on the other two:
<img width="1315" alt="screen shot 2016-09-26 at 5 22 29 pm" src="https://cloud.githubusercontent.com/assets/2492510/18856467/ab828526-840f-11e6-9a64-8ede18af296e.png">

**Comment by ed-yau** [comment]
@sabrinang The icons for the rest of spaces look great! I'll swap the type with the display font to see how the text fitting changes. I agree i think using this will definitely allow larger type for the banners! Thanks

**Comment by kristinashu** [comment]
Sabrina's lovely icons are all done! @ed-yau you can download them here: https://drive.google.com/drive/u/1/folders/0B2irLVDJivhLaEZ2RTk1Q0JWZE0

**Comment by ed-yau** [comment]
Previous
![banners old](https://cloud.githubusercontent.com/assets/21972436/18915049/86d69b3a-8587-11e6-92f2-5a5d60467477.jpg)
New 
![banner look](https://cloud.githubusercontent.com/assets/21972436/18914870/c01a127e-8586-11e6-98a7-d65df9ad7bc9.jpg)

Hi all, @sabrinang @kristinashu @xmatthewx  I've just put together how the large space banners could work with the display typeface. The type can be made bigger with this. Let me know your thoughts to finalise a design on these.

**Comment by xmatthewx** [comment]
Thanks @ed-yau. Looking good. One thing that jumps out – this font has really wide word spacing. Can we do some optical kerning on these? Digital Arts is almost okay, but I'm worried the word "in" will jump off that connected spaces sign!

@edrushka – how would the team feel about shortening their name to just "Connected Spaces" for this sign? For bigger type and fewer lines of text. We can keep "dilemmas" in other printed material. 

@sabrinang I really like the new digital arts and connected space icons. Nice work on all of these.

**Comment by edrushka** [comment]
I hear you on the challenge of fitting all those words on the banner, but I think 'dilemmas' is a foundational element in the space concept . If we must shorten, I defer to @thornet for what words to include on on the banner. 

Is it possible to keep as-is?

**Comment by thornet** [comment]
Thanks @xmatthewx and @edrushka. The dilemmas word is definitely key. Possible alternatives if it must be shortened: Connected Dilemmas.

**Comment by xmatthewx** [comment]
Thanks @thornet. 

@ed-yau – Let's stick with the full name to avoid confusion.

**Comment by ed-yau** [comment]
@xmatthewx Thanks, optical kerning is already been put on the banners above and also -100 on the tracking to make the words tighter. (The display font naturally has quite wide spacing, but I will adjust the kerning so the letters sit closer!)

**Comment by kristinashu** [comment]
@ed-yau can you please add colour in? I think the type might look different once it's a softer contrast. 

Also, will you be able to have all the banners (10 spaces, floor numbers, 'one web') done for Monday?

**Comment by xmatthewx** [comment]
Do we have a count of total banners? Is this what we're thinking?

| Count | Type | Qty | Location | Total |
| --- | --- | --- | --- | --- |
| 10 | Space banner | x2 | Railing AND inside space | 20 |
| 8 | Floors 2-9 | x1 | Railing OR inside space | 8 |
| 1 | One Web | x10 | Railing OR inside space | 10 |
- It'd be nice to have an extra One Web for Walker space or behind registration table.
- Space banners x2 could be hung on railing and just inside the space for people who get off elevators.

**Comment by kristinashu** [comment]
@xmatthewx what do you mean by "inside space"? I was under the impression the banners would only be over the railings (like last year). 
- Floor 1 did not have a session last years so I am assuming it won't this year.
- Floor 0 does not need a banner.
- Walker space does not need a banner. Walker space will not have sessions (only speaker series).

The important thing right now is to have the print ready files. We can easily adjust numbers later on.

**Comment by xmatthewx** [comment]
Hey @ed-yau – don't worry about my questions about placement and quantity. You can just focus on file prep. 

@kristinashu – should we start a separate thread for banner production quantities? I'm going to edit my comment above to simplify based on your comment.

**Comment by ed-yau** [comment]
@xmatthewx I'm in the process of marking the floorplan spaces with where things can potentially go. I'll give you this plan mark up when its done to compare with your quantity suggestions and options if it helps?

@kristinashu Final design with colour print files for these banners will be ready for Monday to review!

**Comment by sabrinang** [comment]
During our demos today, I noticed that the pixel sort pattern isn't on the angle of the grid in the style guide. @ed-yau Can you adjust these on the one web banner?
<img width="809" alt="screen shot 2016-09-30 at 10 21 20 am" src="https://cloud.githubusercontent.com/assets/2492510/19000497/c2e6d0f6-86f7-11e6-815a-f8585dc772e2.png">

**Comment by kristinashu** [comment]
Ed has shared the updated banners https://redpen.io/p/yfad874f695291a82c

@xmatthewx @sabrinang @edrushka can you approve the design and then @ed-yau can give us the print ready files? 

I've opened a separate ticket for quantities and pricing https://github.com/MozillaFoundation/Mozfest2016_production/issues/178.

![red-pen-4d269b9d-0c99-4f6f-d5c6-7abcb10b44f3](https://cloud.githubusercontent.com/assets/1068783/19161623/5b984428-8ba9-11e6-9236-27873655829c.jpg)
![red-pen-9d02f19a-ab49-457d-d9e0-a1edd53b0a77](https://cloud.githubusercontent.com/assets/1068783/19161619/5b97a90a-8ba9-11e6-91a8-3df0648edee1.jpg)
![red-pen-57f0400c-e948-40f2-f232-19428a534a9b](https://cloud.githubusercontent.com/assets/1068783/19161624/5b98bf0c-8ba9-11e6-93b2-a724059e654b.jpg)
![red-pen-3546abf5-2e50-4a0b-f316-b2487b5b0600](https://cloud.githubusercontent.com/assets/1068783/19161620/5b97b846-8ba9-11e6-966e-b5dac05b904f.jpg)
![red-pen-6328aff3-1f50-4106-d179-2c8dd41b3568](https://cloud.githubusercontent.com/assets/1068783/19161622/5b97fc34-8ba9-11e6-812e-a882c9be0826.jpg)
![red-pen-7910c944-1c3e-461e-cce4-efc924849fba](https://cloud.githubusercontent.com/assets/1068783/19161621/5b97d2f4-8ba9-11e6-9d40-bcf018984b21.jpg)
![red-pen-693780b3-e1e8-4c18-e435-3dabe33ecfd6](https://cloud.githubusercontent.com/assets/1068783/19161625/5baa2990-8ba9-11e6-8a34-ac5a095c685f.jpg)

**Comment by xmatthewx** [comment]
banners look super duper good to go

**Comment by kristinashu** [comment]
Excellent, design is done! @ed-yau could you please place the artwork in the templates mentioned in https://github.com/MozillaFoundation/Mozfest2016_production/issues/178? Note, we don't need every floor numbers.

**Comment by kristinashu** [comment]
Banners turned our great! Including floor numbers was a valuable addition. Sizes were good but they could have been even bigger! The banner material curled and was difficult to flatted out. We ended up printed an additional MozEx paper at Ravensbourne and it looks pretty much the same as the banner material banners so I think next year we could probably just use paper.

![artboard jpg](https://cloud.githubusercontent.com/assets/1068783/20195514/c6dac7de-a74b-11e6-829d-04974ce2ad5e.png)

Printed out smaller paper version for each Space.

<img width="469" alt="screen shot 2016-11-10 at 1 43 40 pm" src="https://cloud.githubusercontent.com/assets/1068783/20195522/cedca8e4-a74b-11e6-8c70-9a901d68fe19.png">
