### ISSUE TITLE
Design main + D&D stage - Deadline Oct 11

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Mozfest2016_production#103]
#### Info:

Last year's stage was a big success.

Background conversation in https://github.com/MozillaFoundation/Mozfest2016_production/issues/63 also closely linked to slide template https://github.com/MozillaFoundation/Mozfest2016_production/issues/87
#### Two stages (Main Stage - Level 4 and Dialogue and Debates Stage - Walker Space Level 0):
- They should look similar.
- Both 2016 stages will look like 2015's main stage (printed backdrop, two screens, one comfort monitor)
- Stages will NOT have: podium or projector

Notes about the D&D Stage:
- Talks will be streamed and recorded!
- This is the more important stage.
- Good opportunity to think about how branding shows up in video frames.
- Design should not be too busy (like with lots of stripes) because this will look crazy on film.
- Walker room will be artificially lit because there are no windows or natural light.
#### Dimensions:
- last year the backdrop was 4.87 x 3.35 m (need to confirm if we will use this size for both stages)
#### Last year's:
- Working files in Drive https://drive.google.com/open?id=0B2qu3ExKWIlvSlJYOU1uMlhCY0U
- GitHub https://github.com/mozilla/mozillafestival.org/issues/262

<img width="1075" alt="screen shot 2016-08-23 at 1 46 39 pm" src="https://cloud.githubusercontent.com/assets/1068783/17911805/8bc399fe-6944-11e6-9f92-0c3f8711445e.png">

**Comment by sabrinang** [comment]
design progress on redpen: https://redpen.io/p/fq57a6cbac24232872

**Comment by sabrinang** [comment]
@erikad Can we confirm the sizes for both backdrops are 4.87 x 3.35 m? (same as last year) 

Also, I'm going to check in about arabic "one web" with Khaled on the email thread

**Comment by sabrinang** [comment]
@marcwalsh Can you supply the dimensions for the main stage (floor 4) and for the debates and discussions stage (floor 0) when you have them confirmed?

**Comment by marcwalsh-zz** [comment]
100mm Bleed to each side of the image - High Res 100% (Actual Size) image size either PDF or EPS for each image.
Walker Space- Wall size 4800w by 2400h
Level 4- Wall size 4800w by 2400h

**Comment by marcwalsh-zz** [comment]
@sabrinang - See print specs above ^^ :)

**Comment by sabrinang** [comment]
@marcwalsh just to clarify that is 4800mm by 2400mm?

**Comment by marcwalsh-zz** [comment]
Yes that's correct! :)  @sabrinang

**Comment by sabrinang** [comment]
<img width="1126" alt="screen shot 2016-10-12 at 4 36 02 pm" src="https://cloud.githubusercontent.com/assets/2492510/19331526/08bef738-909a-11e6-9035-48f04b7353d0.png">
@kristinashu @xmatthewx design review of stage designs?

Files in gdrive https://drive.google.com/drive/u/1/folders/0B4Q8pzCpDS_eXzFtcll6bnduMUE or redpen: https://redpen.io/p/fq57a6cbac24232872

Both stages have the same layout bit with different background colour and textures. I have the files prepared for print but wanted design feedback before I pass them over for print.

**Comment by xmatthewx** [comment]
Looks good.
- Let's check with videographer as suggested on stand
- Should Moz logo be further to the left? Not critical, just curious.

Beyond that, I think these are good to go from where I sit. @kristinashu anything else?

**Comment by kristinashu** [comment]
Yes, maybe the MozFest logo should be left and maybe even up a little. 

@sabrinang did you should outline all the text?

**Comment by sabrinang** [comment]
Thanks for the feedback - I aligned the logo more left making that the  baseline of wordmark aligns with top of white circle and left margin is balanced with the top. I also outlined the the localized text in the latest files (100mm bleed with crop/trim marks) and exported in the For Print folder. 
![stage_preview](https://cloud.githubusercontent.com/assets/2492510/19406099/d5e5ed16-9234-11e6-9134-d7a453ec552d.png)

**Comment by sabrinang** [comment]
The director, Mike, replied that the stage won't have any issues being filmed. The files in the For Print folder are good to go then (.eps and .pdf included): https://drive.google.com/drive/u/1/folders/0B4Q8pzCpDS_eOEZHUURrSUVKWG8

**Comment by marcwalsh-zz** [comment]
Sent to printers!

**Comment by sabrinang** [comment]
## Post MozFest Documentation

The Main Stage on level 4 had lights along the bottom with a table set up to the right.
![mozfest-documentation-main-stage](https://cloud.githubusercontent.com/assets/2492510/20193638/c1343b38-a743-11e6-930c-0aaa8329690a.png)

 The Dialogue and Debates Stage in the Walker Space on level 0 had a lighter background treatment which contrasted the dark space and the yellow strip below peaked through under the stage lights.
![mozfest-documentation-dd-stage](https://cloud.githubusercontent.com/assets/2492510/20193644/c5aa5648-a743-11e6-8a15-13b5fb9e0283.png)
