### ISSUE TITLE
Add last year's map to Drive

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Mozfest2016_production#104]
I can't seem to find illustrator files for the maps. Can someone please add them to Drive since we'll be building off of it for this year?

https://drive.google.com/open?id=0B20-0lpP23c0WHBhR005XzBpOUU

cc @lovegushwa @marcwalsh @natalieworth @flukeout

**Comment by marcwalsh-zz** [comment]
@kristinashu This is last year's artwork which contains the maps in AI format...

[https://drive.google.com/open?id=0B2qu3ExKWIlvSldqLTdvRnFiaTQ](https://drive.google.com/open?id=0B2qu3ExKWIlvSldqLTdvRnFiaTQ)

Does that help? :)

**Comment by kristinashu** [comment]
Perfect, thanks!
