### ISSUE TITLE
Add label- MozFest contributor- 

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/Mozfest2016_production#106]
Please add label - MozFest contributor and remove stipend request label from 
the final 21 Mozfest participation travel stipends volunteers!!!
1.  Label to be added -  MozFest contributor
2. Remove Travel stipend request
3. Add comment- travel covered and facilitator will be attending as MozFest contributor

**Comment by marcwalsh-zz** [comment]
All updated! Closing... 💆🏻
