### ISSUE TITLE
Copy for D&D photo/video consent

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Mozfest2016_production#107]
Based on conversation in https://github.com/MozillaFoundation/Mozfest2016_production/issues/97

We have last year's general photo/video consent copy (below) but need another version for the D&D room. 
#### General Photo & Video Consent

If you do not wish to be photographed or videoed, please request a yellow lanyard from registration. These special lanyards signify that you do not wish to be captured by the onsite photography and video team. 
Mozfest’s official photographer and video team will stream all mainstage programming live on Air Mozilla.
For keynotes, we would advise anyone not wishing to appear on the livestream to watch from the 5th floor or higher. You can also view and listen to all keynotes from the first floor and foyer.
#### We will need a different sign for D&D since:
- the content is used by MoCo for commercial use. Our policy is re-use for non commercial purposes so in this room we need to highlight that
- It is audio recording
- Live content so those who wish not to be seen need to know where to seat away from cameras

Last year's design:
<img width="419" alt="screen shot 2016-08-24 at 10 50 35 am" src="https://cloud.githubusercontent.com/assets/1068783/17941840/dd740b94-69e9-11e6-80c7-ea9ff9822eac.png">

**Comment by edrushka** [comment]
cc @KevZawacki

**Comment by marcwalsh-zz** [comment]
Just on a similar note here @edrushka @Saallen - we will need release forms for speakers in the D&D talks. Is this something Mozilla has a generic template for?

**Comment by Saallen** [comment]
We do- @erika can you use or build upon the ones you use for the Dosed filming?

**Comment by edrushka** [comment]
In previous years, we haven't used a consent form with Dosed. Instead, we relied on the coloured lanyards, the the poster (above) at the registration area, and an [email we sent to all attendees](https://docs.google.com/document/d/1k1zIWDlkYFJvDohe9Hu9tTOtXURJzanN998RpiSxvxM/edit) outlining photo consent options. I feel a similar approach will work this year for attendees.

For D&D speakers, we probably want a release form that outlines how we intend to use their talks in  the future (e.g. create a video library on our site, promote on social etc.)

@KevZawacki can you find out what MoCo uses for their Speaker Series? I'm thinking particularly of the Kevin Kelley talk, which was streamed live, then later packaged in a video.

**Comment by KevZawacki** [comment]
@edrushka Sure -- emailing Diane Tate now.

**Comment by KevZawacki** [comment]
MoCo internal comms does not have any boilerplates we can swipe, unfortunately.

**Comment by KevZawacki** [comment]
Wait, [they do](https://drive.google.com/a/mozilla.com/file/d/0B-BKZVAww2KHS1lVdkFwZndtRUp3UFhBYnk3anZsZWpXNE1N/view?usp=sharing) (from View Source). 

Would we just swap in "MozFest" and then share with speakers alongside next week's email?

@edrushka @Saallen

**Comment by Saallen** [comment]
wow- intense
will we be adding a  CC license to our broadcast as if yes- then we need to mention this here too.
Otherwise it looks good

**Comment by KevZawacki** [comment]
Updated speaker release form [here](https://docs.google.com/document/d/1-oz4fcLZATF1DCndZzGga7WzPBtREs_aAUfcEcXMnuw/edit).

@Saallen @edrushka Does this look good? OK to send to our confirmed speakers along with today's email?

**Comment by edrushka** [comment]
Gah! So intense! Should we get ops or legal to weigh in on if we actually _need_ this? I don't know if it's legit to modify a legal doc for CC licensing.  I do realize it will take weeks if we involve legal. Is there any urgency to get these signed?

**Comment by Saallen** [comment]
This needs to go before legal and we should definitely have one.
I will open a bug for it now. I dont think it will take long as its already been used at a previous event

**Comment by Saallen** [comment]
Upon recommendation we should not have the CC license on this form- Legal updating this week for us. This form will be used for those interviewed onsite too for other videos

**Comment by KevZawacki** [comment]
Great! We can share this form with our speakers on Oct. 3, along with the [speaker playbook](https://docs.google.com/document/d/14VXDQcdKjOztX62HxYbnHXrPjwD-xR3ATY03KcsPVSo/edit).

**Comment by edrushka** [comment]
@Saallen or @marcwalsh did we hear back from legal on this?

**Comment by KevZawacki** [comment]
@edrushka We did -- form has been updated and shared with speakers.
