### ISSUE TITLE
Guide: Write introduction

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/Mozfest2016_production#108]
For 2016 Festival Guide. Write Introduction: What is MozFest?
Include:
- 7th year. Opportunity for network to convene. Largest event. Projects are born here etc. [not about Mozilla, about the network. Mozilla listens to the community here]
- What to expect over the weekend. (explain how the weekend upfolds)
- Diversity and Inclusion stats. (Instead of having a standalone statement, celebrate the diversity of the festival and its participants E.g. “There are 10+ sessions in languages other than English, Facilitators from 30+ countries, 5 youth-led sessions”)

Note to designers: copywriting team needs a wordcount for this section!

**Comment by xmatthewx** [comment]
Can you share last year's introduction? @edrushka

**Comment by edrushka** [comment]
@marcwalsh do you have the text from last year's book anywhere?

**Comment by marcwalsh-zz** [comment]
Sure thing!

See below...

> MozFest is where many of the web's best and most innovative ideas spring to life. It's where passionate thinkers and inventors come together to learn form one another and imagine how the Web can remain open and accessible to everyone. 
> 
> We invite you to make the most of this gathering of extraordinary technologists and creators by sharing your ideas, demos, hacks, bringing a pragmatic approach to solving real problems and forging new collaborations. Don't be shy - if you love the Web, your ideas are welcome!

**Comment by edrushka** [comment]
MozFest is the world's leading event by -- and for -- the open internet movement.

What is MozFest?

MozFest is a three-day extravaganza of interactive sessions, hands-on activities and engaging talks, and is one of Mozilla’s largest annual networking opportunities.

Now in it’s seventh year, MozFest has a rich history of driving innovation on the web. Planned activities and impromptu conversations foster connections between open source enthusiasts who work in the arts, sciences, journalism, education and engineering. 

MozFest is a diverse, highly interactive event with something for everyone. This year, there are nine thematic Spaces filled with participant-led sessions. These might be interactive labs where participants can learn something new or share their knowledge, small group breakout discussions where bright minds debate the most pressing issues facing the Internet today, or design sprints dedicated to hands-on making, hacking and producing a ‘thing’.

We’re proud to welcome 1800 passionate advocates of the open web from a wide range of backgrounds. This year, there are sessions in X languages, session hosts from X countries, and X sessions lead by youth.

This weekend, we invite you to join influential thinkers from around the world to build, debate, and explore the future of a healthy internet. 

Welcome to MozFest.

---

@Saallen @KevZawacki pls review this intro for the festival guide

**Comment by Saallen** [comment]
This looks great @edrushka - well defined and perfecto!
I do think if we mention the 9 spaces we should also mention MozEx as an experience- while it is not considered a space with sessions, talks it does play a large part in the program.
would it be ok to add this within the description too?

**Comment by KevZawacki** [comment]
@edrushka Hey, this is great! Nicely done :-)

One note: We should use lowercase "internet" throughout. (It's capitalized in the fifth paragraph.)

**Comment by edrushka** [comment]
MozFest is a diverse, highly interactive event with something for everyone. This year, there are nine thematic Spaces filled with participant-led sessions. These might be interactive labs where participants can learn something new or share their knowledge, small group breakout discussions where bright minds debate the most pressing issues facing the internet today, or design sprints dedicated to hands-on making, hacking and producing a ‘thing’. 

New for 2016 is MozEx: an art exhibition with a 21st-century twist. Curated by the digital learning teams at both the Tate and the V&A, this exhibit explores links between art, society, and the digital world.

---

How's this @Saallen

**Comment by Saallen** [comment]
Looks great to me, thanks for the edit!

**Comment by edrushka** [comment]
@carrie-Ann, here is the final copy for the introduction to the festival guide

---

MozFest is the world's leading event by -- and for -- the open internet movement.

What is MozFest?

MozFest is a three-day extravaganza of interactive sessions, hands-on activities and engaging talks, and is one of Mozilla’s largest annual networking opportunities.

Now in it’s seventh year, MozFest has a rich history of driving innovation on the web. Planned activities and impromptu conversations foster connections between open source enthusiasts who work in the arts, sciences, journalism, education and engineering.

MozFest is a diverse, highly interactive event with something for everyone. This year, there are nine thematic Spaces filled with participant-led sessions. These might be interactive labs where participants can learn something new or share their knowledge, small group breakout discussions where bright minds debate the most pressing issues facing the internet today, or design sprints dedicated to hands-on making, hacking and producing a ‘thing’.

New for 2016 is MozEx: an art exhibition with a 21st-century twist. Curated by the digital learning teams at both the Tate and the V&A, this exhibit explores links between art, society, and the digital world.

We’re proud to welcome 1800 passionate advocates of the open web from a wide range of backgrounds. This year, there are sessions in X languages, session hosts from X countries, and X sessions lead by youth.

This weekend, we invite you to join influential thinkers from around the world to build, debate, and explore the future of a healthy internet.

Welcome to MozFest.

**Comment by edrushka** [comment]
Closing. Pull text from final festival guide InDesign file. Content in this ticket has not been through final proof-reading.
