### ISSUE TITLE
Guide: Write Key Festival Timings

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/Mozfest2016_production#109]
For 2016 Festival Guide. Write Key Festival Timings
Include:
- Can be similar to how we the Weekend Outline section on the website: https://mozillafestival.org/expect
- pull from #70
- Avoid specific session blocks because they change

THIS PAGE CAN BE CUT IF NECESSARY

**Comment by edrushka** [comment]
Friday

```
18:00 Science Fair begins 
```

Saturday

```
9:00-9:30 main stage
10:00 -11:00 Session 1
11:15- 12:15 Session 2 and D&D 1
12:30 -13:30 Session 3
12:30- 14:00 Lunch
13:00 - 13:45 Sessions 4, D&D 2 and Lunch cont.
14:00-15:00 Sessions 5
15:15- 16:15 Sessions 6 
16:30- 17:30 Sessions 7
18:00 Evening activities begin
```

Sunday

```
10:00- 10:45 main stage
11:00 - 12:00 Sessions 8 and D&D 3
12:15 - 13:15 Sessions 9
12:30- 14:00 Lunch
13:00- 13:45 Sessions 10
14:00- 15:00 Sessions 11
15:15- 16:15 Sessions 12
16:30 - 17:30 Sessions 13
18:00 Demos
```

@KevZawacki can you confirm these are the most up-to-date timings for the D&Ds?

**Comment by KevZawacki** [comment]
@edrushka They're a bit off. D+Ds are currently:

Saturday, Oct. 29 // 11:15 a.m. - 12:15 p.m. (correct above)
Saturday, Oct. 29 // 3:15 p.m. - 4:15 p.m. (incorrect above)
Sunday, Oct. 30 // 2 p.m. - 3 p.m. (incorrect above)

We'll likely be adding a fourth this week; time tbd.

**Comment by edrushka** [comment]
@Carrie-ann this is ready for the guide. Final copy for the Key Festival Times section (although be aware we may add one final 'Dialogues and Debates' slot)

Friday

```
18:00 Science Fair begins 
```

Saturday

```
9:00-9:30 Welcome and keynote
10:00 -11:00 Session block 1
11:15- 12:15 Session block 2 and 'Dialogues and Debates' Speaker Series
12:30 -13:30 Session block 3
12:30- 14:00 Lunch
13:00 - 13:45 Session block 4 and Lunch cont.
14:00-15:00 Session block 5
15:15- 16:15 Session block 6 and 'Dialogues and Debates' Speaker Series
16:30- 17:30 Sessions block 7
18:00 Evening activities begin
```

Sunday

```
10:00- 10:45 Keynote 
11:00 - 12:00 Session block 8 
12:15 - 13:15 Session block 9
12:30- 14:00 Lunch
13:00- 13:45 Session block 10
14:00- 15:00 Session block 11 and 'Dialogues and Debates' Speaker Series
15:15- 16:15 Session block 12
16:30 - 17:30 Sessions block 13
18:00 Demo Party begins
```

**Comment by Carrie-ann** [comment]
@edrushka Great! Thanks for this.

**Comment by edrushka** [comment]
@Carrie-ann we decided to add a 4th Dialogue and Debate slot now rather than later 😉 I updated the comment above.

**Comment by edrushka** [comment]
Just for consistency across tickets, here are the timings with the additional 5th  D&D:

Saturday
    9:00-9:30 main stage
    10:00 -11:00 Session 1
    11:15- 12:15 Session 2 and D&D 1
    12:30 -13:30 Session 3
    12:00- 14:00 Lunch
    13:00 - 13:45 Sessions 4 and D&D 2
    14:00-15:00 Sessions 5
    15:15- 16:15 Sessions 6 and D&D 3
    16:30- 17:30 Sessions 7
    18:00 Evening activities begin

Sunday

```
09:30 - 10:45 MozFest Breakfast
11:00 - 12:00 Session 8
12:15 - 13:15 Session 9 and D&D 4
12:30 - 14:00 Lunch
13:00 - 13:45 Session 10
14:00 - 15:00 Session 11 and D&D 5
15:15 - 16:15 Session 12
16:30 - 17:30 Sessions 13
18:00 - Closing Demo Party
```

**Comment by KevZawacki** [comment]
@edrushka I have the final D+D scheduled for Session 12 on Sunday (15:15 - 16:15). Can you confirm if this is correct / typo above?

**Comment by edrushka** [comment]
Confirming that D&D 5 is at 14:00 - 15:00, as indicated above.

**Comment by edrushka** [comment]
Closing. Pull text from final festival guide InDesign file. Content in this ticket has not been through final proof-reading.
