### ISSUE TITLE
Guide: Write Mozilla’s 5 Key Issues 

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/Mozfest2016_production#110]
For 2016 Festival Guide. Write Mozilla’s 5 Key Issues 

Include:
- Brief introduction giving context: these are the biggest challenges to the open web. We need to work together to make these mainstream issues.
- Each issue, with description (from the handout in London or latest update).

Note: Bobby’s visual might work here. If not, we may need another visual because this is a lot of text.

**Comment by edrushka** [comment]
@samanthaburton This is for the physical booklet (the Festival Guide) that we give to all attendees at MozFest when they arrive and register. Full context [here](https://docs.google.com/document/d/1Cz3kZSrwmvnaO8GDlTl8VTcvPjZ4TmjfVvaul8rhOvQ/edit#). Do you have an updated version of the one-page handout you provided in London? We can also use that copy, if it's still up-to-date.

@secretrobotron will the visual you're working on with the contractors be appropriate here?

**Comment by samanthaburton** [comment]
The most up-to-date version is page 5 of the MoFo Strategic Plan - https://drive.google.com/file/d/0B87EwT3UvJkMU3RrUFFxc1VrYk0/view?usp=sharing

**Comment by edrushka** [comment]
**Mozilla’s Key Internet Issues: Shaping the Agenda**

To unlock the next wave of openness and opportunity on the Internet, we need the public to understand and be ready to address the biggest challenges and opportunities that face the internet today.

Mozilla, our community and our allies need to be clear, compelling voices for the open Internet. Our goal is to work together to make open internet issues mainstream issues, globally.

Mozilla has identified five issues that we believe must be tackled in the current era, to build the open internet we want:
**Online Privacy & Security**
Mozilla’s Goal: People understand and can meaningfully control how their data is collected and used online, and trust that it’s safe. In parallel, companies and governments work to protect our data and enhance our ownership over our digital identities.

**Open Innovation** 
Mozilla’s Goal: Open is the default: open source and open standards continue to be at the heart of the Internet, and influence organizations and industries products, policies and practices. As a result, entrepreneurs and everyday Internet users can create, innovate and compete online without asking permission.

**Decentralization** 
Mozilla’s Goal: The technologies and platforms people use every day are interoperable and based on open standards. People expect and demand systems that allow seamless flow and transfer of information and content.

**Web Literacy** 
Mozilla’s Goal: People have the skills to read, write and participate in the digital world. Together, these informed digital citizens move beyond just consuming content, to creating, shaping and defending the web.

**Digital Inclusion** 
Mozilla’s Goal: People everywhere can access and have the opportunity to participate in building the entire internet. Subsequently, everyone on the Internet has the opportunity to access and shape our digital world. The internet reflects the diversity of the people who use it.

---

@carrie-ann @kristinashu here is text for the 5 key issues. You can see how it was laid out on Page 5 of [this PDF](https://drive.google.com/file/d/0B87EwT3UvJkMU3RrUFFxc1VrYk0/view)

This is our official language, so I'm hesitant to shorten. What do you think about wordcount?

**Comment by edrushka** [comment]
Closing. Pull text from final festival guide InDesign file. Content in this ticket has not been through final proof-reading.
