### ISSUE TITLE
Guide: Dialogues and Debates Speakers Series 

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/Mozfest2016_production#111]
For 2016 Festival Guide. Write Dialogue and Debate Speakers Series 

Include: 
- Brief context about what we're trying to achieve with the Speakers Series
- Speakers photo and tweet length bio. Title/subject of talk.

Notes: 
- This can be a complementary piece to 5 key issues #110
- We’re aware that speaker lineup could change at last minute. Let’s design to link speakers with topics. If, close to the print deadline, we feel like a lot of speakers might pull out, we can discuss an insert instead.

**Comment by Carrie-ann** [comment]
@edrushka Just out of interest do you happen to know how many Dialogue and Debate Speakers there are going to be? I'm currently trying to work out how information could look in the festival Guide. 

Thanks !

**Comment by edrushka** [comment]
There are currently 9 confirmed speakers and a couple maybes. I don't think we'll exceed 12.

**Comment by edrushka** [comment]
@KevZawacki what date are we aiming to have the speakers list finalized and the photos and bios ready? Also, did you give a wordcount for the bios?

**Comment by KevZawacki** [comment]
I've asked for all headshots, bios, and talk titles by Friday, Sept. 23.
Bio wordcount is <200 words. We can trim further.

**Comment by edrushka** [comment]
Dialogues + Debates -- MozFest’s speaker series -- is where compelling voices touch on topics related to Privacy and Security, Digital Inclusion, Web Literacy, Open Innovation, and Decentralization. 

These 45-minute talks, followed by a moderated Q&A session, will take place in the Walker Space on the ground floor of Ravensbourne, surrounded by provocative interactive art that explores the speakers' themes.

---

@KevZawacki how's that for the intro? I'll add the speakers when the info is ready to be made public. Also, do you want to include when they'll be speaking? I'm inclined _not_ to include speaking times in the written guide, in case we need to change them after the print deadline.

@Carrie-ann I believe we're at 11 speakers now.

**Comment by KevZawacki** [comment]
@edrushka A few revisions below. (I'm not a fan of listing out the five issues -- I think we lose people. Thoughts?)

Also, agreed that we don't want to include times -- at least, not yet. Once speakers have had their playbook for a week or two, I think we can consider them final. 

---

Dialogues + Debates -- MozFest’s speaker series -- is where compelling voices touch on the biggest issues facing the internet (and society) today.

These 12-minute talks, followed by a moderated Q&A session, will take place in the Walker Space on the ground floor of Ravensbourne, surrounded by provocative interactive art that explores the speakers' themes.

**Comment by edrushka** [comment]
+1 to not listing issues - we are dedicating an entire section of the Festival Guide to them, so they'll be well covered. Thanks for your review!

@KevZawacki please let me know when I can make the speakers list public in this ticket.

**Comment by edrushka** [comment]
@Carrie-ann here is the final copy for the Dialogue and Debates Speaker Series intro

---

Dialogues + Debates -- MozFest’s speaker series -- is where compelling voices touch on the biggest issues facing the internet (and society) today.

These 12-minute talks, followed by a moderated Q&A session, will take place in the Walker Space on the ground floor of Ravensbourne, surrounded by provocative interactive art that explores the speakers' themes.

---

The individual speaker details are here: https://docs.google.com/document/d/1xHq6RnAolJNHhZzuf-UV98qNFexESoIufzJci9VvVmY/edit
A few of the talk titles still to be added.

**Comment by Carrie-ann** [comment]
@edrushka @kristinashu Would you please be able to provide me the headshot images separated from this document? I'm having issues taking the images out and it would be better for linking if I can have them as separate files. Thanks a lot!

**Comment by kristinashu** [comment]
@Carrie-ann bio images are [here](https://drive.google.com/drive/folders/0B-BKZVAww2KHRzlGOWNfc19rZGc?usp=sharing)

**Comment by edrushka** [comment]
Closing. All revisions being tracked in #172.
