### ISSUE TITLE
Guide: Write Spaces

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/Mozfest2016_production#112]
For 2016 Festival Guide. Write Spaces 

Include: 
- Brief overview of what a space is 
- Descriptions of individual spaces (tagline, not paragraph)

Note: Pull from https://mozillafestival.org/spaces-and-sessions.

**Comment by edrushka** [comment]
@Saallen will we be asking Wranglers to update their space descriptions or should I pull from what's currently on https://mozillafestival.org/spaces-and-sessions?

**Comment by Saallen** [comment]
@edrushka 
I think we should let them know we will be updating and give them a window to make small changes.
I would like to add this to the agenda for next weeks call

**Comment by edrushka** [comment]
Ok - although should we wait until curation actually finishes before we ask them to re-write?

**Comment by Saallen** [comment]
Yes, once we can afford it with the printing timeline-

Sarah Allen

Events Manager and Mozilla Festival Producer
Mozilla Foundation

Find out more about MozFest https://mozillafestival.org/ and follow the
conversation on twitter https://twitter.com/mozillafestival?lang=en-gb

**Comment by edrushka** [comment]
@Saallen the deadline has passed right? Did any spaces request changes to their space description?

**Comment by Saallen** [comment]
Science said they might need to but I have not heard from them. I will ping
Earliest but if nothing by today's call it's officially closed

**Comment by edrushka** [comment]
Looks like Science doesn't want a re-write. I will use copy from the website for this section.

**Comment by edrushka** [comment]
Spaces are physical and thematic learning hubs based around a broad topic, like science, art, or journalism. A Space is made up of sessions, which are interactive gatherings around a specific idea like _Quantum computing - The next step_, _Ro-Botticelli - Creating art with robots_, or _Graveyards & Treasure Troves - Hidden APIs of the Media_.

**Digital Arts and Culture**
In the 21st Century, the relationship between art and technology has grown deeper and more nuanced than ever before. We use technology to create art. We view and share art using new and impressive digital tools. And often, technology itself — from products to web pages — is art. In this space we unpack the relationship between art, technology, and the web.

**Journalism**
Journalism doesn't just tell the story of the Internet — it's part of it. Software like Django, D3, and Backbone has emerged from newsrooms to power some of the most innovative work on the open Web. And reporting entertains and challenges millions of readers online every day, giving them the information they need to engage with their communities. In this space we explore how journalism can change our lives, both in person and online.

**Open Science**
Science and the web both help us understand the world around us. We cover topics like open data and research, citizen science, and science communication — all the while learning news skills and tools. In this space we explore, remix, and hack at the intersection of science and the Internet, and learn how the web is transforming research and discovery.

**Open Badges**
Open Badges are transforming how we recognise and reward learning. These digital credentials showcase and communicate learners’ skills — from HTML to design — in a way that traditional CVs and transcripts cannot. In this space we showcase exciting badges projects, hack on and build badge infrastructure, and encourage new partners and networks adopt badges.

**Fuel The Movement**
Current copyright laws aren't equipped for the internet age. Right now, we have a unique opportunity in the European Union to update and reform copyright laws to enhance -- not hinder -- creativity and innovation. In this space we will help participants explore how these and other laws impact them -- and what YOU can do about it.

**Localisation**
The internet spans many cultures and languages and this space reflects the diversity of the web and the people who use it. We’ll explore how people participate in the digital world in a way that reflects their unique culture and identity. In this space, localisation experts and amateurs alike will share localisation tools, discuss their experiences on a multicultural Internet, and explore how we can create a Web that’s truly inclusive of all languages and societies.

**Youth Zone**
Too often, current-day education systems are prescriptive. Learning is based around certain objectives, like exams. And independent thinking isn’t encouraged. In this space we’re creating an environment where independent thinking isn’t just encouraged — it’s rewarded. Our space is a sandbox for kids, teens, and adults alike to tinker, hack, build, and play as a means of learning. 

**Demystify the Web**
Grab your ticket to our carnival of learning! All who enter will gain the most important skills of our age: the ability to read, write and participate in our digital world. This space invites teachers and learners of all ages to join our funhouse of Web literacy. Embrace the unknown! Experience the thrills! Imagine and share the full potential of the Web with everyone!

**Dilemmas in Connected Spaces**
As our lives and physical environments become even more connected online, we're faced with dilemmas. Should I allow my personal data to be used if it improves my daily life? Should my everyday objects be online? This space allows makers and learners to explore these dilemmas through a series of interactive experiences and mischievous interventions. 

**MozEx (Art Exhibit)**
MozEx is an art exhibition with a 21st-century twist. Curated by the digital learning teams at both the Tate and the V&A, this space showcases dynamic digital artwork that spans many disciplines and media. Created by both individual practitioners and cross-disciplinary collaborations, the exhibit will explore the value of art to society through Web literacy, digital inclusion and accessibility, privacy, policy, and hacking.

---

@carrie-ann @kristinashu this isn't quite tweet-length. Do I need to cut these descriptions back even further or will this wordcount work?

**Comment by edrushka** [comment]
Calling this final copy unless design dictates otherwise.

**Comment by edrushka** [comment]
Closing. Pull text from final festival guide InDesign file. Content in this ticket has not been through final proof-reading.
