### ISSUE TITLE
Guide: Write Non-EN sessions

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/Mozfest2016_production#113]
For 2016 Festival Guide. Write Non-EN sessions

Include: 
- Highlight that we’re supporting non-EN sessions through a range of supports (e.g. live translation, localizing session materials etc.). 
- Emphasize that Mozilla believes the internet should be inclusive to everyone.
- If possible, highlight specific sessions

**Comment by edrushka** [comment]
@Saallen @marcwalsh I wonder if we need an entire section for this. I mentioned the number of languages in the intro in #108.

**Comment by edrushka** [comment]
**Draft copy:**

Inclusion at MozFest

MozFest typically welcomes attendees from more than X countries. This year, we're taking our first steps into multi-language programming by supporting sessions in six languages in addition to English: French, Spanish, German, Italian, Hindi and Arabic. 

Additionally, we'll provide BSL (British Sign Language) interpretation for the deaf community attending the festival, and captioning of our ‘Dialogues and Debates’ speakers series on viewing monitors spread throughout the venue.

---

@Saallen @marcwalsh what do you think? Does this information warrant inclusion in the festival guide?

**Comment by Saallen** [comment]
I think we should phrase this a bit differently as we have not publised this anywhere else. Could we say something like" This year we are working with some key member of the deaf community to build out our event to be more inclusive. We are offering BSL and captioning in some of our sessions for the first time as we explore how to be more effective and inclusive in this community."

**Comment by edrushka** [comment]
Yah, after talking to Heather I'm actually going to re-write this entire section. She had some great tips about communicating how we're supporting other people to excel in this space, rather than trying to excel ourselves. Draft 2 coming later this week.

**Comment by edrushka** [comment]
A Multi-Lingual MozFest

MozFest welcomes attendees from more than 50 countries who speak a stunning diversity of languages. We've been deeply inspired by the work and dedication of the localization community to make the web a more inclusive space for the millions of users who do not speak English. This year, we're taking our first steps into multi-language MozFest programming by supporting sessions and activities in six languages in addition to English: French, Spanish, German, Italian, Hindi and Arabic. 

---

@hjbailey your thoughts?  (this is for the printed festival guide)

**Comment by edrushka** [comment]
@carrie-ann here is the final copy for the Multi-lingual Mozfest (non-EN sessions) piece

---

A Multi-Lingual MozFest

MozFest welcomes attendees from more than 50 countries who speak a stunning diversity of languages. We've been deeply inspired by the work and dedication of the localization community to make the web a more inclusive space for the millions of users who do not speak English. This year, we're taking our first steps into multi-language MozFest programming by supporting sessions and activities in six languages in addition to English: French, Spanish, German, Italian, Hindi and Arabic.

**Comment by edrushka** [comment]
Closing. Pull text from final festival guide InDesign file. Content in this ticket has not been through final proof-reading.
