### ISSUE TITLE
Guide: Write Participation Guidelines

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/Mozfest2016_production#114]
For 2016 Festival Guide. Write Participation Guidelines
Include: 
- short version of guidelines
- list festival@mozilla as support
- no link to larger guidelines (linked on the web)

**Comment by edrushka** [comment]
@Saallen Do we want the short version from the [poster](https://drive.google.com/drive/u/0/folders/0B4Q8pzCpDS_eVHJ0Mlc2MWUtX0U) or from the [website](https://mozillafestival.org/guidelines) (would include Respect, How to Treat Each Other sections, plus condensed version of Raising Issues)?

**Comment by Saallen** [comment]
With this I think from the Website is a better version to build from.
I dont think we need how to raise issues as it will be on the back of the name badge

**Comment by edrushka** [comment]
The Mozilla Festival respects Mozilla's community participation guidelines. These guidelines cover our behaviour as participants, facilitators, space wranglers, staff, volunteers, vendors, and anyone else involved in making MozFest possible.

**How to treat each other**
be respectful and welcoming
try to understand different perspectives
do not threaten violence
empower others
strive for excellence
don‘t expect to agree with every decision

Are you seeing behaviour that doesn't respect these guidelines? Email festival@mozilla.org

**Comment by Saallen** [comment]
Looks great. Thanks

**Comment by edrushka** [comment]
@Carrie-ann this is ready for the guide. Final copy for the Participation Guidelines section:

The Mozilla Festival respects Mozilla's community participation guidelines. These guidelines cover our behaviour as participants, facilitators, wranglers, staff, volunteers, vendors, and anyone else involved in making MozFest possible.

**How to treat each other:**
Be respectful and welcoming
Try to understand different perspectives
Do not threaten violence
Empower others
Strive for excellence
Don‘t expect to agree with every decision

Are you seeing behaviour that doesn't respect these guidelines? Email festival@mozilla.org

**Comment by edrushka** [comment]
Closing. Pull text from final festival guide InDesign file. Content in this ticket has not been through final proof-reading.
