### ISSUE TITLE
Add template for asking facilitators about L10N

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/Mozfest2016_production#118]
As requested on the space wranglers call, draft some text that Wranglers can use to reach out to 2nd language facilitators to coordinate the L10N options.

Add to this doc: https://public.etherpad-mozilla.org/p/festival-facilitatoremails16

cc @Saallen

**Comment by edrushka** [comment]
@Saallen what do you think of this?

Hi <name>,

We're so thrilled you'll be joining us at MozFest next month.

When you submitted your session proposal, you indicated that you can present some, or all, of your session in a language other than English. I wanted to follow up on that.

MozFest 2016 will support six spoken languages in addition to English: French, German, Arabic, Italian, Spanish and Hindi. We are encouraging session facilitators to incorporate these language in one or more of the following ways:
- presenting your session entirely in another language, with our without translation
- presenting part of your session in another language
- including multi-lingual support material for your session
- encouraging breakout conversations in multiple languages
- using non-English websites or tools as examples 

We will support you with whatever degree of translation you need.

Please let me know if you are still interested in including languages other than English in your session, and we can discuss options for translating (if required).

Thanks

**Comment by SpikeUK** [comment]
A couple of change suggestions if I may please @edrushka 

> When you submitted your session proposal, you indicated that you can present some, or all, of your session in another language.....

may be should be 

> When you submitted your session proposal, you indicated that you can present some, or all, of your session in a language other than English.....

and

> presenting your session entirely in another language, with our without translation

may be should be

> presenting your session entirely in a language other than English, with or without translation to English

and finally 

> presenting part of your session in another language

could be

> presenting part of your session in a language other than English

Hope this helps :)

**Comment by Saallen** [comment]
Hey
- both look good to me but I would like this email to go out post travel stipends email.
  So while yes this email should be sent- could you also make a small paragraph which lets the facilitator know more comms will come for those who will do all or part of their session in a language other than English?

The next comms email will be congratulating those facilitator who have been accepted and what they should expect in the coming weeks

**Comment by edrushka** [comment]
> could you also make a small paragraph 

Do you mean a small paragraph for the travel stipends email? Sure, I can do that.

Clarifying the order of email sends. Is this correct?
1) Email to all accepted sessions
2) Travel stipends email
3) Non-EN sessions email

**Comment by edrushka** [comment]
@Saallen when can we send the Non-EN sessions email?

**Comment by Saallen** [comment]
@edrushka we must send the first email- welcoming them them first. 
We are waiting on two spaces to complete their curation then we will send the official email
