### ISSUE TITLE
Build program of support for BSL

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/Mozfest2016_production#119]
Two spaces (Badges & Science) have a session they'd  like to do in BSL (British Sign Language). 
Ian said he may be able to hook us up with interpreters from the BBC.

@Saallen @marcwalsh @hjbailey are there other programmatic elements of the festival, like mainstage keynotes, D&Ds or facilitator training we should support with interpretation?

**Comment by marcwalsh-zz** [comment]
I have a couple of companies in the UK quoting on having on-demand video BSL translators for sessions that need them.  I'll be able to let you know costs for these end of next week.

**Comment by edrushka** [comment]
Julie also has a session in her space that needs BSL.

**Comment by edrushka** [comment]
Any updates on costs, @marcwalsh?

**Comment by edrushka** [comment]
Link for interpretation services provided by the Royal Association for Deaf People (RAD): http://www.royaldeaf.org.uk/services-partners/communication-services/interpreting-and-events/

**Comment by edrushka** [comment]
Any updates? Are we still looking at separate BSL or will this be wrapped into the live-captioning in #151?

**Comment by edrushka** [comment]
BSL on mainstage this year 👍
