### ISSUE TITLE
SOW for design contractor

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/Mozfest2016_production#12]
Based on the asset review in #11, write a job description for the contract designer position.

cc @Saallen @hannahkane

**Comment by kristinashu** [comment]
@xmatthewx is this done?

**Comment by xmatthewx** [comment]
Nope. You and I should do it in collaboration with @edrushka and Marc. I don't think I have all the info required in my brain.

**Comment by edrushka** [comment]
Marc has a list going here: https://github.com/MozillaFoundation/Mozfest2016_production/issues/23#issuecomment-234269137

**Comment by edrushka** [comment]
Ooops - deleting. This was for the JD, not the list of possibles.

**Comment by edrushka** [comment]
Any chance we could complete this task this week? That way we can start assessing some of the shortlist from #23 next week. I can do a first draft Thursday if that helps.

**Comment by xmatthewx** [comment]
@edrushka – it would be very helpful to have a draft from you, even if it has big blanks for us to fill in re: design specific things. You've done many more of these contracts than us.

**Comment by edrushka** [comment]
Here's a [draft scope of work] (https://docs.google.com/document/d/19cMw9HaFoUPC_hGr9ZZwrMfPCsRo8l5crkCjwHVO_Ec/edit). @marcwalsh please review and add any other tasks you think should be included.

**Comment by Saallen** [comment]
Hey
 jumping in and adding my two cents to the doc
🌺

**Comment by xmatthewx** [comment]
All the details look great in this and the job posting.

**Comment by Saallen** [comment]
I am worried that wayfinding design and execution will clash with slide design and retouch the week preceeding the festival.
 Last year the team we hired to cut the vinyl worked until very late both nights pre festival. They worked exclusively on wayfinding and implimentation, and the timeline was tight. I know we want to be able to design the wayfinding piece earlier but it is a massive piece of work, and the impliementation can only take place from the Wed- Fri.
I think we might need separate designer to help with slides or at least have staff support here- @xmatthewx is there staff who can work with MarkS and high level guests pre festival if we need the extra support?

**Comment by xmatthewx** [comment]
Yes. We could work on the slides. I recommend that we focus on a strong template, rather than specific content (for people than other MarkS).

**Comment by Saallen** [comment]
Totally agree- content should not be our responsability apart from Mark.
One solid template, that other people work within - thx

**Comment by xmatthewx** [comment]
This is done

**Comment by xmatthewx** [comment]
@secretrobotron - link above to the scope of work for your enjoyment and reference
