### ISSUE TITLE
Localize 'one web'

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/Mozfest2016_production#124]
I've reached out to @hjbailey to get 'One Web' localized in our six supported languages.
- [x] French
- [x] German
- [x] Hindi
- [x] Arabic
- [x] Spanish
- [x] Italian

**Comment by Saallen** [comment]
Arabic translation below
Translated:
Decentralized
Localized
One inclusive web
Innovative
Literate
Secure

London
October 28-30 2016
Festival

Arabic:
لا مركزية
مُوطّنة
وب واحدة تسع الكل
مبتكِر
مثقّف
آمن

مهرجان
لندن
٢٨-٣٠ أكتوبر ٢٠١٦

note from Khaled: (I had to reorder the last three lines so they make sense in Arabic, so
the they are 3,1,2.)

Remember Arabic works Right to left ;)

**Comment by Saallen** [comment]
Italian

One Web - Il Web

Decentralized - Decentralizzato
Localized - Tradotto
One - Unico
Inclusive - Inclusivo
Web - Web
Innovative - Innovativo
Literate - Conoscenza
Secure - Sicuro

London - Londra
October 28-30 2016 - 28-30 Ottobre 2016
Festival - Festival

**Comment by marcwalsh-zz** [comment]
Hindi:

One Web   : एक वेब
Decentralized : विकेन्द्रीकृत
Localized : स्थानीयकृत, स्थानीकरण
One : एक
Inclusive : सम्मिलित, समावेशी
Web : वेब
Innovative : अभिनव, नवीन, परिवर्तनात्‍मक
Literate : साक्षर, शिक्षित
Secure : सुरक्षित
London : लंडन
October 28-30 2016 : 28-30 अक्टूबर 2016
Festival : त्योहार, महोत्सव

**Comment by edrushka** [comment]
Hey @hjbailey - do you think you'll be able to get French, German or Spanish?

**Comment by marcwalsh-zz** [comment]
**Spanish:**

Decentralized: Descentralizada
Localized: Localizada

One / inclusive / web, Una / web / inclusiva   <==  Note this breaks the design. (/ = new line)

Innovative: Innovativa
Literate: Alfabetizada   <==  I am not particularly sure about this one.
Secure: Segura

**Comment by marcwalsh-zz** [comment]
**French:**

Decentralized: Décentralisé
Localized: Localisé (TN: I’m torn here, it’s jargon. To have a more obvious reference to l10n, it might be better to say Traduit (Translated), even if, of course, it’s not the same thing)
One / inclusive / web: Un / Web / inclusif <== Also breaks design
Innovative: Innovant
Literate: Alphabétisé
Literate: Sûr

London: Londres
October 28-30 2016: 28-30 octobre 2016
Festival: Festival

**Comment by marcwalsh-zz** [comment]
**German:**

Decentralized: Dezentralisiert
Localized: Lokalisiert
One: Ein
inclusive: offenes
This is literally "open", but matches better here than literal translations "allumfassendes" (negative connotations for surveilling everything) or "inklusives" (mostly used for people with disabilities).
web: Web
Innovative: Innovativ
Literate: Bildend
Secure: Sicher

**Comment by marcwalsh-zz** [comment]
That's all the translations completed! @edrushka (I'm still not allowed to close issues) are you able to tick all them off and close the issue please?

**Comment by edrushka** [comment]
Closing this but cc-ing @sabrinang first. Here are all the translations, Sabrina!

**Comment by sabrinang** [comment]
Excellent! Thanks everyone! :+1:

**Comment by sabrinang** [comment]
For Arabic, it isn't clear what _one web_ alone is. I only have the translation above in the context of _one inclusive web_ = "وب واحدة تسع الك

**Comment by edrushka** [comment]
@hjbailey any chance you could ask Khaled to localize the phrase "one web"? 

![screenshot 2016-08-29 13 01 39](https://cloud.githubusercontent.com/assets/4515662/18934264/9446ca1e-858d-11e6-955c-4301075ffe9b.png)

**Comment by edrushka** [comment]
One Web
وِب واحدة
 One
وِب
 Web
واحدة

If وِب is too narrow for the design, you can alternatively use شبكة but
that is more generic as it means network, net, web, or even grid (while
وِب is just Arabic transliteration for web).

---

cc @sabrinang (from Khaled)

**Comment by sabrinang** [comment]
Is one web alone واحدة وِب then? The stacked copy is still a bit unclear for me and I want to make sure how it looks inline (will be using it to accent stage backdrop)

<img width="1131" alt="screen shot 2016-09-29 at 11 46 25 am" src="https://cloud.githubusercontent.com/assets/2492510/18967532/6685866c-863a-11e6-9c2e-d92be110d527.png">
