### ISSUE TITLE
Creche Supplier

### ISSUE THREAD

**Issue by marcwalsh-zz** [MozillaFoundation/Mozfest2016_production#126]
Book creche supplier for the festival weekend.
## 

Requirements:

Saturday 29th: 10am  - 5pm
Sunday 30th: 11am - 4pm

**Comment by marcwalsh-zz** [comment]
Contacted Tinies for quote as last year and our contact is currently out of office until Sep 2nd.

**Comment by Saallen** [comment]
Proposed location for the Creche- 2nd floor
Opening times
Saturday 10am- 5pm
Sunday 11am - 4pm

All sign up captured via https://docs.google.com/a/mozillafoundation.org/forms/d/e/1FAIpQLSd0lBHH4xNIKSQ7D2ZNJlj4rwayRJw3aDbFmmud6JICdIjyzg/viewform?c=0&w=1

**Comment by marcwalsh-zz** [comment]
Awaiting new quote from suppliers, once sent terms will be passed through legal.

**Comment by Saallen** [comment]
Contract currently on bugzilla 
So closing this issue
