### ISSUE TITLE
5KM Run

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/Mozfest2016_production#129]
What: 5km run organised by Matt  from Digital me for Sunday morning at 9am. Sign up page on the Website.

Required:
*Investigate T shirts or sweat bands
*share information on Shower facilities
*Coordinate group picture
- Insure the route is available

**Comment by Saallen** [comment]
looping in @marcwalsh here as he has a potential route for @mattdigitalme

**Comment by marcwalsh-zz** [comment]
Yo @mattdigitalme

This starts at the entrance of Ravensbourne, runs around the O2, down the grass areas to the ecology park and back up along the thames to Ravensbourne. It’s 4.84KM.

![unnamed_route](https://cloud.githubusercontent.com/assets/14007066/18786755/736096e4-8197-11e6-8e08-39ea8ee85bdb.jpg)

It's a pretty flat route, but takes you all the way around the Peninsula, so you'd run the entire way around The O2, then down towards The Pilot Inn pub towards and around the Ecology Park and the back up along the Thames.

**Comment by mattdigitalme** [comment]
@marcwalsh This looks perfect! :)

**Comment by marcwalsh-zz** [comment]
🙌 Closing!
