### ISSUE TITLE
Identify places to post design contractor position

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/Mozfest2016_production#13]
Please add to this list of places/people we should share the contract designer posting (reminder this contractor will ideally be based in London):

- Ravensbourne
- Marc (MozFest production assistant)
- Luca (Tate)
- Julie (Arts Award)
- etc.

cc @xmatthewx @Saallen

**Comment by edrushka** [comment]
We're going to start with Ravensbourne. If that doesn't yield results by Aug 10 we'll post more widely.

**Comment by xmatthewx** [comment]
Listing with Ravensbourne. Open new ticket only if needed.
