### ISSUE TITLE
Design Wayfinding: Concept

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Mozfest2016_production#131]
This ticket is to start thinking of all the wayfinding pieces holistically and to explore different concept directions.

The primary piece of work will be the floor vinyl and signage:
- Design Wayfinding: Floor vinyl and internal signage #89

Other related tickets are:
- Design Wayfinding: Floor plan maps #91
- Design Wayfinding: Space banners #102
- Design Wayfinding: Info booths #90
- Design Wayfinding: session signage #92
- Design Wayfinding: science fair and closing demo info cards #94

**Comment by ed-yau** [comment]
[Wayfinding Concept.pdf](https://github.com/MozillaFoundation/Mozfest2016_production/files/469724/Wayfinding.Concept.pdf)
Current Ideas & Thinking for Concept Direction

**Comment by ed-yau** [comment]
![identified spaces](https://cloud.githubusercontent.com/assets/21972436/18473343/539faf9c-79b4-11e6-97b2-50c4a6f3ca0d.jpg)
![moodboard](https://cloud.githubusercontent.com/assets/21972436/18473346/56b98bee-79b4-11e6-894d-98e8d7032253.jpg)
![vinyl graphics-01](https://cloud.githubusercontent.com/assets/21972436/18473466/011aae10-79b5-11e6-9574-42847ce3cb24.jpg)
![1-01](https://cloud.githubusercontent.com/assets/21972436/18473469/036dc79c-79b5-11e6-9960-4531c345fce0.jpg)
![2](https://cloud.githubusercontent.com/assets/21972436/18473472/04cb5122-79b5-11e6-983e-7400e542789d.jpg)
![3](https://cloud.githubusercontent.com/assets/21972436/18473473/067762e0-79b5-11e6-8815-1369ddae5cf1.jpg)

**Comment by kristinashu** [comment]
Excellent, thanks for sharing @ed-yau!

**Comment by edrushka** [comment]
Love this, @ed-yau! Nice job.

**Comment by xmatthewx** [comment]
@sabrinang – let's pick two space ... a long name and a short name ... share the icons so @ed-yau can mock up floor signage.

**Comment by kristinashu** [comment]
@ed-yau once you've explored what Matthew mentioned above, you can get started on:
- Design Wayfinding: Floor vinyl and internal signage #89 (getting into the details of the signage like were exactly we will need the signs and how many of each...)
- Design Wayfinding: Space banners #102 (simple flags with the space icon and name on it)
- Design Wayfinding: Floor plan maps #91 (both a general map for the Festival Guide and more detailed ones specific to each floor with will appear on each floor)

**Comment by xmatthewx** [comment]
Concept is in good shape. We should get sign off from fest planners after we have an idea about banners. Maybe we share with them Monday or Tues?

**Comment by edrushka** [comment]
@xmatthewx let me know if you want me to book a 30min call.

**Comment by ed-yau** [comment]
@kristinashu @edrushka @xmatthewx @sabrinang 
Please find development on the Wayfinding concept.
[Wayfinding Developed Concept.pdf](https://github.com/MozillaFoundation/Mozfest2016_production/files/479027/Wayfinding.Developed.Concept.pdf)
Here is focus on the Space banners and a brief overview on all the wayfinding formats based on this concept direction that could work in the Ravensbourne space.
![wayfinding1](https://cloud.githubusercontent.com/assets/21972436/18619664/7d800fb0-7dfa-11e6-93ef-ae774bfc44eb.jpg)
![wayfinding2](https://cloud.githubusercontent.com/assets/21972436/18619665/82798514-7dfa-11e6-9c35-d98fa8d919f0.jpg)
![wayfinding3](https://cloud.githubusercontent.com/assets/21972436/18619666/87f734d2-7dfa-11e6-95fb-1da9f0e0db4c.jpg)
![wayfinding4](https://cloud.githubusercontent.com/assets/21972436/18619668/8ca55cd4-7dfa-11e6-9f25-32c3f5708c47.jpg)
![wayfinding5](https://cloud.githubusercontent.com/assets/21972436/18619671/9195141e-7dfa-11e6-94a6-8b23f07f5041.jpg)
![wayfinding6](https://cloud.githubusercontent.com/assets/21972436/18619673/9679ddfc-7dfa-11e6-9a16-71794fb9d162.jpg)

**Comment by ed-yau** [comment]
Door Signage, Directional Arrows (Column & Walls), and Floor Maps (Column & Walls & lifts) have not yet been visualised... but format wise would follow the use of a print mounted onto foam board. A4 mounted sheet stuck over an A3 mounted sheet.

**Comment by kristinashu** [comment]
@ed-yau love the layering and all the colors, these are looking great! 

My only concern would be the amount of set up work needed to do all three types (wall, balustrade, and rafters) of spaces signage, but will discuss with everyone. 

One piece we had last year but don't see in these mockups are the space names in vinyl (both on the stairs and on the floor) with arrows. I can't find a great example from last year but here's one pic from the installation: 
<img width="1321" alt="screen shot 2016-09-19 at 9 02 24 am" src="https://cloud.githubusercontent.com/assets/1068783/18639523/19a03570-7e49-11e6-8922-4c9894bdff04.png">

Next step is to get approval from Sarah, @edrushka a 30min meeting would be great!

**Comment by xmatthewx** [comment]
This is really great. I really the three items as a system (space, floor number, one web). I'm not sure that we will need all three placements (hanging, railing, wall), but I like the flexibility that would give festival planners. Given how much we fill the space with people and stuff, Wall banners probably wouldn't be too visible. Worth discussing. 

Let's get this approved as our approach first, and then dig into the specifics of how this system will work with the current plan for spaces second.

**Comment by sabrinang** [comment]
I like hanging space banners that could be used on the rafters and balustrades. The modular elements would make it flexible for us to mix and match with the layering effect echoed here and great usage of colour. I am not crazy about using foam core as a material and I think when all the spaces are set up we won’t have that much space to lean these on the walls so I don’t know how practical this application on the walls would would be. 

I like the inclusion of the pattern on the one web banner and the large scale number. I’m thinking for the title of the spaces could they be larger? or how does it look with the display font? I would want the space title to be legible from far distances and I’m afraid the titles would be too small.

**Comment by kristinashu** [comment]
Marc shared a link to the printer's site which offers some foam core alternatives https://www.pixartprinting.co.uk/wide-format/printing-flat-bed-rigid-materials/

**Comment by xmatthewx** [comment]
To make space names larger, we could do the names vertically coming down from a slightly smaller space icon.

**Comment by kristinashu** [comment]
@marcwalsh aside from the floor maps (example below), do you have access to a more detailed building map? This will be useful for planning out the vinyl flooring...

<img width="509" alt="screen shot 2016-09-19 at 3 20 03 pm" src="https://cloud.githubusercontent.com/assets/1068783/18650899/ba8cfd46-7e7c-11e6-81db-6925d2bacb1f.png">

**Comment by marcwalsh-zz** [comment]
@ed-yau @kristinashu @xmatthewx 

@Saallen started issue #128 to create a huge notice board in the large open space under the Ravensbourne branding on the ground floor. Just thought I'd tie both these issues together.

**Comment by edrushka** [comment]
Link to floorplans (note: some of these are slightly out of date): ~~https://drive.google.com/drive/folders/0BymL-b3rLMtZekE0NnZsQ0xzc1k?usp=sharing~~

EDITING THIS COMMENT- USE THESE MAPS FOR CORRECT FLOOR NUMBERS-SA
https://drive.google.com/drive/folders/0B_B9-Ny1xBaRX1BUQVpER3dIaWM

**Comment by ed-yau** [comment]
@edrushka these are great! Many thanks for supplying these plans! These detail plans are essential for general wayfinding design practice and planning in large buildings with multiple floors! It means I can also put together a clear PDF pack using these to show exactly where all the types of signs should be located. It will give you an accurate idea of quantities needed for each type of sign, for the print production process ahead, as well as also working as a handy map for those involved in the installation of these signs in the space. I know some floors will be out of date but from my recent visit to the building I will work with consideration of these new walled spaces on these plans.

**Comment by kristinashu** [comment]
@ed-yau we meet with Sarah and she is happy with the direction so we can go ahead and move forward! 

Here are a few notes and things to consider while moving forward:
- likes the layering effect, coloring and strong visual branding
- if there are two space on one floor, how would this be handled it?
- leaning signs will only be possible in a few places
- love the hanging signs
- concerned about the amount of work to install (and remove) vinyl on the floor so we should try to limit the amount we use
- floor vinyl is particularly useful in entryway so when people look over the rails and down to the foyer, there's cool branding there
- how are the arrows functional?
- Concerned about the numbering on lift: There are a lot of lifts. How valuable is it to have these? As awesome as these look, we probably shouldn't do them.
- Instead, could just do something on the 1st or 2nd floor lift. Maybe try the 'one web' circle on main floor elevator door...

Concept stage for wayfinding is done! We're ready to get into the details in https://github.com/MozillaFoundation/Mozfest2016_production/issues/89

@edrushka is there a time we could meet with @ed-yau to go over the building map and point out key areas? Let us know which spaces are final and which are TBD. After 7pm London time usually works for Ed.

**Comment by kristinashu** [comment]
Reviewed feedback at our meeting. Closing this and applying this concept to:
- Design Wayfinding: Floor vinyl and internal signage #89
- Design Wayfinding: Floor plan maps #91
- Design Wayfinding: Space banners #102
