### ISSUE TITLE
One Web Visual Direction - Pixel Sorting Art & Textures

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Mozfest2016_production#132]
Art Direction Planning Doc (for reference): https://docs.google.com/presentation/d/1Wr2XK-ogr-72XnMqdmLU2Rf64S-5ctC23OimMwnsquY/edit#slide=id.g16808a0425_0_50

![mozilla-festival_visual-exploration_one-web_v5](https://cloud.githubusercontent.com/assets/2492510/18218510/f3588036-7117-11e6-88f8-8e6addc615ab.png)

For this years visual direction, I want to utilize pixel sorting _(a type of glitch art)_ as a part of the digital neon visual system for One Web theme. The art will be inspired by the angles of from the grid system abstracted from the Mozfest cubes (mainly the 60 degree angle that the trapezoid shapes, patterns and localized text use too) and incorporating the neon palette.

The example applications in the mockups show white elements (One Web lockup) on top of this art. It should provide enough contrast to be legible. The art can also be masked on the lockup circle and be too busy that the text gets lost. 

<img width="1061" alt="screen shot 2016-09-02 at 2 33 58 pm" src="https://cloud.githubusercontent.com/assets/2492510/18218974/ffcab7dc-711a-11e6-8969-f73d5d46b6c9.png">
A vector texture will provide the flexibility to crop in for a macro texture (like the thicker bar style on the left example) and if micro texture if used in its entirety. If we have one scalable texture we can crop from different sections and apply them in different ways so we probably do not need more than 1. 

Deliverables:
- 1 hi-res scalable texture that can be printed large scale (stage) and smaller printed assets (.svg). 

As for timeline, the sooner we have it we can include it in more assets mockups since contractors will be onboarded next week but they can use placeholder textures til we have it. Ideally we will have the texture by end of next week for contractors to use (finalized texture by end of next heartbeat at the latest).

---

@gvn does awesome image processing art and we discussed about the above so he can help. I am excited to showcase some of his art!

**Comment by gvn** [comment]
So, a couple things!
1. Upscaling a pixel sort is achievable by doing a "nearest neighbor" resample in Photoshop (or other tools). I gave some thought to converting a pixel sorted bitmap to SVG, but I don't think the end result would rasterize any differently.
2. Here's an initial draft of a texture generated with one of my processes using the palette from the design doc. This is a different approach than pixel sorting, but feels like it fits the direction still. Curious to hear your thoughts!

<img width="1343" alt="mockup1" src="https://cloud.githubusercontent.com/assets/206379/18361579/490d9284-75b7-11e6-944d-e6534d276727.png">

The background is all SVG, so easily rasterized to whatever size and pixel density you need. 👍

**Comment by sabrinang** [comment]
Thanks for posting up a draft and exciting to see! My main thoughts and feedback would be around how visually busy the text area feels that could interfere/distract from the words so here is some ideas to try: 

<img width="1206" alt="screen shot 2016-09-08 at 1 00 05 pm" src="https://cloud.githubusercontent.com/assets/2492510/18364718/32372bee-75c4-11e6-99d7-b773a4ed7c2a.png">

Can we also try making the bg brighter closer to the purple and blue in the palette?

**Comment by gvn** [comment]
Here's the AI file if you want to try tweaking some stuff directly! [fox-diff.ai.zip](https://github.com/MozillaFoundation/Mozfest2016_production/files/462614/fox-diff.ai.zip)

I can work on some variations and alternatives as well. Just wanted to get the ball rolling. :metal:

**Comment by SpikeUK** [comment]
May I just comment please that I am really loving the direction you all are going with this design work. And I **NEED** that purple for the volunteer's t-shirts :)

**Comment by Pomax** [comment]
A random little attempt using Processing, with glitch distortion turned off, and on respectively:

![noglitch](https://cloud.githubusercontent.com/assets/177243/18367004/e87ad028-75cd-11e6-93c6-843be8b4c487.gif)

![glitched](https://cloud.githubusercontent.com/assets/177243/18367007/eb31170a-75cd-11e6-8223-70d2a373822c.gif)

Code used:

```
class Drop {
  int age, x, y, MAX_AGE = 100, RAND_AGE = 100, death;
  Drop(float x, float y) {
    age = (int)random(0,MAX_AGE);
    death = MAX_AGE + (int)random(RAND_AGE/2,RAND_AGE);
    this.x = (int)x;
    this.y = (int)y;
  }
  void draw() {
    if (age > MAX_AGE) {
      drawDying();
    } else {
      drawAlive();
    }
    age++;
  }
  void drawAlive() {
    for (int i=age; i>=0; i--) {
      float f = 1 - (float)i/(float)death;
      color fc = color(f * 250, f*27 + (1-f) * 251, (1-f) * 171 + f * 221, (1-f) * 255);
      fill(fc);
      stroke(fc);
      rect(x - i*0.7, y+i, 2,2);
    }
  }
  void drawDying() {
    float a = map(age, MAX_AGE, death, 255, 0);
    for (int i=age; i>=0; i--) {
      float f = 1 - (float)i/(float)death;
      color fc = color(f * 250, f*27 + (1-f) * 251, (1-f) * 171 + f * 221, (1-f) * a);
      fill(fc);
      stroke(fc);
      rect(x - i*0.7, y+i, 2,2);
    }
  }
  boolean isDead() {
    return age >= death;
  }
}

ArrayList<Drop> drops = new ArrayList<Drop>();
int dropCount = 300;
int[] distortionMap;
boolean useDistortion = false;

void setup() {
  size(500,500);
  for(int i=0;i<dropCount; i++) {
    addRandomDrop();
  }
  if (useDistortion) {
    distortionMap = new int[height];
    int runner = 0;
    for(int i=0; i<height; i++) {
      if (random(1)>0.5) {
        runner += (int)random(1,10);
      } else {
        runner -= (int)random(1,10);
      }
      distortionMap[i] = runner;
    }
  }
}

void addRandomDrop() {
  int p = 100;
  drops.add(new Drop(random(-p,p+width), random(-p,p+height)));
}

void draw() {
  background(109,34,175);
  int removed = 0;
  for(int dd=drops.size()-1; dd>=0; dd--) {
    Drop d = drops.get(dd);
    d.draw();
    if (d.isDead()) {
      drops.remove(dd);
      removed++;
    }
  }
  while(removed-- > 0) {
    addRandomDrop();
  }

  if (useDistortion) {
    // distort the lines
    loadPixels();
    for (int i=0; i<height-1; i++) {
      int w = width-distortionMap[i];
      w = constrain(w,0,width);
      arrayCopy(pixels, i*width+distortionMap[i], pixels, i*width, w);
    }
    updatePixels();
  }

  textAlign(CENTER, CENTER);
  textSize(40);
  fill(255);
  text("WHOOOOA MOZFEST", width/2, height/2);
}
```

**Comment by gvn** [comment]
@sabrinang – Here are some more SVG fragment variations that you can feel free to organize & use however you like! 🎉 

[fragments.zip](https://github.com/MozillaFoundation/Mozfest2016_production/files/462717/fragments.zip)

[burst-fragments.zip](https://github.com/MozillaFoundation/Mozfest2016_production/files/462946/burst-fragments.zip)

**Comment by sabrinang** [comment]
fragments are lookin' fine :+1: 
<img width="1277" alt="screen shot 2016-09-08 at 4 47 40 pm" src="https://cloud.githubusercontent.com/assets/2492510/18370703/fe60abd6-75e3-11e6-8541-661cc83e1c8d.png">
<img width="1279" alt="screen shot 2016-09-08 at 5 15 39 pm" src="https://cloud.githubusercontent.com/assets/2492510/18371283/e86fc4ca-75e7-11e6-911a-bb66e06793e7.png">

**Comment by xmatthewx** [comment]
This is all so so awesome. 

@Pomax @gvn @sabrinang – it'd be amazing if you ran a workshop at Mozfest on generative art ... and created something we then used on the last day. cc @flukeout @simonwex

**Comment by gvn** [comment]
Here's an example of a composite "pixel sort" process and triangulation process. 

For a little extra grit and texture:

![composite-w-logo](https://cloud.githubusercontent.com/assets/206379/18405086/d57bd068-76a3-11e6-8f78-35711a97eeba.png)

[composite-w-logo.ai.zip](https://github.com/MozillaFoundation/Mozfest2016_production/files/464973/composite-w-logo.ai.zip)

**Comment by gvn** [comment]
@sabrinang – Here's some more pixel sorts based on the fireworks image:

[pixel-sorts.zip](https://github.com/MozillaFoundation/Mozfest2016_production/files/470898/pixel-sorts.zip)

Let me know if you need any more!

**Comment by sabrinang** [comment]
@gvn these pixel sorts are great! 

I just experimented with different crops and transparency/blending modes and we can achieve a lot of effects with them:
![pixelsort-sample-experiments](https://cloud.githubusercontent.com/assets/2492510/18495859/ec16f4c6-79d5-11e6-8c05-6f9f719294a3.png)

@ed-yau @Carrie-ann Please experiment with the .svgs in the .zip file provided above and incorporate them as you see fit for layering in your projects :+1:

**Comment by Pomax** [comment]
@sabrina @xmatthewx @gvn I'd be for a generative session, I wrote my Processing sketch in maybe 10 minutes, easy enough to explain a pixel grid to people and then go "and now you get to mess it up _tremendously_" =D

**Comment by edrushka** [comment]
Love where you're going with these, @gvn and @sabrinang. Would be so cool to incorporate in some of the generative ideas, like #143

**Comment by kristinashu** [comment]
These look great! I've added them to the style guide folder.
