### ISSUE TITLE
Chat about event app details

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/Mozfest2016_production#134]
Hi @Saallen and @edrushka , 🍰 

We have filed relevant tickets here and there and I thought having a short chat could get us all on the same page easier. Let's find time to meet on Vidyo? 😄 

Some topics I would like to chat about:
- what kind of changes will be made to [mozfest-program-2016 repo](https://github.com/MozillaFoundation/mozfest-program-2016)
- deadline for making changes on the [mozfest-program-2016 repo](https://github.com/MozillaFoundation/mozfest-program-2016) (includes all kinds of changes, e.g., labels and milestones changes... etc)
- who to give edit access to the event app spreadsheet (should be minimal set of people)
- how to fill out meta that are not included in Github but are required for the event app (duration, Space, Pathway, facilitator, location, timeblock, ... could be more)

/cc @xmatthewx

**Comment by edrushka** [comment]
Invite sent!
Meeting is for Sarah, Mavis and I. Matthew optional. Let me know if anyone else needs to attend.

**Comment by Saallen** [comment]
I have a question I have been thinking about but not asking any one
Will there be a search option on the app @mmmavis ?

**Comment by xmatthewx** [comment]
Yep. Search already exists.

**Comment by edrushka** [comment]
See it in action here: http://mozilla.github.io/mofo-allhands/2016-london/

**Comment by mmmavis** [comment]
The link Erika attached is for London All-hands. Here's the WIP MozFest 2016 version: http://mozilla.github.io/mozfest-event-app/ 🎆

**Comment by Saallen** [comment]
🌷

**Comment by mmmavis** [comment]
I'm gonna close this ticket since our chat has already happened and event app milestones have been created: https://github.com/mozilla/mozfest-event-app/milestones 🎉 thanks team
