### ISSUE TITLE
Design Festival Guide: version 1 (Sept 20) + 2 (Sept 27)

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Mozfest2016_production#135]
Based on work done in - Festival Guide Concept #69 

Deadlines:
- Content deadline [Erika]: Sept 20
- Deliver version 1 [Carrie-Ann]: Sept 20
- Design team review & feedback on 1st mock-up  [MoFo Design]: Sept 22
- Deliver version 2 (final) [Carrie-Ann]: Sept 27
- Design team review & feedback on 1st mock-up  [MoFo Design]: Sept 29

**Comment by kristinashu** [comment]
@Carrie-ann could you please attach the black and white pdf of all the content so far? We know you are still working on it and things will be moving around but we would love to get a rough idea of how the content feels.

**Comment by kristinashu** [comment]
@carrie-ann has shared her progress here: https://redpen.io/p/aq3ed683d65024fc8f

Everyone is very pleased with the overall direction!

## Specs

@marcwalsh is looking into print costs now (which would be the area if concern).

Booklet:
- A5
- Cover: textured blue cardstock with white print, half A5 length ways (270gsm)
- Inside (Main): 16pp white paper stock with full colour print (120gsm)
- Inside (Sub): 12pp slightly smaller B6 size on yellow (80gsm) 
- thread bound with yellow center stitch
- yellow fabric tape on outside binding (only ornamental) 

Map:
- A2 or A3 double sided prints (120 gsm), full colour and folded to either quarters on A2 or in half on A3

## Spreads

Design is looking great! There are some comments in Redpen but the key feedback so far is:
- add more hierarchy to the timings page (https://redpen.io/omb652c4b57946671b)
- distributing the 3 sections of content on the last page through out the booklet (https://redpen.io/vu283b856509ab69a4)
- add more multi language design asset to the Multi cultural section (https://redpen.io/vu283b856509ab69a4)

## Cover
- Experiment with different arrangements of the One Web logo on cover and glitch pattern. Consider placement of MozFest logo on front, glitch, or back.

## Content

Wrapping up content in Festival Guide content #68 

@sabrinang @edrushka @xmatthewx

**Comment by Carrie-ann** [comment]
@kristinashu With the inside yellow section for wranglers, it would be 12pp rather them 4pp due to the amount of bios we have. Just making sure we are all on the same page on size. :)

**Comment by kristinashu** [comment]
Oh yes thanks, I knew that! I've updated the comment above.

**Comment by xmatthewx** [comment]
@MozExhibit in case you haven't seen it, the festival guide design direction is set. Draft version 1 coming soon. The full photo spread in particular might offer some ideas for the art guide. https://redpen.io/p/aq3ed683d65024fc8f

**Comment by kristinashu** [comment]
@Carrie-ann here's a summary of the feedback to work this weekend.

### Feedback:

**Cover/back:** https://redpen.io/xgc9b9608397d613de
- no blue leaflet or yellow tape :( 
- Let’s try a cover with and without blue bar version
- no table of contents
- keep ‘one web’
- keep guidelines
- add MozFest logo
- updated possible art on redpen: https://redpen.io/kycfbd6747ab1d2999 (All in glitch pattern folder: https://drive.google.com/drive/u/1/folders/0B2irLVDJivhLUmZlSEFCWUk3UWc)

**Timings:** https://redpen.io/omb652c4b57946671b
- Add more hierarchy, remove “block” text

**Spaces:** https://redpen.io/sf084926c327f3b0eb
- add space icons

**Wranglers insert:** https://redpen.io/sf084926c327f3b0eb
- maybe blue text instead of black?

**D&D:** https://redpen.io/ge4cbb64deb0d2ae4f
- most of the bio images are [here](https://drive.google.com/drive/folders/0B-BKZVAww2KHRzlGOWNfc19rZGc?usp=sharing)
- content is [here](https://docs.google.com/document/d/1xHq6RnAolJNHhZzuf-UV98qNFexESoIufzJci9VvVmY/edit) 

**Last page:** https://redpen.io/vu283b856509ab69a4
Distribute the 3 sections of content on the last page throughout the booklet:
- Move the “Co-designed with Community” section to the end of the Wranglers booklet (maybe the back cover)?
- Replace one of the testimonials spreads (either entire the spread or just half) with “Multicultural MozFest”. Add languages like this example

### Other notes:

It's ok if you end up needing to add more pages to the booklet. 

Please link to the Drive folder once you have added you're working files.

Would also be great to see how this fits in with the notebook #150 and map #91.

(cc @edrushka so you're in the loop!)

**Comment by kristinashu** [comment]
@Carrie-ann here's a folder with all the wrangler images https://drive.google.com/open?id=0B4rEOP1A0tc0YkVSeUpfVjZ0a0E
We are missing 4 pics/bios and we probably won't be getting them. Please include these people's names only.

Here are all the D&D images https://drive.google.com/open?id=0B4rEOP1A0tc0YkVSeUpfVjZ0a0E

Do you need anything else?

**Comment by kristinashu** [comment]
Carrie has shared a pdf for copy edits and updated https://redpen.io/p/aq3ed683d65024fc8f:
[Mozilla Festival Guide V3.pdf](https://github.com/MozillaFoundation/Mozfest2016_production/files/507348/Mozilla.Festival.Guide.V3.pdf)

@edrushka will add her copy edits by Wednesday.

In the meantime, @Carrie-ann will:
- try an alternative options for cover
- add the MozFest2016 logo to the cover
- try a smaller map insert size
- finish up Wrangler insert (add all images/bios and retreat copy "A Festival Co-Designed with Community")
- add room for new D&D people #172
- other small design updates mentioned in redpen

**Comment by edrushka** [comment]
My Wed. edits will include Sarah's final comments and signoff. After I edit, I'll ask Stevie and Kevin to review one final time for copy gremlins (no content changes, though).
Except for adding the new D&Ds, I don't foresee major content edits. It looks really great so far!

**Comment by Carrie-ann** [comment]
@kristinashu Just so you guys have the correct measurements. The inside yellow booklet is 117mm (w) x 200mm (h), not B6. This is so the pages fit nicely to the grid within the guide. :)

**Comment by kristinashu** [comment]
Closing this ticket, we are now on the final round of review! And everything is looking awesome!
