### ISSUE TITLE
Design Festival Guide: final version - final deadline Oct 11

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Mozfest2016_production#136]
Based on work in Festival Guide version 1 (Sept 20) + 2 (Sept 27) #135 and concept work in https://github.com/MozillaFoundation/Mozfest2016_production/issues/69

Deadlines:
- Final Revisions [Carrie-Ann]: Oct 3
- Copyediting [Erika]: Oct 3-6
- Final copy edits [Carrie-Ann]: Oct 7-11
- Send to printers [Marc]: EOB Oct 11

**Comment by kristinashu** [comment]
@edrushka: @carrie-ann has updated the comps and is ready for you're final copy edits https://redpen.io/p/aq3ed683d65024fc8f

Next steps:
- Carrie to update notebook cover over the weekend (then put design in template https://github.com/MozillaFoundation/Mozfest2016_production/issues/150 - this has to go to print end of day Monday)
- Erika & co. to review final copy edits
- Designers will add small bits of feedback to redpen
- Map: Carrie to determine size and pattern for the back of the map insert (needs to coordinate with Ed https://github.com/MozillaFoundation/Mozfest2016_production/issues/91)
- (if time, maybe a glitch placeholder for missing wranglers)

cc @sabrinang @xmatthewx

**Comment by edrushka** [comment]
I've sent this to my copy editing team. I've requested they provide feedback by end of day Saturday.

**Comment by kristinashu** [comment]
Final round of copy edits is done, all the design updates are done with the exception of the glitch cover which @sabrinang is updating.

https://redpen.io/p/aq3ed683d65024fc8f

Just coordinating with @marcwalsh and the print on how they want the files set up and how we will proof the files.

**Comment by sabrinang** [comment]
The glitch cover iterations .ai is here: https://drive.google.com/file/d/0B4Q8pzCpDS_eWno3OF9zMzd5Mmc/view

<img width="1276" alt="screen shot 2016-10-11 at 9 41 12 am" src="https://cloud.githubusercontent.com/assets/2492510/19279593/e4a1d1d0-8f96-11e6-800a-dfb8ebb406aa.png">

**Comment by kristinashu** [comment]
I put this glitch into the indesign file to test it out but it's looking a little too crazy
https://redpen.io/hgaa88c1580cbf616d
Maybe we can we try using few colors?

**Comment by sabrinang** [comment]
@carrie-ann You can use the updated texture (with less yellow) and the .ai file for front and back covers is here: https://drive.google.com/file/d/0B4Q8pzCpDS_eUnNXX1BMLTZGMm8/view 

<img width="1080" alt="screen shot 2016-10-11 at 2 21 35 pm" src="https://cloud.githubusercontent.com/assets/2492510/19289134/1ac71d84-8fbe-11e6-97b5-4f28ef2efc05.png">

**Comment by Carrie-ann** [comment]
@sabrinang Great!

**Comment by sabrinang** [comment]
@carrie-ann We did a quick print test and found that the back art was making the text a bit hard to read so I updated the .ai file v4 (removed and moved over some texture for more empty space beneath for the back cover): https://drive.google.com/file/d/0B4Q8pzCpDS_ea1FEczBqUjVCN0k/view

<img width="1063" alt="screen shot 2016-10-11 at 5 08 14 pm" src="https://cloud.githubusercontent.com/assets/2492510/19293051/804c4a1e-8fd5-11e6-82a6-2a1538a8b8f4.png">

**Comment by sabrinang** [comment]
@Carrie-ann  The "youth zone" and "dilemmas in connected spaces" icons are swapped please re-arrange <img width="672" alt="screen shot 2016-10-11 at 6 18 50 pm" src="https://cloud.githubusercontent.com/assets/2492510/19294171/33363640-8fdf-11e6-9cb2-de0895a9d18d.png">

**Comment by kristinashu** [comment]
Thanks for making all the updates @carrie-ann! 

Here is the final version of the guide:
[Mozilla Festival Guide FINAL 14-10-16 SPREADS.pdf](https://github.com/MozillaFoundation/Mozfest2016_production/files/530127/Mozilla.Festival.Guide.FINAL.14-10-16.SPREADS.pdf)

and the wrangler booklet:
[Space Wrangler booklet - FINAL.pdf](https://github.com/MozillaFoundation/Mozfest2016_production/files/530134/Space.Wrangler.booklet.-.FINAL.pdf)

Carrie just needs to export the file for the printer and then we are done! 

cc @marcwalsh @edrushka @xmatthewx @sabrinang

**Comment by edrushka** [comment]
Y'all, this is stunning.  I am so, so thrilled with how it turned out. Thank you!

![happy](https://cloud.githubusercontent.com/assets/4515662/19398456/87ef2c54-9201-11e6-92ac-f22cd0483583.gif)

**Comment by xmatthewx** [comment]
![giphy 3](https://cloud.githubusercontent.com/assets/53411/19399354/1eb16c02-921f-11e6-8299-3f99f5c313c8.gif)

**Comment by kristinashu** [comment]
Amazing job! All of Carrie's print files are here:

These are Single pages, 3mm bleed with crop marks and high quality. The colours are CMYK with Pantone Reflex Blue.

Main Festival Guide - PDF labeled with FINAL 14:10:16 SINGLES

https://drive.google.com/drive/folders/0BzVQTTEXQZdXWC0xbVJuNkpkRTQ

Wrangler Booklet - PDF labeled with FINAL SINGLES

https://drive.google.com/drive/folders/0BzVQTTEXQZdXMlh0Rm1YR1cwZ3M

**Comment by kristinashu** [comment]
Guide looked great! Size, matte print, and paper turned out well.

![artboard jpg](https://cloud.githubusercontent.com/assets/1068783/20194991/946393aa-a749-11e6-9fb0-050aa4cd7fef.png)

Volunteers did however complain about the amount of work it was to assemble these packages, compared to just putting them into a tote bag.
