### ISSUE TITLE
List of tech in Ravensbourne

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/Mozfest2016_production#137]
Required- catalogue list of tech from level 5 in Raves

Purpose - Hiring of equipment for Production but also spaces. Ensuring we dont over promise, over book and can share the list

**Comment by marcwalsh-zz** [comment]
I doubt we will be able to get a list of all equipment. However I've contacted Ravensbourne asking for additional access to view all equipment on my CLR login, so I'll be able to make a smaller list of pieces that spaces may require.

**Comment by marcwalsh-zz** [comment]
Requests for Ravensbourne equipment will be made through me, and I'll check with CLR / Lauren as to if it's in stock. 

A definitive list isn't available, there's a lot of stuff (mostly video production based)!
