### ISSUE TITLE
Test and Finalize One Web Theme Colours

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Mozfest2016_production#139]
<img width="1027" alt="screen shot 2016-09-07 at 4 32 10 pm" src="https://cloud.githubusercontent.com/assets/2492510/18332095/ac28b5e6-7518-11e6-9788-08d12bdfc1a1.png">
We are using a bold palette with neons this year and we need to test:
- for print in CMYK
- for print in Pantone 
- How the palette works as a whole (example: what if yellow was neon and the rest were not?)
- finalize the palette with referencing a pantone book or printed samples

We should identify in spreadsheet what key pieces have a a higher budget for special printing and connect with what the printers can do.

**Comment by kristinashu** [comment]
@lovegushwa is checking his Pantone book to identify true neon versions and also a non-neon equivalent for each color.

**Comment by lovegushwa** [comment]
@kristinashu thanks for setting up this ticket! Will check on these this afternoon.

**Comment by kristinashu** [comment]
@lovegushwa any luck?

**Comment by lovegushwa** [comment]
@kristinashu so sorry about the wait! 

![screen shot 2016-09-21 at 5 05 03 pm](https://cloud.githubusercontent.com/assets/12228435/18733190/a51aa362-801d-11e6-8d36-77d2ff94240c.png)

**Comment by lovegushwa** [comment]
here is a really bad photo of neon colors for your reference. 

![img_20160921_165113](https://cloud.githubusercontent.com/assets/12228435/18733229/e59e396c-801d-11e6-89c5-b2b2b47b0d72.jpg)
