### ISSUE TITLE
Create MozFest moodboards

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/Mozfest2016_production#14]
Create a few moodboard options for MozFest 2016.

Previous  mood boards for signage:
- https://uk.pinterest.com/sarahretro/signage-ideas/
- https://uk.pinterest.com/mozfest14/community/

Inspiration from Ravensbourne:
https://drive.google.com/drive/u/0/folders/0B20-0lpP23c0eGVvSDR0WHRRUUk?ths=true

@hannahkane assigning you for now - please re-assign when you chose a designer!

**Comment by kristinashu** [comment]
@natalieworth @lovegushwa do you have any moodboards from last year?

Also sharing these amazing notes Natalie wrote up after her tour of Ravensbourne https://docs.google.com/a/mozilla.com/document/d/1HS_H1_cm_8f1lQOOYKeHKL7TlQRf8REtsIPLtRl8dQs/edit?usp=sharing

**Comment by kristinashu** [comment]
I've done a whole bunch of pinning https://www.pinterest.com/kristinashu/conferencefestival/ 
Now I'll start to narrow them down to a few different directions and create moodboards.

@sabrinang please add some pins if you come across anything interesting.

**Comment by natalieworth** [comment]
@kristinashu Sorry for the delay! I have a moodboard here from last year (but I was more for the graphics/ illustration production assets that the contractor created): https://www.pinterest.com/nataliejworth/mozfest-2015-benchmarks/ Not sure if it helps? 2015's branding was definitely more iconographic.

**Comment by kristinashu** [comment]
Thanks @natalieworth! And thanks @sabrinang, I see you've been adding some pins. Good stuff!

**Comment by kristinashu** [comment]
@sabrinang here's were I'm at with the moodboards https://drive.google.com/open?id=0B2irLVDJivhLQkEtXzJodDhHSTA

I've been trying to group our pins thematically. I think if you can distill them down to about 5 different directions that would be great. Could add an intro slide to each direction to set the tone (bold, playful, hand done, artsy...).

**Comment by sabrinang** [comment]
The moodboards have been narrowed down to four and can be found here: https://goo.gl/6F895N and it will inform ticket https://github.com/MozillaFoundation/Mozfest2016_production/issues/44 and https://github.com/MozillaFoundation/Mozfest2016_production/issues/41
