### ISSUE TITLE
Moments to celebrate for comms

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/Mozfest2016_production#140]
This is a list of big moments of releases of the festival schedule or program to be used for press, social or mail outs. cc @KevZawacki @KGorr 
Please include Sign for updates tito emails in this mail out
- [ ] Release the full list of speakers
- [ ] Fringe events such as MozEx event at the Tate 10-11th oct
- [ ] Schedule for the festival
- [ ] Release the digital MozEx catalogue 
- [ ] Curiculum call workshop

**Comment by KevZawacki** [comment]
Important ticket! Thanks, @Saallen. Let's update whenever we have a date pinned down.

**Comment by Saallen** [comment]
First date confirmed @KevZawacki & @kristinashu 
Fringe event at [the tate](http://www.tate.org.uk/whats-on/tate-britain/pop/digital-artist-show-tell)
Date- 10- 11th of Oct talks after 1pm each day
Opportunity to see some of the exhibits ahead of the opening day at MozFest, meet some of the artists in residence at the tate and listen to array of talks.

**Comment by Saallen** [comment]
@marcwalsh suggested Meet the Space Wrangler piece - maybe we could do an AMA on twitter? or do a release of 10- 15 tweets sharing blogs, twitter accounts and linking to their spaces...good way to celebrate the narrative too. What do you think @KevZawacki @KGorr @edrushka

**Comment by KevZawacki** [comment]
@Saallen Twitter AMAs take a fair amount of resources to set up and execute -- I'm not sure the ROI would be there. I like the idea of a Medium post that shares headshots and bios.

**Comment by edrushka** [comment]
@KGorr the Fringe Event at the Tate could be a good sneak preview for the next email, since the speakers list won't be ready yet.

**Comment by KGorr** [comment]
Happy to help draft some tweets about the space wranglers and the spaces, @Saallen. Other than the mozfest site and medium, are there other resources I should be using? Do we have a list of their contact info/twitter handles gathered somewhere?

Regarding the Fringe Event at the Tate - sounds great to me! @edrushka, where can I find info on this? (Sorry if I've missed it somewhere...)

**Comment by KGorr** [comment]
Whoops - sorry, @edrushka! Scrolled up and saw the link is already provided for the event. I'll draft something soon and send it your way for review.

**Comment by Saallen** [comment]
@KGorr We have emails, and some twitter handles. We can get these added easily though
The fringe event page is a good tool for news also

**Comment by Saallen** [comment]
Got another cool thing to talk about on Twitter or emails
@acabunoc bby ran an open project training to encourage ppl to collaborate and build on their projects through the platform network pulse- and she recorded it . Great work Abby 📹 
https://www.youtube.com/watch?v=4lu_t7sJyms&feature=youtu.be

**Comment by edrushka** [comment]
People are starting to blog about their sessions. See: http://equalitytime.co.uk/5935/2016/10/04/mozfest/

**Comment by KGorr** [comment]
Thanks, @edrushka!
