### ISSUE TITLE
Create info pack for D&D speakers

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/Mozfest2016_production#145]
To include:
- [ ] flight details
- [x] hotel details
- [x] key festival timings
- [x] other D&D speakers and their themes
- [x] their speaking slot
- [ ] template for slide presentation ?? (if we're including this, we should have it ready!)

@KevZawacki @Saallen please add anything else you can think of

**Comment by KevZawacki** [comment]
Speaker playbook shaping up [here](https://docs.google.com/document/d/14VXDQcdKjOztX62HxYbnHXrPjwD-xR3ATY03KcsPVSo/edit#).

Planning to send week of Oct. 3. Or earlier, if possible!

cc @HPaulJohnson

**Comment by KevZawacki** [comment]
[Speaker Playbook](https://docs.google.com/document/d/14VXDQcdKjOztX62HxYbnHXrPjwD-xR3ATY03KcsPVSo/edit#) just about complete. Planning to ship Tuesday, Oct. 4 as a PDF, and alongside our release form.

@edrushka @StevieBenton Can you provide final QA before the end of the week?

@Saallen @HPaulJohnson Also welcome/encouraged to provide QA

**Comment by StevieBenton** [comment]
@KevZawacki Sure, more than happy to take a look. Do you prefer comments or direct edits?

**Comment by KevZawacki** [comment]
@StevieBenton Comments are best. Thanks!

**Comment by KevZawacki** [comment]
Send! Closing ticket 🎆
