### ISSUE TITLE
Supply board games 

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/Mozfest2016_production#146]
@marcwalsh @Saallen During a meeting about connecting participants at MozFest, a few people noted that some other tech fests provide board games, which helps some of the more introverted folks connect. Wondering if we could have 2 or 3 of these spread throughout the building - say in a couple coffee zones and on the 4th floor.

**Comment by Saallen** [comment]
Have you been to MozFest before!!!- we always have hungry hippos, connect 4, draughts and chess onsite. Normally on the lower levels. 
Hippos or chess didnt survive the London office move though. If you have other suggestions send them my way @edrushka

**Comment by edrushka** [comment]
THERE HAS BEEN HUNGRY HUNGRY HIPPOS ALL THIS TIME AND NO ONE TOLD ME!?

That's it. This is my last year on the production team. I will attend as a participant in 2017 so I can partake in this fun 😤 

@kristinashu were there other games at XOXO you could recommend?

**Comment by kristinashu** [comment]
Love that we're already doing this! 

XOXO had lots of indie games but none in particular come to mind.

**Comment by marcwalsh-zz** [comment]
[Argos](http://www.argos.co.uk/static/Browse/ID72/38597322/c_1/2%7Ccategory_root%7CToys%7C33006252/c_2/2%7C33006252%7C2+for+20+pounds+on+selected+games%7C38597322/r_001/4%7CCharacter%7CHungry+Hippo%7C1.htm) currently have a deal on all board games... - Any that strike your fancy?

@kristinashu @edrushka @Saallen

**Comment by kristinashu** [comment]
Jenga!

**Comment by edrushka** [comment]
Adam Lofting's board game!!!! https://www.thegamecrafter.com/games/moving-out-at-last-

**Comment by marcwalsh-zz** [comment]
Closing as we will be using the games we have at MozLondon.
