### ISSUE TITLE
Create Slack or Chat channel

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/Mozfest2016_production#147]
XOXO Festival has a dedicated Slack channel that is active throughout the year. See this article: http://www.theverge.com/2015/9/18/9349425/slack-future-of-conferences-xoxo-festival

What options do we have for MozFest? 

@xmatthewx please update this ticket after your software meeting

**Comment by edrushka** [comment]
Any updates @xmatthewx ?

**Comment by xmatthewx** [comment]
No clear answer unfortunately. Simon and the team needs to do an assessment on chat before we can decide whether MoFo will continue with it or choose another path. 

Independent of that, we could decide whether to use chat or not for Mozfest. Chris made it sound like a small and easy lift to set it up. Without that as a limitation, is it worth the effort to communicate about it with attendees? Does an uncertain future with chat deeply impact the value in the short term?

Let's discuss.

**Comment by kailan** [comment]
Hi – not sure if I'm supposed to comment in this repo, but I'd like to add my input!

I (along with some other attendees) think a Slack team for anyone at the festival would be a great idea before, during, and after the festival. Before the festival it can be used to get to know others before the event starts, during the festival it can be used for key communications ("Hey, still got some room for [session] in [room]!"), and after the festival we can use it to keep in touch with people we met and share photos/ideas.

It wouldn't cost anything as Slack has a virtually unlimited plan and it wouldn't take much time (an hour or two) to set up.

**Comment by edrushka** [comment]
hey @kblanks thanks for the comment. We already have a Slack channel and will do some work to get it into shape in the next couple weeks. Plans for improvement will be documented and discussed in #175.
