### ISSUE TITLE
Design: Name Card

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/Mozfest2016_production#148]
This ticket is for the design of the name card/name tag that hangs on the lanyard.
![22482329519_622a2381f0_m](https://cloud.githubusercontent.com/assets/4515662/18568996/ee27d7e6-7b54-11e6-8f5e-b639a091109b.jpg)
![22840128102_20df8584b1_m](https://cloud.githubusercontent.com/assets/4515662/18569005/f9e88a12-7b54-11e6-90a7-82bda78f80ef.jpg)
![22686916430_721fb649b5_m](https://cloud.githubusercontent.com/assets/4515662/18569009/fb3b87ca-7b54-11e6-9c94-3db37f81c53a.jpg)
### Front of card:

Must have:
- the words MozFest 2016
- area for writing name. Ideally this will allow enough room for Twitter/Github handles as well, for those that choose to share.

Should have:
- space for freedom/creativity/customization with stickers etc.
- known stickers:'I speak [language]' stickers and Science Space's 'brain' stickers
### Back of card:
- WiFi: [network name and password]
- Connect! #MozFest on [Twitter Icon] [IG Icon] [Flickr Icon] and [Network Pulse shortlink]
- Schedule: [schedule shortlink]
- Help: Tweet #MozHelp or visit the Info Desks on floors X, X and X.
- Lunch: From 12:30 - 14:00 on floors X, X and X.
- Coffee: Always hot on Floors X, X and X.
- Safety: Alert a volunteer, approach an Info Desk or email Sarah at festival@mozilla.org (all emails will be handled in the strictest confidence).
### Notes:
- There will only be one card. We will not have separate cards for different roles. 
- All lanyards will be the same colour except for those attendees who do not want their photos taken. They will wear different coloured lanyards to be easily identified.
- Cards should be designed with two attachment points at the top, so they don't flip
- Cards should be cardboard, not plastic, to minimize environmental footprint

**Comment by edrushka** [comment]
@marcwalsh @Saallen this encompasses everything we discussed today with the exception of wifi/connectivity. I hesitate to include this because network names and passwords often change at the very last minute. IMO, it would be worse to have incorrect information than no information at all. What do you think?

**Comment by SpikeUK** [comment]
@edrushka @marcwalsh @Saallen Could we maybe leave clear space for Wi-Fi details and maybe print these on stickers that could be stuck-on when the Volunteers are assembling them?
@Marcwalsh - will we have last minute label printing facilities on site?

**Comment by marcwalsh-zz** [comment]
@edrushka @SpikeUK @Saallen - Network name and password will be fine. We can pre-agree this with Ravensbourne well in advance to ensure that it doesn't change.

I'm checking if the password can be disabled on the network if not we can use something simple such as mozfest16 or oneweb16

**Comment by edrushka** [comment]
Ok, I'll add wifi info to the back of the card info. @kristinashu this is ready for you to present to Ed and Carrie-Ann.

**Comment by kristinashu** [comment]
Yes, I think that's all the info we need!

**Comment by Saallen** [comment]
Hey- just a note on
- Safety: Alert a volunteer, approach an Info Desk or email Sarah at festival@mozilla.org (all emails will be handled in the strictest confidence). 
  festival@ goes to 7 ppl would it be better to add my direct email
  or add a phone no-( which I will have asap)

**Comment by SpikeUK** [comment]
I think it should stay to the festival@ address rather than just you @Saallen . It give gives transparency within the team and has multiple eyes.
After all, the complaint may be about you ;-)

**Comment by marcwalsh-zz** [comment]
@Saallen I think an email and phone number is the way to go, some international visitors wouldn't use a telephone number and an email is quite identifiable. Could we not make a help@mozillafestival.org email that could be used for that which then could be forwarded to a smaller group?

**Comment by kristinashu** [comment]
@sabrinang and I have mocked up the name cards: https://redpen.io/p/vfb6a99be818e00757

We are restricted in size to A6 (same as last year). 

Design is similar to what was in the style guide but with some added space at the bottom of stickers ("I speak _____" and science's matching game).

Please let me know if you have any feedback about the design (pink vs blue/purple) or content.

**Comment by edrushka** [comment]
These look good! I think I prefer the blue/purple simply because of how the cog and wordmark pop so nicely. There's been some discussion about lanyard pricing and we may be limited in our colours (which may impact the colour you want for the card) @marcwalsh can you update on lanyard strings?

**Comment by kristinashu** [comment]
For lanyard strings, most colors could work (including black) with the exception of red or orange which would clash with all our palette.

**Comment by SpikeUK** [comment]
I think we are reserving the yellow lanyards to signify people do not wish to be filmed/photographed

**Comment by Saallen** [comment]
Hello confirming the festival hot line
+44 (0) 207 855 3030

**Comment by kristinashu** [comment]
I've added the phone number and updated the copy based on redpen feedback. Only missing piece is the wifi network and password (for @marcwalsh to confirm). We will decide on colour once we know the lanyard colour.

https://redpen.io/p/vfb6a99be818e00757

**Comment by edrushka** [comment]
@Saallen please review and sign off on the content on the back of the lanyard card: https://redpen.io/p/vfb6a99be818e00757

**Comment by Saallen** [comment]
Hello
I just left some comments- I would like the safety piece changed, especially in regards to too many locations for vital and super important information to get lost- This will never work if there are too many options for failure.
**Safety**
approach 5th floor info desk, email festival@mozilla.org or call XXXXXXX
All reports will be held in the strictest confidence

_In regard to listing_
Help and safety are confusing above each other

Can we move help (onsite) to connects position and put connect above safety?
We don't want ppl going on IG looking for help with supplies.

**Comment by SpikeUK** [comment]
I agree with Sarah - I would prefer to not involve the local volunteers in the reporting chain for reports of breaches of CofC. Having said that, anyone with a radio should be fair game.

**Comment by kristinashu** [comment]
Redpen has been updated with that feedback https://redpen.io/p/vfb6a99be818e00757

Waiting to hear back about wifi, slack, and lanyard color.

**Comment by marcwalsh-zz** [comment]
WiFi information:

Network Name: `RaveEvents` 
Password: `mozfest16`

**Comment by marcwalsh-zz** [comment]
@kristinashu (sorry should have tagged you!)

**Comment by kristinashu** [comment]
I've updated the comps https://redpen.io/p/vfb6a99be818e00757

Just need to know what the lanyard colour options are and then we can choose blue/purple or pink. But people seem like people prefer the blue/purple.

**Comment by marcwalsh-zz** [comment]
@kristinashu 

We can get pantone matched lanyards... if required and they're not too much more money. 
Let me know the colour that works best with the design you want and I'll order them.

**Comment by kristinashu** [comment]
Great! I spoke with @sabrinang and we think the lanyard should be blue (Pantone 072).
<img width="333" alt="screen shot 2016-10-12 at 12 30 10 pm" src="https://cloud.githubusercontent.com/assets/1068783/19324714/b84e0ffe-9077-11e6-8f55-232326fb152c.png">

Then we'll go with the pink name card.

**Comment by kristinashu** [comment]
Here's the final mockup https://redpen.io/gnd31171caaee6d86d 

@edrushka can you please sign off on the content.

@marcwalsh how do you want the file (.ia, pdf, how much bleed...)?

**Comment by edrushka** [comment]
@kristinashu did you determine if we use "floor 4" or "level 4" in the other assets?

**Comment by kristinashu** [comment]
@edrushka I can't find anywhere else we reference Floor or Level but Level seems more commonly used in tickets and it was used on last years map. I updated Ground Floor to Ground Level on that last update.

**Comment by edrushka** [comment]
R+ on content. This looks very good. Nicely done!  :dancing_men:

**Comment by kristinashu** [comment]
@edrushka shoot! Just noticed the schedule app uses Floor.

**Comment by edrushka** [comment]
Haha...my brain kept telling me there was _somewhere_ we were being inconsistent. Not a huge deal. If you can update the card go ahead. If you prefer to keep as-is, that's fine. I think it's more important we're consistent across the graphic assets.

**Comment by kristinashu** [comment]
I've stuck with 'Level' and will use it consistently for print materials.

<img width="542" alt="screen shot 2016-10-13 at 1 54 41 pm" src="https://cloud.githubusercontent.com/assets/1068783/19366658/e6133b8c-914c-11e6-9045-56ee3872b287.png">
<img width="540" alt="screen shot 2016-10-13 at 1 54 53 pm" src="https://cloud.githubusercontent.com/assets/1068783/19366659/e6147b28-914c-11e6-90e1-e650ad08086e.png">

@marcwalsh here are the print files for the name card: https://drive.google.com/open?id=0B2irLVDJivhLZ29Fb3dNcVE3alU

Print color should be as close to Pantone Pastels Neones 807 as possible.
<img width="207" alt="screen shot 2016-10-13 at 1 51 38 pm" src="https://cloud.githubusercontent.com/assets/1068783/19366503/325fd5fa-914c-11e6-91c0-0b1ec0062e13.png">

**Comment by marcwalsh-zz** [comment]
Hey @kristinashu,

I'll need an outline of where the hole punch will go, are you able to add this please (as a separate layer).

**Comment by kristinashu** [comment]
@marcwalsh I've updated the files to have the two holes https://drive.google.com/open?id=0B2irLVDJivhLZ29Fb3dNcVE3alU

The holes are the same size and distance from the top as last year, except there are two of them. Will the lanyard clip be the same as last year? If so then this should work but let me know if they're going to be a different type.

<img width="316" alt="nametag-01" src="https://cloud.githubusercontent.com/assets/1068783/19404717/441fd4e6-9225-11e6-9b80-aab598e6bd51.png">
<img width="316" alt="nametag-02" src="https://cloud.githubusercontent.com/assets/1068783/19404718/4420ca0e-9225-11e6-9606-73abfb3c893f.png">

**Comment by marcwalsh-zz** [comment]
Sent to printers!

**Comment by kristinashu** [comment]
People found the extra info on the back useful. A lot of people tweeted their name card. But volunteers complained about the extra time it took to attached two clips instead of one per lanyard.

![artboard jpg](https://cloud.githubusercontent.com/assets/1068783/20195994/9095c712-a74d-11e6-8ee0-02565c29b7e2.png)
