### ISSUE TITLE
Language stickers

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Mozfest2016_production#149]
@SpikeUK mentioned this in #80

We need stickers that say "I speak xxxxx language". These should be non-glossy so people can write on them. 

translated text: https://github.com/MozillaFoundation/Mozfest2016_production/issues/124

**Comment by SpikeUK** [comment]
This is an idea that has been kicking around for local volunteers for several years now but has never been realised: volunteers that have declared (when they signed-up) that they can converse in language (other than EN) display sticker on their name badges.
The obvious idea was to have county flags but that fails as some languages are used in multiple countries.
On the volunteer sign-up form we have the following options

> FR | French | Français
> ES | Spanish | Español
> IT | Italian | Italiano
> DE | German | Deutsch
> HI | Hindi | हिन्दी 
> AR | Arabic | العربية

Could we print something like

> FR | French
> FR | Français

On a square label AND have blanks for options other than the current six.

I cannot read Gujarati so would need "GU" rather than ગુજરાતી

**Comment by kristinashu** [comment]
Linking this to the lanyard/name tag ticket https://github.com/MozillaFoundation/Mozfest2016_production/issues/148

**Comment by kristinashu** [comment]
Here are the language stickers on the lanyards: https://redpen.io/p/vfb6a99be818e00757

Currently the stickers are 1.5in but I need to make sure that size is doable. 

<img width="533" alt="screen shot 2016-09-30 at 1 53 06 pm" src="https://cloud.githubusercontent.com/assets/1068783/19006613/6b3460b2-8715-11e6-9ada-c2b1b9c9abbe.png">

<img width="413" alt="screen shot 2016-09-30 at 1 55 06 pm" src="https://cloud.githubusercontent.com/assets/1068783/19006638/89aa95a2-8715-11e6-8c90-b40e102559ef.png">

cc @sabrinang @marcwalsh

**Comment by kristinashu** [comment]
@marcwalsh are we able to get these stickers around 1.5 inches in size? With a matte finish so people can write on them?

@SpikeUK how many stickers do you think we need?

**Comment by marcwalsh-zz** [comment]
I'm getting a quote for these today, I'll be getting them printed on sheets and not die-cut. 

I have a rough estimate on numbers, it will be a few hundred in total and spare blanks just in case.

**Comment by kristinashu** [comment]
Thanks @marcwalsh. I've updated each sticker to be 40mm. We probably need a decent amount of blank ones for the many languages we haven't accounted for. Here are the print files:

[Language Stickers.zip](https://github.com/MozillaFoundation/Mozfest2016_production/files/517271/Language.Stickers.zip)

Also in Drive folder: https://drive.google.com/open?id=0B2irLVDJivhLUW9FTWxNTGJGWnc

**Comment by SpikeUK** [comment]
@kristinashu I do not have access to all attendee records but taking the local volunteer data and scaling it up for a hypothetical 1.800 attendees ...
- French    | 5%   | 45
- Spanish  | 5%   | 45
- Italian     | 5%   | 45
- German  | 5%   | 45
- Hindi      | 10% | 90
- Arabic    | 2%   | 36
- other     | 20% | 360

So 45 sheets of the above (one of each named language + three blanks) would be about right in my estimation.

**Comment by kristinashu** [comment]
@marcwalsh how are these being printed? Any chance we could add a bunch of matching game stickers (https://github.com/MozillaFoundation/plan/issues/839) to this? They would be the same size as these language stickers but we would need a lot of them (one for every attendee). 

cc @flukeout @acabunoc

**Comment by marcwalsh-zz** [comment]
Sent to printers!

**Comment by sabrinang** [comment]
## Post MozFest Documentation

The language stickers were available in 6 languages and a blank customizable version at the customize your name tag station near the registration table. Markers were available to write your own language and attendees placed these on their name tags.
![mozfest-documentation-language-stickers](https://cloud.githubusercontent.com/assets/2492510/20158777/636bc7d0-a691-11e6-8478-fe469dd3630b.png)

**Comment by SpikeUK** [comment]
I noticed several people had hand-written stickers with the word "English". I know that this is default for most of us here and it would be an interesting discussion for 2017 if we should pre-print some with this value. #justsayin

**Comment by sabrinang** [comment]
For localized assets, we should have a documented sign-off process with the localizer. Our Arabic stickers are incorrect and we discovered this after an attendee let us know on the first day but with a clear process we can prevent that next year.
