### ISSUE TITLE
Hold a design retrospective 

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/Mozfest2016_production#15]
Chat with @natalieworth @lovegushwa to determine what worked (and what didn't) in last year's MozFest design process (design all the way to delivery).

Assigning @hannahkane to coordinate when a designer has been identified.

cc @xmatthewx

**Comment by lovegushwa** [comment]
@edrushka would love to discuss. I'm out on PTO until July 13th

**Comment by kristinashu** [comment]
I'm also on PTO July 15th but it looks like everyone is available Thursday July 14th from 2-3pm PT so I'll send out an invite for then.

cc @sabrinang

**Comment by kristinashu** [comment]
Here are our meeting notes: http://etherpad.io/p/mozfest_design_retro

We will consolidate these notes into a gdoc to share with Erica and Sarah.

**Comment by kristinashu** [comment]
I've added a short summary of the meeting at the bottom of [design brief doc](https://docs.google.com/a/mozilla.com/document/d/1f-ybB8x6HJ2F4JyDnN8wUdyMcO9b7VpQCLGINGgTKuA/edit?usp=sharing)
