### ISSUE TITLE
Design notepad - Deadline Oct 11

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Mozfest2016_production#150]
Based on https://github.com/MozillaFoundation/Mozfest2016_production/issues/34

Notepad will be clipped to the Festival Guide and should compliment the design.

Supplier Info:
- [PixArt Printing](https://www.pixartprinting.co.uk/digital-litho-printing/office-products/customised-notebook/) - These have a full color print on the outside and then 90gsm ivory paper on the inside and are 60 pages and sewn bound.

**Comment by marcwalsh-zz** [comment]
Attached is the template for the notepads. @kristinashu @xmatthewx 

[QFS_D_A6.zip](https://github.com/MozillaFoundation/Mozfest2016_production/files/514394/QFS_D_A6.zip)

**Comment by kristinashu** [comment]
Thanks @marcwalsh! Looks like we can have bleed so that's great. For pricing, the dimensions are A6 and we would recommend not too many pages, something around 48 pages.

@carrie-ann is working on the design in the Festival Guide ticket #135 and the work can be seen here https://redpen.io/p/aq3ed683d65024fc8f

**Comment by kristinashu** [comment]
@xmatthewx @edrushka can you please give final sign off on this notebook?

This is what the back (left side) and front (right side) look like:
<img width="1004" alt="screen shot 2016-10-10 at 2 32 40 pm" src="https://cloud.githubusercontent.com/assets/1068783/19251890/8244c862-8ef6-11e6-9a0f-4329b2afda05.png">

And how it will look all together (but with one clip, not two):
![red-pen-13bc0bce-b330-42ac-c340-38676703f08c](https://cloud.githubusercontent.com/assets/1068783/19251885/7e730816-8ef6-11e6-97dc-380eac1d64e0.jpg)

Redpen link https://redpen.io/p/aq3ed683d65024fc8f

@marcwalsh here are the print ready files in the notebook template. They includes the .ai file and a pdf

[Final Notebook .zip](https://github.com/MozillaFoundation/Mozfest2016_production/files/520468/Final.Notebook.zip)

Files are also in Drive: https://drive.google.com/open?id=0BzVQTTEXQZdXVXJlWHpLYTFfS0U

**Comment by xmatthewx** [comment]
✔️ 😺

**Comment by marcwalsh-zz** [comment]
@kristinashu @xmatthewx - I need to know the colour of the thread we want to use. 

These are the options:
<img width="674" alt="screen shot 2016-10-11 at 12 56 04" src="https://cloud.githubusercontent.com/assets/14007066/19269372/238a3c50-8fb2-11e6-96ec-c44f2968ba0a.png">

**Comment by kristinashu** [comment]
Yellow would be cool. @carrie-ann does that sound good to you?

**Comment by Carrie-ann** [comment]
@kristinashu @marcwalsh I agree, the yellow thread will stand out really nicely against the blue spine!

**Comment by marcwalsh-zz** [comment]
Sent to printers! 👯‍♂️

**Comment by kristinashu** [comment]
Yay!
