### ISSUE TITLE
Guide: Write Ravensbourne piece

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/Mozfest2016_production#152]
For 2016 Festival Guide. Write Ravensbourne piece

@Saallen what do we need to convey here? Do you have any copy already written?

**Comment by Saallen** [comment]
Ravensbourne College is a wired media and design campus located in East London and the home of MozFest for the last 6 years.
It spans nine floors that are custom-built to combine maker labs with impromptu classrooms, in an open dymanic fashion that suits Mozillas open ethos. It’s a learning institution networked with creative industries and designed to give students real-world experience.
With a student body curious about hacking digital media, a beautiful building and plenty of industry
and academic collaborators, they play a many roles throughout the festival from facilitators, to production team through to events support - Ravensbourne is the perfect partner for Mozfest. Thanks for hosting us!
@RavensbourneUK  @raveinnovate

www.ravensbourne.ac.uk

Make changes as you see fit @edrushka

**Comment by edrushka** [comment]
Ravensbourne College is a wired media and design campus located in East London and has been the home of MozFest for the past six years.

Spanning nine custom-designed floors, the venue combines maker labs with impromptu classrooms in an open and dynamic fashion -- a perfect match for Mozilla's open ethos. 

Ravensbourne's students are passionate about hacking digital media, and backed by dedicated industry and academic collaborators, they participate in and add value to the festival in innovative ways, year after year. 

Staff and technologists at the college take on invaluable roles during MozFest, including facilitation and production support. 

Thank you for this incredible partnership!

@RavensbourneUK
www.ravensbourne.ac.uk

---

@Saallen here's my draft. Thoughts?

**Comment by edrushka** [comment]
@Saallen re-ping for your signoff

**Comment by Saallen** [comment]
beautiful- can we just add this twitter handle too  @raveinnovate

**Comment by edrushka** [comment]
@carrie-ann this content is final for the Ravensbourne piece

---

Ravensbourne College is a wired media and design campus located in East London and has been the home of MozFest for the past six years.

Spanning nine custom-designed floors, the venue combines maker labs with impromptu classrooms in an open and dynamic fashion -- a perfect match for Mozilla's open ethos.

Ravensbourne's students are passionate about hacking digital media, and backed by dedicated industry and academic collaborators, they participate in and add value to the festival in innovative ways, year after year.

Staff and technologists at the college take on invaluable roles during MozFest, including facilitation and production support.

Thank you for this incredible partnership!

@RavensbourneUK
@raveinnovate
www.ravensbourne.ac.uk

**Comment by edrushka** [comment]
Closing. Pull text from final festival guide InDesign file. Content in this ticket has not been through final proof-reading.
