### ISSUE TITLE
Guide: Write MozRetreat piece

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/Mozfest2016_production#153]
For 2016 Festival Guide. Write MozRetreat piece
- should detail relationship between retreat and festival

**Comment by Saallen** [comment]
Sharing notes @erikad
MozRetreat Berlin, was a 3 day event bringing together the key designers for the festival in 2016. A combination of staff, community members, partners and festival allies invited to attend with the aim of working together to design and build the program structure. All attendees will play an active role in the design and execution of the festival 
Held 5 months before the festival it was an opportunity for the program team to come together to create a relationship between the group and share an experience that will have impact on the outcome of the event.
Last year we came together to think collectively about how to evolve the festival from the previous 5 years. This year we want to define that evolution and design the program collectively. Using the collective energy, design ethos and open knowledge of this group we will build purpose statements, individual space call for proposals and map the pathways for 2016
The goal of the retreat is to give the attendees time and space to think creatively about MozFest, whether that is through emersing ourselves in a local community or making dinner together  This is the first and last time the group will come together before the  festival-  so it should be used as a time to get to know each other, share narratives, build connections and alliances between spaces

**Comment by edrushka** [comment]
MozFest: A festival co-designed with community

In May, 40+ community members, partner organizations, festival allies and Mozilla staff attended a three-day planning session to co-design and build the MozFest 2016 program.

Our goal was to think collectively about how to evolve the festival from the previous 6 years. The energy, design ethos and open knowledge of this group defined our approach to Spaces and Pathways, ensuring that all MozFest attendees have a way to engage with the festival. We also set challenges for ourselves in areas of inclusion, resulting in a multi-lingual call for proposals, and the support of six languages in addition to English in this year's programming. Additionally, we imagined new ways to encourage thoughtful dialogue and debate on the most pressing topics currently facing the web and its users, and are proud to offer our first ever Speaker Series at MozFest 2016.

---

What do you think @Saallen Do we need to say more?

**Comment by Saallen** [comment]
🍬

**Comment by edrushka** [comment]
@carrie-ann this piece is ready for the Festival Guide.
