### ISSUE TITLE
Source clips for Festival Pack

### ISSUE THREAD

**Issue by marcwalsh-zz** [MozillaFoundation/Mozfest2016_production#154]
Just as a reminder as it maybe something that proves more tricky to find.

We need around 1800 binder / bulldog / foldback clips to hold the festival pack together. 

Would be good to know colors / style etc. 

@kristinashu @sabrinang - Any suggestions?

**Comment by kristinashu** [comment]
We can see once we know what the cover looks like in https://github.com/MozillaFoundation/Mozfest2016_production/issues/69 but anything close to our color palette will work well

<img width="692" alt="screen shot 2016-09-20 at 1 10 10 pm" src="https://cloud.githubusercontent.com/assets/1068783/18687152/afce0866-7f33-11e6-9f03-573d43dae278.png">

**Comment by kristinashu** [comment]
Black would also be fine to use.

**Comment by marcwalsh-zz** [comment]
ORDERED! 

Arriving tomorrow to MozLondon
