### ISSUE TITLE
Tracking issue for key areas in Ravensbourne

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/Mozfest2016_production#155]
This issue will be eventually populated with all the major areas within the venue

Please use these maps for room numbers https://drive.google.com/drive/folders/0B_B9-Ny1xBaRX1BUQVpER3dIaWM
 Key areas for wayfinding
- [x]  Spaces
- [x]  Exhibit
- [x] Lunch areas
- [x] Coffee
- [x] Supplies room
- [x]  Creche
- [x] Prayer room

cc @kristinashu @sabrinang @marcwalsh @edrushka

**Comment by Saallen** [comment]
**Locations for Moz Exhibit**

Walker space
3rd floor Open Media studio
7th floor room 707

**Comment by Saallen** [comment]
**Creche**

Level 2 room 208

**Comment by Saallen** [comment]
**Coffee**
 Walker space
level 5
Level 9

**Comment by Saallen** [comment]
**Lunch**
slight change per day- 
no need to highlight Friday as pre event day - as an fyi only

Friday 
Level 4

Saturday
Foyer 
Level 4 
Level 6
Level 8

Sunday 
Foyer
Level 4
Level 6

**Comment by Saallen** [comment]
**Supplies room**

level 1 room 107

**Comment by Saallen** [comment]
Prayer room

Level 3

**Comment by kristinashu** [comment]
Thanks! This is super helpful. I've updated the map on redpen https://redpen.io/p/nca82e6ea157535639

Assuming Supplies room should be room 107 (not 297).

**Comment by Saallen** [comment]
emmm, where did 297 come from......where did I type that.... @kristinashu

**Comment by kristinashu** [comment]
Oops, 297 is a typo on my part! But it says 207 above in one of your comments @Saallen.

**Comment by kristinashu** [comment]
@edrushka you mentioned some space locations to me, are they finalized? Or close to being finalized?

**Comment by Saallen** [comment]
Level 1 & Mezz
Space- Digital Arts and Culture

Level 2 
Youth Zone

Level 3
Open Media Art Exhibt

Level 4
Library Space- Fuel the movement

Level 5
Coffee station

Level 6
Space -Delimma of connected spaces
Space- Localisation

Level 7
Space- Demystify the Web
Art exhibit

Level 8
Space- Journalism
Space- badges

Level 9 
Space- Science

**Comment by edrushka** [comment]
@marcwalsh can you fill in the rest of these?
- Lunch areas
- Coffee
- D&D stage -- Walker Space, Ground Floor
- Main speaker stage -- Open Space, 4th Floor
- Prayer room
-  Supplies room 
- Creche -- not sure if we want this on the map
- #mozhelp, info booth

**Comment by kristinashu** [comment]
If we know exactly locations, if would be great if you can add them here https://redpen.io/tp8c68c697ba47ced8

**Comment by Saallen** [comment]
Level 0 Foyer 
Registration
Lunch station
Cafe

Level 0 Walker space
Dialogue and Debate stage
Art exhibition
TODO Installation
Coffee station

Level 1 & Mezz
Space- Digital Arts and Culture
105-108 Production back of house

Level 2 
Youth Zone
208 Creche

Level 3
Open Media Art Exhibit

Level 4
LIbrary- Space- Fuel the movement
OPen space- Main stage
Food station

Level 5
Coffee station
Info desk
TODO Installation
Comms desks

Level 6
Space -Delimma of connected spaces
Space- Localisation
Lunch station

Level 7
Space- Demystify the Web
Prototyping lab
Art exhibit

Level 8
Space- Journalism
Space- badges

Level 9 
Space- Science
Prototyping lab
Coffee station

**Comment by kristinashu** [comment]
Thanks! I've updated the overview map https://redpen.io/tp8c68c697ba47ced8
I just guessed the exact locations so please let me what needs to be moved around.

**Comment by kristinashu** [comment]
Final maps are here: https://redpen.io/p/nca82e6ea157535639
