### ISSUE TITLE
Plan Pulse kiosk

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/Mozfest2016_production#156]
We'd like https://mzl.la/pulse to have a physical place in the festival, a kiosk where attendees can browse activity and find asset/people they might connect with to collaborate. 

To do:
- [ ] figure out location with @Saallen @edrushka 
- [x] figure out hardware 
  - iMac or Mac mini and large monitor
  - standing desk
  - mount for large sign/banner
- [x] design & print 
  - large sign/banner
  - small CTA/instructions
  - screens 
  - [maybe] animated stream that could be projected or displayed 
- [ ] plan
  - [x] email [science fair participants](https://docs.google.com/spreadsheets/d/1TJ8mMm0K7FYpstGWLLZJLdv8lkbrZbJ4upDf-iloz3I/edit#gid=140327018) to add item to MozFest Pulse form: http://mzl.la/mozfest-pulse 
  - [ ] how to engage facilitators to post assets
  - [x] coordinate mentor/mentee activity with @acabunoc 
  - [ ] connect again with comms team to leverage as fodder 
    cc @kristinashu

**Comment by abbycabs** [comment]
I talked to @Saallen & @edrushka today about a table at the science fair!

**Comment by edrushka** [comment]
If you're at the Science Fair do you still want the kiosk for the rest of the festival?

**Comment by xmatthewx** [comment]
I think yes. Science fair is crazy busy. I could see people browsing this during some down time between sessions. 

It's actually a way for the science fair to continue throughout the weekend.

**Comment by xmatthewx** [comment]
As we talked about, it be great to identify a place where Pulse and the Network Map can remain available for participants to browse throughout the weekend. Could be in a corner near the main stage. By a coffee stand or info booth. iMacs would be great, screens might work.

**Comment by xmatthewx** [comment]
Here are draft signs we could use for them. 

@sabrinang – I'm not sure if I did your cut corners properly around the word network. Files are on [drive](https://drive.google.com/drive/u/1/folders/0B_rbDAen9prkNzRYejBjZ3RKMGs). cc @kristinashu 

![mozfest-pulse-signs](https://cloud.githubusercontent.com/assets/53411/19174840/dcb17588-8bff-11e6-807a-7c526ee8f56e.jpg)

**Comment by xmatthewx** [comment]
@sabrinang – please include these as you prepare other posters for print. I don't have a strong opinion about size, so feel free to modify the [files in drive](https://drive.google.com/drive/u/1/folders/0B_rbDAen9prkNzRYejBjZ3RKMGs). My ragged type on small pulse sign is also pretty poor.

Ideally we can mount these on boards since we might not have a wall to use. cc @marcwalsh

**Comment by marcwalsh-zz** [comment]
Large Signs are around £30 each and the A4 signs are £16 each. 

Would these be from MozFest's printing budget or somewhere else?

**Comment by xmatthewx** [comment]
As discussed, we can print from Design/Production budget if it's not tricky to group with other print order. Both projects are in services of Mozfest, so @edrushka suggested it's okay to do from Mozfest budget.

**Comment by xmatthewx** [comment]
@marcwalsh offered to look into to some ways we can lock computer down as a kiosk. 

related ticket in pulse repo: https://github.com/mozilla/network-pulse/issues/203

**Comment by marcwalsh-zz** [comment]
@xmatthewx - Are these files ready for print?

**Comment by xmatthewx** [comment]
I'd like either @sabrinang or @kristinashu to review and confirm they're ready.

**Comment by xmatthewx** [comment]
Closing this. Filed separate issues. Tracking meta of all the issues here: https://github.com/mozilla/network-pulse/issues/225
