### ISSUE TITLE
Teach Stevie how to use Github

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/Mozfest2016_production#157]
We are learning Github 👍 

@StevieBenton welcome to Github!

**Comment by StevieBenton** [comment]
Hi! Github learning is progressing successfully!

**Comment by edrushka** [comment]
@Saallen Say hi to Stevie!

**Comment by Saallen** [comment]
Hi @StevieBenton welcome to Github
Once you get in the swing of things its super easy to use
**Pro tip**

Turn off your watch notifications so you only get an email from Github when someone mentions you
![screen shot 2016-09-22 at 11 24 29](https://cloud.githubusercontent.com/assets/10194015/18744770/37451d3c-80b7-11e6-823a-28280233d9ef.png)

**Comment by StevieBenton** [comment]
Hello @Saallen and thanks for the tip! All looks pretty straightforward and I'm looking forward to getting stuck in

**Comment by edrushka** [comment]
Closing. Stevie is now a GH pro! 😉
