### ISSUE TITLE
Write Mark's bio for website

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/Mozfest2016_production#159]
Need Mark's bio for Team page. @KevZawacki do you have this somewhere, or can you draft? Please stick to shorter wordcount. Thank you!

**Comment by edrushka** [comment]
We'll need a photo, too.

**Comment by KevZawacki** [comment]
**Mark's bio**:

Mark is Executive Director of the Mozilla Foundation, a global community that does everything from making Firefox to taking stands on issues like privacy and net neutrality. Mark’s main job is to build the movement side of Mozilla, rallying the citizens of the web, building alliances with like-minded organizations and leaders, and growing the open internet movement. 

**Mark's photo**:
![mark-surman_by_joi-ito-990x557](https://cloud.githubusercontent.com/assets/11045250/18835017/1ef084c0-83c7-11e6-8caf-7a8e9e6ace30.jpg)

**Comment by edrushka** [comment]
Thank you Kevin!! :bow: 🐕
