### ISSUE TITLE
Scope website updates

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/Mozfest2016_production#16]
Scope how the updated design should be reflected on the website. This should be a minimal visual refresh.

cc @Saallen

**Comment by edrushka** [comment]
Update: meeting with Mark S (hopefully) in the next week or two to determine if any changes need to be made prior to the festival other than the light visual update we discussed.

**Comment by hannahkane** [comment]
Do we have a scope for this yet? Would be good to know now for planning upcoming heartbeats.

**Comment by edrushka** [comment]
#onit. Hope to have the broad strokes by end of this heartbeat.

**Comment by edrushka** [comment]
Here is a [high level overview of the proposed changes](https://docs.google.com/document/d/1HQkzvdWCcTxnFOWlL-6gPrM4xtIivZwo0b7DINnM9ZU/edit#). 

This needs some discussion, as we've increased the scope slightly by adding the video live-streaming and/or archiving element(s). @hannahkane and @KevZawacki we should chat with @simonwex about the technical requirements and restrictions here. That will help us with resourcing.

**Comment by edrushka** [comment]
@marcwalsh @Saallen please review.

cc @xmatthewx for design awareness

**Comment by xmatthewx** [comment]
cc @alanmoo for dev perspective

**Comment by alanmoo** [comment]
Next up doesn't look too bad from a dev time perspective, maybe a day. Friends and Allies page is probably the bigger lift, though we'll see once it's designed.

**Comment by edrushka** [comment]
Hannah, Kevin, Wex and I met to discuss and prioritize. We're going to eliminate a separate page for Friends and Allies. 

@hannahkane shall we close this scoping ticket and create separate tickets for the rest of the tasks? They are all fairly simple (most complicated is incorporating videos on landing pages as discussed in the meeting).

**Comment by hannahkane** [comment]
@edrushka - yes, please.
