### ISSUE TITLE
Create music playlist for Walker Space

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/Mozfest2016_production#160]
Put together a playlist for Walker Space (when D&D stage not in use).

**Comment by edrushka** [comment]
There will be no music on the 4th floor this year ❌ 🎻 ❌

**Comment by Saallen** [comment]
can we ask @OpenMatt  for a playlist ?- he has been keeping people dancing all summer and should have some good mixes! 💃

**Comment by edrushka** [comment]
I realized that TODO might use sound in some of their installations, in which case we should not have music playing in the Walker Space. Closing this issue for now. Will re-open if music is needed.

This issue was really only filed to solve the violin problem ;)

**Comment by Saallen** [comment]
Ok cool- note that TODO installations will not have issue with noise bleeds in or out.

**Comment by OpenMatt** [comment]
But wait -- I have the perfect music already picked out for this!!!! 
https://www.youtube.com/watch?v=dQw4w9WgXcQ
