### ISSUE TITLE
MozFest brown bag

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/Mozfest2016_production#161]
Brown bag for MozFest
To share programming information about the 2016 festival wit Staff but buiod excitement and manage expectations

Speakers
*Sarah
- Erika
- Marc
- Kevin
- someone from the design team
- Ruth from Ravensbourne

Topics to share
- Spaces narrative + moz ex
- new elements to the program such as languages, assessibility and d&d
- Designs...ooohhh
- Ravensbourne sponsorship

**Comment by ldecoursy** [comment]
Will there be time for space wranglers to do a quick go-round? Maybe with a specific prompt (one session or activity they're most excited about, or where they need help/participation)

Also could be good to add a "how MoFo's show up" agenda item, to cover self-care, also pulling from an email we sent last year (feel free to update/remix):
- Listen to learn and learn to lead.
- Step UP, step IN, and step BACK. That is, be attentive to the moment and recognize when leading well requires you to step up and help, or when you need to step back and let others lead. 
- Visit other spaces to see your colleagues in action. Use real-time participation and honest conversation to inform how we work better together in the future. 
- Note who stands out for their participation, for their leadership, for how they’re working with others. Celebrate them. 
- Connect with people you don’t often have the opportunity to. Connect with them in a way that is meaningful and authentic to you.

**Comment by Saallen** [comment]
Yes, we can do a self care and how to show piece here too.
I will ask but as not all spaces are led by mofos, it might be trickly to have all spaces represented but I will put it to them.

**Comment by marcwalsh-zz** [comment]
We smashed it! 💪
