### ISSUE TITLE
Enter Science Fair projects into Pulse

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/Mozfest2016_production#164]
The science fair is awesome. It's also hectic and difficult to absorb all the various projects. Let's add them to Pulse pre-Mozfest so people can browse them through the weekend. 

Many science fair projects are great assets for network members beyond Mozfest. Lets capture them in Pulse!

@edrushka 

Who wrangles the science fair?
When will curation happen?
Where does the list of projects live?
What details on each project are captured?

Note: If the you haven't started gathering submissions, we could leverage Pulse to gather and assess.

**Comment by edrushka** [comment]
@Saallen wrangles the Science Fair!  🔬 💻 🍺 

cc @StevieBenton to watch for story/project capturing plans

**Comment by Saallen** [comment]
adding the list of [science fair tables](https://docs.google.com/spreadsheets/d/1TJ8mMm0K7FYpstGWLLZJLdv8lkbrZbJ4upDf-iloz3I/edit#gid=0) and allocations here- ping if you require access as this contains email addresses-
Note its more about cool organisations and individuals and their projects taking part in the festival , than the sessions you can go to

**Comment by StevieBenton** [comment]
Thank you for adding me in here. Of the themes there I think, while all interesting, the youth, science and journalism areas could be really fruitful for me. I'll check in from time to time, but if anything (in any theme, but especially those) looks particularly unusual or innovative, please ping me

**Comment by xmatthewx** [comment]
@Saallen – I've drafted an email ([pad](https://public.etherpad-mozilla.org/p/science-fair-pulse)) we could send to wranglers. To gather info from them for me to review and post (it doesn't go directly to Pulse). 

I think this is the best approach to documenting the science fair for festival comms. We can also leverage this to point photographers to specific projects. 

If you think it's good, let's figure out the best timing. Better sooner as incentive to plan science fair? Or later after decisions are nearly final?

**Comment by xmatthewx** [comment]
@edrushka – suggests that we gather info directly from participants after the list from wranglers is done. Sounds good to me. 

https://public.etherpad-mozilla.org/p/science-fair-pulse

**Comment by xmatthewx** [comment]
closing. tracking here: https://github.com/mozilla/network-pulse/issues/226
