### ISSUE TITLE
Design Speaker Series poster - Print at Ravesbourne

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/Mozfest2016_production#167]
Design a poster to highlight each of the 4 (possibly 5) talks in our speaker series.

Each talk has 2-3 speakers. Details [here](https://docs.google.com/document/d/14VXDQcdKjOztX62HxYbnHXrPjwD-xR3ATY03KcsPVSo/edit) and pics are [here](https://drive.google.com/drive/folders/0B-BKZVAww2KHRzlGOWNfc19rZGc).

Poster should have:
- Time of talk
- Speakers' names 
- Speakers' photos
- Title of each speaker's talk
- Location (Walker Space on the ground floor)

@KevZawacki how hackable should we make these? What are the chances we'll be swapping speakers' times? If this is likely, we can design for it.

**Comment by KevZawacki** [comment]
@edrushka It's possible programming could change at any time -- more hackable = better.

**Comment by edrushka** [comment]
@kristinashu given that programming times/speaker combinations may change, do you think it's better to make posters for each individual speaker, rather than each talk?

**Comment by kristinashu** [comment]
It might be messy having a separate poster for each speaker so I would prefer to have one poster for each talk. Since we don't need very many copies, maybe we can design this now but print it on site at Ravensbourne?

Do you have higher res images for the speakers?

**Comment by KevZawacki** [comment]
Hi @kristinashu, that works for me. @edrushka is that doable?

Re: higher-res headshots, I've placed several [here](https://drive.google.com/drive/folders/0B-BKZVAww2KHRzlGOWNfc19rZGc?usp=sharing). If some are too low quality, let me know. We may be able to track down better ones on Flickr, etc.

Still unsure if Mark is speaking, so you can leave him off the posters.

**Comment by edrushka** [comment]
@marcwalsh can we get the Speaker Series printed on site at Ravensbourne? There are 4-5 talks and we'll probably want 2 or 3 posters for each talk to put around the building = 15 posters in total.

**Comment by edrushka** [comment]
For reference, our official release on the D&Ds. This info is now public: https://medium.com/mozilla-festival/everything-you-need-to-know-about-mozfests-speaker-series-af8eb8f186bf#.y2pscukes

**Comment by kristinashu** [comment]
@taisdesouzalessa will help out designing these! 

@sabrinang's work in #87 for the D&D slides is a good reference for this poster design https://docs.google.com/a/mozilla.com/presentation/d/1ztrY9GBVc10nSUFFXxE1d0UZZDRNRhCAZ9-cUfz60a0/edit?usp=sharing

We should just have one template design with different content for each speaker series.

**Comment by taisdesouzalessa** [comment]
@kristinashu @sabrinang @xmatthewx @edrushka @KevZawacki  here is the first poster. Please let me know through here your feedback (RedPen is not working - as soon as it works, I will post the link here):
![poster-speaker-series1](https://cloud.githubusercontent.com/assets/22157921/19608407/f9c2976a-9785-11e6-888e-eb3161d63b2c.jpg)

Once I receive all the feedback on this one, I'll do the changes and use it as a template for the other 4.

Note: @sabrinang I played with the icons on the top (the pin and calendar) but it got too busy and confusing. Decided to remove them in order to have more clarity in the layout, let me know what you think :).

**Comment by KevZawacki** [comment]
Ah, @taisdesouzalessa, this is **beautiful**! No changes from my end. 😸

**Comment by xmatthewx** [comment]
This is great. 

I like your use of box pattern for twitter handles. 

Tiny bits: For headings at the top of poster, alignment along bottom of the text seems off a little. It might be pixel rendering, but the white text looks a bit low. Is the vertical yellow line on a grid line? It looks near the center, but not quite on center.

**Comment by kristinashu** [comment]
Looks great! I love the yellow corner and photo border. I just think the speaker's content could be tighten up a little (ie nudge the Topic text up closer to the speaker's job title - it feels a little floaty right now).

**Comment by taisdesouzalessa** [comment]
@xmatthewx you are right, the white text was a bit low, thanks for spotting that. The vertical yellow line was in the middle of a gutter so both texts (title and date, location) could be aligned to the grid. 

I did another version with the yellow line right in the center of the poster and I think it looks better (I was wondering if it would look unbalanced since the title is so big compared to date/location but I think it looks good center aligned). What do you think?

Here is the updated version:
https://redpen.io/p/om396ce7b3b9594de5

**Comment by taisdesouzalessa** [comment]
One thing I forgot to mention: this poster will be A2 
![a2](https://cloud.githubusercontent.com/assets/22157921/19612333/d4e645d0-979a-11e6-98e3-3f810822e82c.jpg)

**Comment by taisdesouzalessa** [comment]
@kristinashu yeah I was wondering that as well...it does feel floaty. Comparing both placements, i prefer the tighter one (it groups the info better):
https://cl.ly/3Y3d1y1i3935

Will go with the tighter version then.

https://redpen.io/p/om396ce7b3b9594de5

**Comment by taisdesouzalessa** [comment]
I was wondering...should we add "am/pm" to the time in the poster or you think it is clear as is?

**Comment by kristinashu** [comment]
Yes, I think it's a good call to add am/pm.

**Comment by taisdesouzalessa** [comment]
@kristinashu here is the latest version, with revisions: https://redpen.io/p/om396ce7b3b9594de5

**Comment by kristinashu** [comment]
Looks great! :tropical_drink:

**Comment by taisdesouzalessa** [comment]
Hey @kristinashu @KevZawacki @edrushka @xmatthewx @sabrinang here are all the 5 posters:
https://redpen.io/p/om396ce7b3b9594de5

I have some questions about the copy:
1. Will Mark Surman and Sahar Aziz have the same topic ("On Mozilla’s key issues")? Here is a screenshot of the medium post:
   <img width="1087" alt="screen shot 2016-10-24 at 2 59 31 pm" src="https://cloud.githubusercontent.com/assets/22157921/19665529/373a01d4-99fa-11e6-90e8-8c7b319202d5.png">
2. Will Katherine Maher talk about "the open internet movement" or "online harassment"? - the [Medium post](https://medium.com/mozilla-festival/everything-you-need-to-know-about-mozfests-speaker-series-af8eb8f186bf#.rrvy6aqyc) mentions the second option and the [doc](https://docs.google.com/document/d/14VXDQcdKjOztX62HxYbnHXrPjwD-xR3ATY03KcsPVSo/edit) I have mentions the first one.
3. Will Simone Browne talk about "Privacy, Security, and Digital Inclusion" as Medium post says or only "Digital Inclusion" as the doc says?
4. Do we have a Twitter handle for Volker Birk? He is the only person without it.

Thanks!

**Comment by kristinashu** [comment]
Looks great @taisdesouzalessa!

Kevin can clarify but I think the Medium post is generally more up-to-date and you should follow that.

No Twitter handle for Volker Birk and I think Simone Browne doesn't want hers shared either.

**Comment by KevZawacki** [comment]
Hi @taisdesouzalessa, to answer your questions:

1) Both Mark and Sahar have yet to pick a specific topic, hence the broad "Mozilla's key issues." OK to put that on the poster.

2) Katherine Maher will talk about online harassment

3) Simone Browne will talk about privacy, security, and digital inclusion

4) Kristina is correct -- we should leave off Twitter handles for Volker and Simone

Thanks!

**Comment by taisdesouzalessa** [comment]
Thanks for your answers, @kristinashu and @KevZawacki. Here are the updated versions (posters 1,3 and 5 were updated - noticed Brian Behlendorf's description on Medium was shorter so I am used the Medium post as source of truth): https://redpen.io/p/om396ce7b3b9594de5

I'll export the PDFs and send you shortly. Kristina, I can trim the posters in London once we print them out.

Thanks!

**Comment by taisdesouzalessa** [comment]
@kristinashu - here are the final PDFs:
[poster-speaker-series-all.pdf](https://github.com/MozillaFoundation/Mozfest2016_production/files/551376/poster-speaker-series-all.pdf)

**Comment by marcwalsh-zz** [comment]
Printed!

**Comment by sabrinang** [comment]
## Post MozFest Documentation

The speaker series posters were found throughout the venue as a collective to showcase all 5 sessions.
![mozfest-documentation-speaker-series](https://cloud.githubusercontent.com/assets/2492510/20194723/77b08c1e-a748-11e6-875f-34489386c7d7.png)
