### ISSUE TITLE
Z verses the S- the battle of our time!!!!!!

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/Mozfest2016_production#168]
Hey- we are at that stage of comms and copy editing where we need to align on the American versus English spelling of words.
Especially in localisation/localization
What are other folks thoughts here @StevieBenton @hjbailey  @edrushka @kristinashu @KGorr @KevZawacki ??

**Comment by hjbailey** [comment]
I am happy either way - seen as we are holding this in England perhaps we should Localise :)

**Comment by KevZawacki** [comment]
Agreed. British English is probably best. I can adjust my **behaviour** accordingly.

**Comment by Saallen** [comment]
![2012-12-14-07 35 25](https://cloud.githubusercontent.com/assets/10194015/18951894/548ce32e-863f-11e6-8e39-ab8a3b26c3fe.jpg)

**Comment by StevieBenton** [comment]
As long as we are consistent in our approach, people shouldn't be left feeling off color either way.

**Comment by KGorr** [comment]
I've been doing my best to keep tweets/emails with British spelling - I'll double check the tweets before I schedule them to make sure my Yankee ways are shining through :)

**Comment by kristinashu** [comment]
Designers have been using British spelling. Sticking with S will also avoid the Zed vs Zee debate!

**Comment by edrushka** [comment]
![british](https://cloud.githubusercontent.com/assets/4515662/18963843/644237ba-862b-11e6-95b7-3af7c613c4e0.gif)

**Comment by edrushka** [comment]
:dove: Closing, as this has been settled peacefully :dove:
