### ISSUE TITLE
Draft for review - overall festival narrative

### ISSUE THREAD

**Issue by StevieBenton** [MozillaFoundation/Mozfest2016_production#169]
Hello @edrushka @Saallen @KevZawacki @KGorr 

I've put together a draft article which offers an overview of the festival. My plan is to support this with other content later on, specifically articles about the five key themes. 

It's not ready for publication yet but I'd really appreciate some input. [The document is here](https://docs.google.com/document/d/1Ce6RHFoKTiM2enNSru6PW1PWZyHLP-GjlUs8GBbygB8/edit?usp=sharing). Please take a look at the first comment for some context!

Thanks all,

Stevie

**Comment by StevieBenton** [comment]
Just another quick thought - is GitHub the preferred way of sharing drafts like this or would you all prefer email?

**Comment by KevZawacki** [comment]
Thank you, @StevieBenton. Taking a look now. And GitHub works for me!

**Comment by edrushka** [comment]
Nice job - this is solid, and we can continue to refine as you come up with more awesome phrases and ideas.

**Comment by Saallen** [comment]
This is really great- thank you!

**Comment by StevieBenton** [comment]
Thanks guys!

**Comment by StevieBenton** [comment]
Hey @edrushka @Saallen @KevZawacki 

Not sure who to ask for final sign-off on this but the [final version is here](https://docs.google.com/document/d/1Ce6RHFoKTiM2enNSru6PW1PWZyHLP-GjlUs8GBbygB8/edit). If it is approved I can upload to Medium. Perhaps think about adding to the MozFest website if an opportunity arises.

Thanks!

**Comment by KevZawacki** [comment]
This looks great, @StevieBenton. @edrushka? 

Two small tweaks:

-- Let's change the headline to "What is MozFest?"
-- Can you select an image from our [Flickr](https://www.flickr.com/photos/134771568@N06/albums/with/72157658567152683)?

Then, ready for Medium! Let me know once it's live: I'll pin it to the homepage, so all visitors see this piece first.

**Comment by StevieBenton** [comment]
Thanks! I've tweaked the headline and will choose an image later. I'll upload this at some point tomorrow once the MozFest slide for board has been signed off.

**Comment by StevieBenton** [comment]
Just a quick update, this has been [published live on Medium now](https://medium.com/mozilla-festival/what-is-mozfest-953b0ac52c2e#.zafqpfafo). Do feel free to share!

Edit: and thanks to all for your input, very much appreciated.
