### ISSUE TITLE
Write content-creators playbook

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/Mozfest2016_production#171]
We have a number of people who will be blogging at MozFest:
- contributors coming via the Participation team
- bloggers who wrote posts last year 
- [add more if you know of any]

Let's provide some context so their blogs will be useful content for us to share throughout the year, not just during the festival weekend.

This could be a remix of the Speakers Series playbook, with some brief notes about our plans to highlight MozFest during other key comms moments throughout the next year. We should also identify a place where they can share their blogs with us. Etherpad? Google spreadsheet?

cc @HPaulJohnson @KevZawacki @StevieBenton

**Comment by KevZawacki** [comment]
For benchmarks, we can point them toward: https://medium.com/mozilla-festival/tagged/mozfest2015

**Comment by StevieBenton** [comment]
I think the Speakers Series playbook is a really good basis for this as it's a very good document. I am happy to take a first go at drafting something if people would like.

**Comment by HPaulJohnson** [comment]
would be great if you wanted to take a first pass at this @StevieBenton - thx!

**Comment by StevieBenton** [comment]
Will do so this week. Anything we definitely want to include, apart from the obvious details? 

I'll set up a Google doc and once I've made a decent start will share with you all.

**Comment by HPaulJohnson** [comment]
I've been meaning to find some time for us to chat @StevieBenton so this sounds like a good opportunity to touch base. I'll find some time for us to discuss.

**Comment by StevieBenton** [comment]
Thanks @HPaulJohnson - I have accepted your invitation. Look forward to catching up.

**Comment by StevieBenton** [comment]
Hello again everyone. I've had a go at [a rudimentary first draft](https://docs.google.com/document/d/1jsUxCzEv2rnqHPkjOs6ina9KEu9y5RHxUkAiMFNzANk/edit?usp=sharing). It's fairly lightweight but doesn't feel like anything specific is missing. 

I will need some help with the procedural bits and pieces - how do folks share their content with us? - but it feels like it's a good start. Any and all comments / edits welcome, as always!

**Comment by edrushka** [comment]
Great start. Left my comments in the doc. Would be great to clarify roles/point-person for content creators. Is that you @HPaulJohnson ???

**Comment by StevieBenton** [comment]
I've had another pass over the document. @edrushka thank you very much for your comments, really useful.

I've tightened some of the copy and also removed a couple of the things which would have created a burden for everyone, like sourcing images.

It now feels a touch on the light side, but I think this could be a good thing. [The link again, for those who missed it](https://docs.google.com/document/d/1jsUxCzEv2rnqHPkjOs6ina9KEu9y5RHxUkAiMFNzANk/edit).

**Comment by edrushka** [comment]
Thanks Stevie! @HPaulJohnson this needs your eyes and also can you clarify your role in the doc? Not sure about a couple things.

**Comment by StevieBenton** [comment]
Hi @HPaulJohnson sorry to ping you again. Just wondered if you could take a look at this please. [Doc is here](https://docs.google.com/document/d/1jsUxCzEv2rnqHPkjOs6ina9KEu9y5RHxUkAiMFNzANk/edit?usp=sharing).

Thanks!

**Comment by HPaulJohnson** [comment]
thanks for the ping, @StevieBenton. I'll work on finalizing this today. I'll find some time in our calendars to discuss and figure out a plan for distributing it to various content creators this week.

**Comment by StevieBenton** [comment]
That's excellent @HPaulJohnson thank you very much. I'm free from about 2.30pm Tuesday, until 4.15 Wednesday, after 5pm on Thursday and all day Friday.

**Comment by HPaulJohnson** [comment]
Left a few comments in the doc but overall looks awesome. Sorry for the delay. Let's discuss when we meet in a few days and then we can distribute it to all the people who might being producing content at Mozfest.

**Comment by StevieBenton** [comment]
That's great, thank you. I agree with both of your comments so will add them to the document. I'll make a couple of notes beneath the actual content about distribution ideas so we have something to discuss when we meet on Thursday.

**Comment by StevieBenton** [comment]
I've added some notes on distribution now. Copying here for ease of reference.

Publish on Medium (with some appropriate images), then tag as MozFest 2016, share on official Mozilla Twitter channels (I can do the Medium part but don't have access to the social channels so one for, perhaps, @KevZawacki )
Send as an email to MozFest attendees (less desirable as might be a bit spammy for those not interested)
Create a PDF (perhaps with some nice design elements if there is capacity) and place on the MozFest website, and share the link on social and in any planned emails that are going out before the festival (if we go down this route we would need to liaise with @KGorr )

Create a leaflet or poster version to display in the physical spaces at the festival (less desirable because requires design time and printing)

Add to the festival app (probably too late for this)

**Comment by HPaulJohnson** [comment]
Email sent to all volunteer content creators today that includes this playbook and the process by which we will be collecting everything during the Festival. 

@StevieBenton and I to meet next week to come up with a content calendar to help as a roadmap for this. 

Closing.
