### ISSUE TITLE
Guide REVISION: Dialogues and Debates Speakers Series

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/Mozfest2016_production#172]
We've just added a 5th Speaker Series to accommodate additional speakers.

@KevZawacki can you please put the most up to date speaker info here for @carrie-ann to revise in the Festival Guide. 

cc @kristinashu

**Comment by kristinashu** [comment]
@carrie-ann would it work if you put this extra info on the last page https://redpen.io/vu283b856509ab69a4 and then move "Multicultural MozFest" spread to be before the "Dialogue and Debate" pages?

**Comment by SpikeUK** [comment]
Do you have timing for extra D&D session please @edrushka ? Can you update #70 please?
Thank you (I am using #70 for master for my volunteer rostering timetable).

**Comment by KevZawacki** [comment]
Hi @edrushka @carrie-ann,

The latest speaker info can be found **[here](https://docs.google.com/document/d/14VXDQcdKjOztX62HxYbnHXrPjwD-xR3ATY03KcsPVSo/edit)**, pages 5-8. It includes people, times, and short bios. 

In the speaker series portion of the festival guide, we should put a footer that reads "Programming subject to change." Between now and Oct. 29, a speaker may fall ill, cancel, etc.

**Comment by KevZawacki** [comment]
@edrushka @carrie-ann

And [here](https://drive.google.com/drive/folders/0B-BKZVAww2KHRzlGOWNfc19rZGc) are the latest headshots.

**Comment by kristinashu** [comment]
@edrushka @KevZawacki for consistency across all design material, are we calling this "Dialogues and Debates" or "Debates and Dialogues"? Both are plural, right?

**Comment by edrushka** [comment]
confirmed. Both are plural.

**Comment by kristinashu** [comment]
But which order? "Dialogues" first or "Debates"?

**Comment by edrushka** [comment]
Dialogues and Debates.

**Comment by kristinashu** [comment]
Thanks, this has been updated!
