### ISSUE TITLE
Guide REVISION: Sunday Key Timings

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/Mozfest2016_production#174]
09:30 - 10:45 MozFest Breakfast
11:00 - 12:00 Session 8 
12:15 - 13:15 Session 9 [line break] Dialogues and Debates
12:30 - 14:00 Lunch
13:00 - 13:45 Session 10
14:00 - 15:00 Session 11 [line break] Dialogues and Debates 
15:15 - 16:15 Session 12
16:30 - 17:30 Sessions 13
18:00 - Closing Demo Party

**Comment by edrushka** [comment]
cc @carrie-ann @kristinashu

**Comment by kristinashu** [comment]
Thanks, this has been updated!
