### ISSUE TITLE
Improve Slack channel

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/Mozfest2016_production#175]
Let's spruce up our existing [MozFest Slack channel](https://mozfest.slack.com/messages/general/).
- [ ] Decide if we want to upgrade our account. It’s not that expensive: https://mozfest.slack.com/pricing
- [ ] Set up a sign-up form e.g. https://github.com/BretFisher/slack-signup
- [ ] Prep some new channels e.g.
- 1 for each of the 10 spaces
- Science Fair
- Demo Party
- Help
- Penpals/meet-and-greet/introduce yourself
- Espanol/Francais/Italiano etc. for the 6 languages
- Social/beers/cocktails
- Fun in London
- Remoties
  Note that these need champions. No sense creating a lot of empty channels.
- [ ] Identify some owners/moderators/admins for tech issues and people issues
- [ ] Put sign-up link on back-of-lanyard ‘How to Connect’ section
- [ ] Put sign-up link in email going on out Oct 18
- [ ] Put sign-up link on website 

Thoughts @Saallen @autonome @xmatthewx ?

**Comment by edrushka** [comment]
Note that we need to find a secure way to set up the auto-invite form. Many of the solutions I found online seem to leave users' email addresses vulnerable.

**Comment by kailan** [comment]
Hi @edrushka, popping in again about this topic since I feel like a Slack expert! (still not sure if I'm meant to be here)
- The Slack paid plans are billed per-user and that's going to get pretty expensive once the public are able to join.
- For sign-ups I've usually always seen [rauchg/slackin](https://github.com/rauchg/slackin) used – I'm not aware of any security issues.

**Comment by edrushka** [comment]
Awesome @kblanks - that's super helpful (And yes, you are welcome to be here! 😄)

**Comment by Saallen** [comment]
Hey- I am of the option this is surplus to communcatio  requirements!!???? 😱 
We are already asking ppl to share on twitter, upload to network pulse, add comments to etherpads on the schedule....this feels like somewhere else I need to check without knowing what is the benefit....

**Comment by edrushka** [comment]
This is a nice-to-have element that allows festival-goers to connect with each other before, during and after the festival. See how the [XOXO Festival has used Slack successfully](http://www.theverge.com/2015/9/18/9349425/slack-future-of-conferences-xoxo-festival).

There is no expectation that you would need to monitor the channel throughout the weekend. We'd need admins/moderators to route any help requests through the existing help desk system. This is principally an attendee connection tool, not a help tool, though.

Happy to chat more as this is still in discussion.

**Comment by edrushka** [comment]
Note after discussion we're moving towards a "less is more" approach with the channels:
- main channel for general festival chatter
- penpals/meet-and-greet/introduce yourself

**Comment by simonwex** [comment]
I'm worried about promoting this slack team to mozfest participants, though I definitely see the value. We'd have some of the same issues if we were to promote Chat as the answer. 

This is something we need to solve for the Mozilla network overall, and it's not clear what the answer will be.

Here are the issues specifically with Slack as I see them:

### Free tier limitations

On the free tier, we're limited to 10,000 messages. There's also an undocumented user limit that we're unlikely to hit anytime soon with Mozfest of 8,462

If half the participants show up on slack, we'll be able to store ten messages for each of them until this message starts showing for everyone:

![image](https://cloud.githubusercontent.com/assets/25260/19173961/34a8b690-8be0-11e6-89d1-3e875f9cb091.png)

_@edrushka  how do we feel about this?_

### Paid-tier pricing

If we needed to upgrade to a paid version, it is $8/user/month. If we're keeping alumni and creating a space for ongoing collaboration and communication throughout the year, this would quickly be a serious cost. **~$100K** / year for 1,000 users. 😨 

### Security Review

I'm not sure if slack has been through security review. @autonome, do you know if one has been done? 

### Invite model

It's a royal PITA to manage invites. The slack signup form @edrushka linked to is interesting, but the demos don't seem to work and will require dev time to get it up and running.

> If email signup is enabled for your team, new members will be able to create an account on their own. Team Owners can manage this option under Team Signup Mode on the Team Settings page.
> 
> For security, only those with access to an email address at the domains specified by the team's Owner will be able to create an account. We'll send a validation link to each new team member's email address to verify their identity before they can create an account.

**Comment by simonwex** [comment]
If we can get through/accept the issues outlined above, we could run this as a test. If that's the case, does anyone have time to put some thought into the evaluation strategy? Ideally we'd want some basic stats on engagement and usage over the year. Also, it could be an opportunity to add some meat to our network strength KPI.

**Comment by edrushka** [comment]
Thank you for looking more deeply into the pricing structure, @simonwex. We certainly don't want users receiving the upgrade message and we absolutely do not have the budget to support 1000 paid accounts.

Any platform the Festival Team supports needs to have longevity. We do not want to begin building a community filled with alumni and creating a space for ongoing collaboration and communication only to have to shut it down because we can't afford to support it.

After reviewing your comments, Simon, I recommend the Festival Team does not implement a sign-up form this year. As tempting as it is, we clearly need to evaluate our long term strategy for supporting this community. This is not something we can do before MozFest 2016, although it is certainly something we should look at for MozFest 2017 and beyond. Thanks for your guidance here.

**Comment by simonwex** [comment]
This isn't going to be an easy problem to solve. It is something we should dig in to in December.

**Comment by msaunby** [comment]
Enterprise slack does exist, I've seen it in use https://gdstechnology.blog.gov.uk/join-the-conversation/ but no idea how it's priced.

**Comment by edrushka** [comment]
Interesting, @msaunby - I see you still need an account within a specific domain (they list 110+ on the signup form!!)

We'll have to look into this. Thanks for the example.

**Comment by edrushka** [comment]
Closing this. Thank you for the discussion everyone.
