### ISSUE TITLE
Guide: Spirit of MozFest (working title)

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/Mozfest2016_production#176]
MozFest is different from other tech events. It is: 
- a checkpoint in an ongoing flow of creation and imagination that never ends
- utterly focused on interactive sessions and experiences - this is the heart of the what makes the festival special
- driven by the audience. More than 400 attendees host sessions
- created with partners in the community
- a place to write creative code alongside people from around the world
- a chance for Mozilla  to listen to the open web community. 

cc @StevieBenton do you want to take a crack at this for the festival guide? We need a short paragraph or two describing the _spirit_ of MozFest. See [other guide content](https://github.com/MozillaFoundation/Mozfest2016_production/issues?q=is%3Aissue+is%3Aopen+label%3A%22Festival+Guide%22) for reference.

**Comment by edrushka** [comment]
@kristinashu this is the new piece of content for the guide. Not ready for Carrie-Ann yet. Still in-progress.

cc @Saallen

**Comment by StevieBenton** [comment]
@edrushka Absolutely. Will have a go and link back to the G-doc here once there's something to see.

**Comment by StevieBenton** [comment]
Hello again, @edrushka @kristinashu @Saallen 

[Here's a link for the first attempt](https://docs.google.com/document/d/1mTBJXTH76XXYo4dTOEybb-fQOnqSE0XqYx8ciWBiE84/edit?usp=sharing). It's fully open so you can comment and edit if you'd like. Is this the kind of thing you were looking for? I'm trying to keep a consistent tone of voice in the content I'm producing without it becoming too repetitive.

**Comment by edrushka** [comment]
Awesome - all of that copy is useful to have. Can you try a shorter version for the Festival Guide specifically. 1-2 short paragraphs that puts more of an emphasis on sessions, and how anyone (young people, 'experts') can lead a session and anyone can connect and share ideas there. It's this audience collaboration through sessions that are the heart, and the defining characteristic, of MozFest.

**Comment by edrushka** [comment]
Check out Dorine's blog for a bit of inspiration: https://medium.com/mozilla-festival/a-call-for-more-youth-led-sessions-at-mozfest-ae44f84ee8a#.xbgccwgbh

**Comment by StevieBenton** [comment]
@edrushka I've had another go with a shift in emphasis. It's in the same document. I've kept the original copy though, as some of it can be remixed for other purposes I think.

**Comment by edrushka** [comment]
@Saallen what do you think of this?

---

The Spirit of MozFest

At its heart, MozFest is a listening exercise and a checkpoint in the circular process of co-creation that the free and open internet depends upon.  Participants bring ideas, energy, enthusiasm and skills to more than 400 peer to peer interactive sessions.

What makes MozFest so special is there is literally no entry requirement. Anyone, of any age, background or level of expertise, can lead and attend sessions. Have an idea, suggestion or passion? We give you the platform. The people at MozFest - you - give the movement its power. Where will you take us next?

**Comment by Saallen** [comment]
Hey
I keep tripping up on checkpoint in the circular process of co-creation- 
I love the language, and totally want to see it used as in version 1 circular and co creation work really well but the 4 c's is distracting and I keep having to re-read

**Comment by Saallen** [comment]
This is sooo good  ❤️ 
What makes MozFest so special is there is literally no entry requirement. Anyone, of any age, background or level of expertise, can lead and attend sessions. Have an idea, suggestion or passion? We give you the platform. The people at MozFest - you - give the movement its power. Where will you take us next?

**Comment by edrushka** [comment]
@carrie-ann @kristinashu please use this for now, we'll tweak slightly to incorporate Sarah's feedback but it won't be drastically different:

---

The Spirit of MozFest

At its heart, MozFest is a listening exercise and a checkpoint in the circular process of co-creation that the free and open internet depends upon. Participants bring ideas, energy, enthusiasm and skills to more than 400 peer to peer interactive sessions.

What makes MozFest so special is there is literally no entry requirement. Anyone, of any age, background or level of expertise, can lead and attend sessions. Have an idea, suggestion or passion? We give you the platform. The people at MozFest - you - give the movement its power. Where will you take us next?

_[testimonials if able to use]_

Mozilla is about building the open platform, building opportunity and empowerment for all of us. And it is the activities that happen here and come out of MozFest that really prove how much hope there is for success.
— Mitchell Baker 

There is something for everyone to do and learn at Mozfest. Mozfest allows you to pick up something completely new and dive in fully.
—Hera Hussain

**Comment by StevieBenton** [comment]
How funny - I know Hera! She does amazing work and wears many hats. Her
charity, Chayn, is perhaps the most impressive, but her work with Open
Corporates is incredible, too. Such a small world...

**Comment by StevieBenton** [comment]
Quick thought @edrushka @Saallen 

If all the Cs are a stumbling block, perhaps change circular for ongoing?

**Comment by edrushka** [comment]
works for me. 

@Saallen please review and sign off on this slight tweak. Also is the title OK?

---

The Spirit of MozFest

At its heart, MozFest is a listening exercise and a checkpoint in the ongoing process of co-creation that the free and open internet depends upon. Participants bring ideas, energy, enthusiasm and skills to more than 400 peer to peer interactive sessions.

What makes MozFest so special is there is literally no entry requirement. Anyone, of any age, background or level of expertise, can lead and attend sessions. Have an idea, suggestion or passion? We give you the platform. The people at MozFest - you - give the movement its power. Where will you take us next?

[testimonials if able to use]

Mozilla is about building the open platform, building opportunity and empowerment for all of us. And it is the activities that happen here and come out of MozFest that really prove how much hope there is for success.
— Mitchell Baker

There is something for everyone to do and learn at Mozfest. Mozfest allows you to pick up something completely new and dive in fully.
—Hera Hussain

**Comment by SpikeUK** [comment]
We know Hera as well @StevieBenton :) She was a MozFest local volunteer in 2013 (concentrating on dealing with out visitors from the media).  Hera was then the volunteer coordinator for the London Wikimania conference in 2014 - we had several chats on the 'phone and exchanges of email exchanging ideas and 'tricks of the trade'.

**Comment by edrushka** [comment]
@StevieBenton one clarification - we don't specify what 'the movement' is in the 2nd para -- or anywhere else in the guide. Possible to rephrase that sentence? Is it too much to say "The people at MozFest - you - give the web/open web its power."?

**Comment by StevieBenton** [comment]
@edrushka I am happy with that change. In my view, better to say "open web" than "web", but yes, please go ahead!

**Comment by edrushka** [comment]
Final copy:

---

The Spirit of MozFest

At its heart, MozFest is a listening exercise and a checkpoint in the ongoing process of co-creation that the free and open internet depends upon. Participants bring ideas, energy, enthusiasm and skills to more than 400 peer to peer interactive sessions.

What makes MozFest so special is there is literally no entry requirement. Anyone, of any age, background or level of expertise, can lead and attend sessions. Have an idea, suggestion or passion? We give you the platform. The people at MozFest - you - give the open web its power. Where will you take us next?

Mozilla is about building the open platform, building opportunity and empowerment for all of us. And it is the activities that happen here and come out of MozFest that really prove how much hope there is for success.
— Mitchell Baker

There is something for everyone to do and learn at Mozfest. Mozfest allows you to pick up something completely new and dive in fully.
—Hera Hussain

**Comment by kristinashu** [comment]
Added!
