### ISSUE TITLE
Print Space banners

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Mozfest2016_production#178]
Based on designs in https://github.com/MozillaFoundation/Mozfest2016_production/issues/102

@marcwalsh have you priced these?

![red-pen-3546abf5-2e50-4a0b-f316-b2487b5b0600](https://cloud.githubusercontent.com/assets/1068783/19161829/3ebe22d6-8baa-11e6-95f4-eff72fc2c489.jpg)

We're hoping for:

10 x "One Web" banner (one for each floor, excluding Level 0)
![red-pen-6328aff3-1f50-4106-d179-2c8dd41b3568](https://cloud.githubusercontent.com/assets/1068783/19161849/4e439d62-8baa-11e6-8eeb-98118b054f24.jpg)

1 x each of the 10 spaces 
![red-pen-7910c944-1c3e-461e-cce4-efc924849fba](https://cloud.githubusercontent.com/assets/1068783/19161848/4e435ca8-8baa-11e6-9167-92652639425b.jpg)

1 x each of the 10 levels (excluding Level 0)
![red-pen-693780b3-e1e8-4c18-e435-3dabe33ecfd6](https://cloud.githubusercontent.com/assets/1068783/19161850/4e4569f8-8baa-11e6-9a0b-3a9e46a5033b.jpg)

If possible, we would also like to print one additional of each space banner (same design as above - icon + space name) either on the banner material or paper (if banner material is too expensive).

**Comment by kristinashu** [comment]
Not sure how finalized the Space locations are but as is, it looks like not every Level has a Space. Based on rough plans https://redpen.io/p/ewf78d105e4368c2af we can reduce the numbers to:

7 x "One Web" banner (one for Level 1, 2, 4, 6, 7, 8, 9)

1 x each of the 10 spaces

1 x each of the relevant levels (one for Level 1, 2, 4, 6, 7, 8, 9)

cc @xmatthewx @sabrinang @edrushka

**Comment by xmatthewx** [comment]
If budget permits, I'd suggest one or two extra "One Web" banners for next to the registration desk. Nice. Not critical.

**Comment by marcwalsh-zz** [comment]
These are good to print in terms of prices. I've attached the templates for the artwork.

[Level Banner Template.pdf](https://github.com/MozillaFoundation/Mozfest2016_production/files/519250/Level.Banner.Template.pdf)
[Space Banner Template.pdf](https://github.com/MozillaFoundation/Mozfest2016_production/files/519251/Space.Banner.Template.pdf)
[One Web Banner Template.pdf](https://github.com/MozillaFoundation/Mozfest2016_production/files/519252/One.Web.Banner.Template.pdf)

^^ @ed-yau

**Comment by ed-yau** [comment]
Hi All, please find the final artwork pdf files for the Banners in the folder titled **EXPORT FINALS** in the shared google drive link.[https://drive.google.com/drive/folders/0B8D3YQVeWHo7VFo4TkNFUzZvTjg]

**Comment by ed-yau** [comment]
@marcwalsh Here are the final banner files for print.
[EXPORT FINALS-20161011T112019Z.zip](https://github.com/MozillaFoundation/Mozfest2016_production/files/521671/EXPORT.FINALS-20161011T112019Z.zip)

**Comment by kristinashu** [comment]
Thanks Ed!

**Comment by marcwalsh-zz** [comment]
Printing! ✌🏼
