### ISSUE TITLE
Guide: REVISION Shorter Space Wrangler Bios

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/Mozfest2016_production#179]
As required for the design, here are shorter bios
#### Grainne Hamilton

Grainne’s varied background includes leading the development of the Jisc Open Badges Toolkit, contributing to the Mozilla Discover project, acting as a Senior Consultant at Blackboard, and founding and facilitating the Open Badges in Scottish Education Group. At DigitalMe, Grainne contributes her expertise to a range of projects and further develops the Open Badges ecosystem in Scotland.
#### Stacy Martin

Stacy is Senior Manager of Privacy and Engagement as Mozilla where she focuses on building privacy community and education/awareness materials like teaching kits on privacy, passwords, and DRM.  Stacy is a co-founder of Privacy Lab, which she and Noah Swartz started in San Francisco and are now expanding to Europe. Her passion is online safety and privacy for vulnerable populations. She has worked with domestic violence organizations, city councils and other nonprofits.
#### Raegan MacDonald

As Senior EU Policy Manager, Raegan leads Mozilla’s public policy work in the EU, specialising in copyright reform, net neutrality, privacy, and data protection. Originally from Canada, Raegan is a policy wonk with experience in campaigning and advocacy. She’s been working on EU legislation for over 5 years, both as manager of Access Now’s Brussels Office and with the European Digital Rights (EDRi) network. 
#### Irini Papadimitriou

Irini is Digital Programmes Manager at the V&A and is responsible for the annual Digital Design Weekend, and the monthly Digital Futures. Irini is also Head of New Media Arts Development at Watermans, an arts organisation presenting innovative work and supporting artists working with technology. She is also one of the organisers for London's Mini Maker Faire, and one of the co-founders of Maker Assembly.
#### Matt Rogers

Matt is passionate about working with young people, particularly when it comes to experimenting with existing and emerging technologies. Matt was a KS1-KS4 teacher for eight years most recently at a Primary School in South East London, where he also held the roles of CAS Lead Educator and Mathletics Lead Educator. This experience directly feeds into Matt’s work on Safe, Naace CPD badges and Scout badges at DigitalMe.
#### Tim Riches

Tim has worked in education for the past 12 years, first with arts groups, helping to develop web based participation projects, and then co-founding award winning open learning platforms including Radiowaves & NUMU. His focus is working with partners to develop a new skills currency using Mozilla Open Badges. Tim also works with Open Badges developing international partnerships and projects.
#### Lucy Lewis

Lucy is Projects Director at DigitalMe. She has developed and managed award winning digital learning programmes, reaching over 10,000 learners, with partners like The Imperial War Museum, The Children’s Society and The London 2012 Olympics. Since 2011, Lucy has worked with employers, learning providers and charities to implement Open Badge programmes and develop tools such as the Badge Design canvas and The Open Badge Academy platform.

**Comment by edrushka** [comment]
cc @carrie-ann @kristinashu

**Comment by Carrie-ann** [comment]
@edrushka Thanks for this Erika! Could I be a pain and also ask for Joey's Bio to be shortened as well?

**Comment by edrushka** [comment]
@Carrie-ann no problem here it is:

#### Joey Lee

Joey is a geographer and computational media artist who is passionate about technological literacy and the engagement of art and science through computation and collaboration. He is co-author of "The Big Atlas of LA Pools" and co-creator of the "Aerial Bold" Kickstarter project. He lives in Vancouver where he’s conducting MSc research and teaching at the University of British Columbia, and building workshops around open source tools.

**Comment by kristinashu** [comment]
Thanks, this has been updated!
