### ISSUE TITLE
Guide: ADDITION Final Bios and photos

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/Mozfest2016_production#180]
Please add these final Space Wrangler Bios and Photos
#### Arliss Collins

Arliss works on data and metrics for the Mozilla Learning Network, analysing data collection methods and standardising collection processes across the MLN hubs. She helps groups to understand their member data as it relates to engagement/growth/retention in their communities and to guide the development of initiatives that build/strengthen member relationships.

@kristinashu please provide photo. This is from Twitter: https://pbs.twimg.com/profile_images/613544115507060736/bz0ATf6e.jpg
#### Manal Hassan

Manal is a FOSS enthusiast and the co-founder and director of Motoon, a venture that connects techies to progressive causes and local communities in need of their skills. Her main interest is adapting and delivering technology to non-techies, and training them to use it on their own. She co-founded the Egyptian GNU/Linux Users Group in 2004, the Arab Techies Collective in 2008 and Open Egypt in 2013.

Photo: http://www.motoon.org/sites/default/files/styles/wide_headshot/public/Manal.jpg?itok=RDGwmRIM
#### George Roter

George leads the Participation Team at Mozilla, whose aim is to develop community leaders and contributors who will invent, shape and defend the internet. Our vision is for Mozilla to become a global pacesetter in participation.

Photo: https://georgeroter.files.wordpress.com/2015/04/img_20141203_054631.jpg?w=800 
#### Raegan MacDonald

@kristinashu please add photo or use this one https://www.flickr.com/photos/mozfest/22481926559/in/album-72157658649418943/

**Comment by edrushka** [comment]
cc @carrie-ann

**Comment by kristinashu** [comment]
Thanks Erika! I think those photos should work. 

Thanks Carrie for adding these in!

**Comment by kristinashu** [comment]
Thanks, this has been updated!
