### ISSUE TITLE
Design a MozFest poster or banner

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Mozfest2016_production#183]
Might be nice to have some sort of mozfest branded poster or banner at the entrance of Ravensborne. Either to hang from the railings or over the registration table. 

cc @sabrinang @xmatthewx

**Comment by sabrinang** [comment]
Will this be similar size to the other mozfest hackable posters? These sound like they could be on the larger side if they are hanging from the railings

**Comment by xmatthewx** [comment]
Could be nice to pair it with the existing One Web banner and sized to complement that.

**Comment by sabrinang** [comment]
@xmatthewx @kristinashu can you give me some design feedback for MozFest branded posters on redpen: https://redpen.io/p/gb43c52500b46e0e0b

It has the same dimensions as the pink One Web wayfinding poster. I'm unsure if we wanted to use pink to match it exactly or choosing a color like purple that would compliment it but not compete with the 3 other colours wayfinding posters are using. Also, a horizontal poster layout may be nice for the registration table application.

![mozfest-poster-scale-preview](https://cloud.githubusercontent.com/assets/2492510/19448945/a96510de-9458-11e6-8f06-592f7d875f1d.png)

**Comment by kristinashu** [comment]
Looks good @sabrinang! The horizontal ones will work well at the registration table (maybe double check if the dimensions would work at a table). 

I think we already use pink and purple a lot so I'm leaning towards the teal and blue version. 

For the vertical ones. Maybe they should be a different size than the pink One Web banner? Might be too symmetrical to have them the same size and paired together.

**Comment by sabrinang** [comment]
![mozfest-poster-scale-preview_2-02](https://cloud.githubusercontent.com/assets/2492510/19658680/acb35572-99dd-11e6-87b8-2eda63f8d100.png)
updated redpen: https://redpen.io/p/gb43c52500b46e0e0b

I have two .pdfs exported (horizontal pink, vertical teal) the same size as floor number banners here: https://drive.google.com/drive/u/1/folders/0B4Q8pzCpDS_eVWhfWmh1QTlHeEk

@marcwalsh Do you have the dimensions (width and height) of the folding tables used for registration?

**Comment by kristinashu** [comment]
Awesome! Maybe we can just adjust the dimensions once we're at Ravensbourne, since it'll be real soon!

**Comment by marcwalsh-zz** [comment]
Printed at the current size but can change if needs be!

**Comment by sabrinang** [comment]
## Post MozFest Documentation

We placed two teal vertical MozFest branded posters on the balustrade facing the entrance. It was placed symmetrically with accompanying one web banners to frame the monitor in the center (just above the registration table). Also, two pink horizontal MozFest branded posters were taped on the front of the tables near the entrance to make the tables appear more prominent. The pink banners were a bit larger than the table's width and height.
![mozfest-documentation-photos_branded-posters](https://cloud.githubusercontent.com/assets/2492510/20120529/1800a75e-a5c2-11e6-8482-3956f2f23287.png)
