### ISSUE TITLE
Print map insert for Festival Guide

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Mozfest2016_production#184]
Based on map design in https://github.com/MozillaFoundation/Mozfest2016_production/issues/91 and festival guide design in https://github.com/MozillaFoundation/Mozfest2016_production/issues/136

Will be 337mm x 460mm folded into four.

Front of the map will look like (but with the Space locations):
<img width="524" alt="screen shot 2016-10-11 at 11 26 42 am" src="https://cloud.githubusercontent.com/assets/1068783/19283220/edb5fde6-8fa5-11e6-9671-fa8183895ad6.png">

Back will look like:
<img width="749" alt="red-pen-b1534aa1-fbce-4441-d223-36d3c9f84d6f" src="https://cloud.githubusercontent.com/assets/1068783/19283291/1fe00898-8fa6-11e6-8253-ab18340fcbfc.png">

And all together:
![red-pen-13bc0bce-b330-42ac-c340-38676703f08c](https://cloud.githubusercontent.com/assets/1068783/19283306/2c7ba6a2-8fa6-11e6-8289-337e12f0f151.jpg)

**Comment by Carrie-ann** [comment]
@kristinashu Please find the illustrator file in the drive which includes the back glitch and map. 

https://drive.google.com/drive/folders/0BzVQTTEXQZdXQjNkdkJmdXFIN1U

**Comment by Saallen** [comment]
hey @kristinashu there are a few icons on the wrong place- let me know when you want me to start making comments on icons to move

**Comment by kristinashu** [comment]
Thank you @Saallen! I met with @marcwalsh and made a bunch of updates to the map:
https://redpen.io/p/nca82e6ea157535639
Please comment in redpen if the map needs any adjustments. 

<img width="860" alt="red-pen-5c09e08e-8b89-451d-b89d-f0fa46b8a665" src="https://cloud.githubusercontent.com/assets/1068783/19394031/25b5e8f8-91ec-11e6-88e3-a8613062f463.png">

**Comment by kristinashu** [comment]
Here's the final map insert:

Dimensions are 337mm x 460mm and then folded into four.

@marcwalsh can you please check with the printer how it will be folded? The key thing is for the logo to be in the same corner as the logo on the notepad and festival guide. I can move the logo if it isn't working with the way they fold it.

![map-insert-01](https://cloud.githubusercontent.com/assets/1068783/19494067/39e77776-9532-11e6-8155-86e142a8186e.jpg)
<img width="973" alt="map insert-02" src="https://cloud.githubusercontent.com/assets/1068783/19498789/ce1ca262-9547-11e6-9ced-6b62b3dd2d77.png">

Print files (.ai file and pdf with crop marks): 
https://drive.google.com/open?id=0BzVQTTEXQZdXQjNkdkJmdXFIN1U

**Comment by kristinashu** [comment]
Updated this overview map. @marcwalsh let me know if the printer gives you a template for this. if not, here's the print PDF:

[Map Insert (outlined).pdf](https://github.com/MozillaFoundation/Mozfest2016_production/files/540278/Map.Insert.outlined.pdf)

also in [Drive](https://drive.google.com/open?id=0B2irLVDJivhLVW1DY0ZGSk54TGs)

**Comment by marcwalsh-zz** [comment]
Sent to print!!

**Comment by sabrinang** [comment]
## Post MozFest Documentation

The map insert was found clipped in the festival guide pack for attendees to reference.
![mozfest-documentation-map-insert](https://cloud.githubusercontent.com/assets/2492510/20194244/79a29db6-a746-11e6-82c5-d185beea6ba5.png)
