### ISSUE TITLE
Draft article for Medium - reviewing the Tate fringe event

### ISSUE THREAD

**Issue by StevieBenton** [MozillaFoundation/Mozfest2016_production#185]
Hello everyone. 

I went to the _excellent_ fringe event yesterday at Tate Britain and have produced a write-up. [It's in draft, and is here](https://docs.google.com/document/d/1wUnh8vcXQrud5U9xX7Il9PApGbVWA7btO-DBskoldko/edit?usp=sharing). 

It's a touch lengthy but in my opinion the issues being explored merit the extra detail. Please do let me know what you think and when we are all happy I will publish on Medium. The doc also includes my notes from the event for reference.

Tagging @edrushka @Saallen @KevZawacki as folks who might be interested.

Thanks all!

**Comment by KevZawacki** [comment]
Thanks, @StevieBenton! Do we have photos to accompany?

**Comment by StevieBenton** [comment]
I have a couple on my phone, will share them on here. They are pretty dark, as the room was pretty dark during the presentations, but I have a nice one from after the presentation which I think looks good

**Comment by StevieBenton** [comment]
I have a couple on my phone, will share them on here. They are pretty dark, as the room was pretty dark during the presentations, but I have a nice one from after the presentation which I think looks good

**Comment by edrushka** [comment]
This is nice, Stevie. I reviewed and suggested a couple lines to pull out/highlight when it goes to Medium. 

We def. need images here. Suggest screen-capping tweets with photos if the ones on your phone are too dark.

**Comment by StevieBenton** [comment]
Thanks for the comments Erika, very helpful. I'll take another look and make any revisions required. 

In terms of image, there's this one which I think is OK but a bit generic...
![tate fringe image](https://cloud.githubusercontent.com/assets/22321839/19358644/800c566c-916e-11e6-8da4-c6ee52eec7f0.jpg)

**Comment by edrushka** [comment]
Looks ready for Medium! Kat Braybrooke is a former MoFo and she posted lots of great pics on Twitter. You could include screengrabs of her tweets or reach out for permission to use the images directly.

**Comment by StevieBenton** [comment]
I've just written to Kat for permission to use her lovely photos as well. I'll start uploading the article to Medium but keep as a draft until the pics are included.

Thanks for the useful feedback!

**Comment by StevieBenton** [comment]
Hello again, 

Kat very kindly allowed me to use her images from the event. I've added these into the post and have now published to live on the Festival Medium publication. [It's here](https://medium.com/mozilla-festival/view-from-the-fringe-digital-arts-show-tell-tate-britain-4f56af848820#.xd68ff1e4). 

Thanks for all your input,

Stevie
