### ISSUE TITLE
List of Vendor / Access Names for Ravensbourne IDs

### ISSUE THREAD

**Issue by marcwalsh-zz** [MozillaFoundation/Mozfest2016_production#186]
Need to create a list of vendor names who require ID card access to site and the level of clearance required.
- [ ] Mozilla Production
- [ ] Mozilla Volunteers
- [ ] MozAV
- [ ] SLX
- [ ] Dosed
- [ ] Feast
- [ ] Risteretto
- [ ] Todo
- [ ] Tinie Creches
- [ ] Mozilla

**Comment by SpikeUK** [comment]
- [x] Volunteers ;-)

**Comment by marcwalsh-zz** [comment]
Added, thanks @SpikeUK

**Comment by SpikeUK** [comment]
@marcwalsh would you like a list of the first line volunteers that will need access cards here or do you have another preferred communication channel?

**Comment by marcwalsh-zz** [comment]
@SpikeUK just talked to @Saallen and we won't be able to issue the the room access cards to volunteers, as they wouldn't be needing access to the areas they will provide for us. We will issue you a card.

**Comment by SpikeUK** [comment]
OK @marcwalsh ! Assuming that we will have access to the Crew Room? I wish to be able to secure this room it is left unattended. Volunteers would be leaving their personal possessions in here whilst they are working elsewhere. Last year some of my property was pinched :(
