### ISSUE TITLE
Draft article for Medium: The Makers of Mozfest - Erika

### ISSUE THREAD

**Issue by StevieBenton** [MozillaFoundation/Mozfest2016_production#187]
Hello everyone,

I've just finished drafting the first piece in the "Makers of MozFest" series. I'll be interviewing people who make the festival happen, including MoFo staff, space wranglers, facilitators and so on. to capture the experience from the eyes of those intimately involved.

The first piece is based on an interview with Erika. [It's here](https://docs.google.com/document/d/1ZRgrxDIJpKnZStomE9r8OH-zg13nJHjlywwNQLHKinw/edit?usp=sharing).

I'm particularly interested to get a handle on whether you think the Q&A works or whether you'd prefer something more narrative / feature style. There's no rush on this but please let me know what you think.

cc @edrushka @Saallen @KevZawacki @KGorr as potentially interested folks.

**Comment by KGorr** [comment]
I'm always a fan of the Q&A style as it allows the readers to hear from the subject of the article directly. It's what we use for the community spotlights and gets great responses. Nice job!

**Comment by StevieBenton** [comment]
Thanks Kristina! That's what I was thinking. Also, so much of the content I'm producing is editorial / feature style, it's good to mix things up a little.

**Comment by StevieBenton** [comment]
Hello folks, this is now in Medium. Not yet live, but we can publish whenever we like. Any suggestions?

**Comment by StevieBenton** [comment]
Sorry, forgot the link https://medium.com/@StevieBenton/36e199d065df

**Comment by KevZawacki** [comment]
I think we should go ahead and publish today / tomorrow.

**Comment by edrushka** [comment]
Works for me. Let's just keep pushing out content as we have it. No need to wait.

**Comment by StevieBenton** [comment]
Great, thanks guys. Published live to the MozFest Medium now.

**Comment by edrushka** [comment]
Thanks Stevie! I'm famous!! 😁
