### ISSUE TITLE
Wall projection

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Mozfest2016_production#188]
Here are the assets for the light projection on to the wall on Level 4+.

Colour palette:
- teal #00fbdd
- yellow #e4f832
- pink #fa1bab
- purple #6d22af
- blue #362fc1

<img width="1190" alt="screen shot 2016-10-14 at 9 03 57 am" src="https://cloud.githubusercontent.com/assets/1068783/19394266/3cae1d5e-91ed-11e6-9012-7750dabb7f0f.png">

eps + svg of the gear icon:
[Pink Gear.zip](https://github.com/MozillaFoundation/Mozfest2016_production/files/529945/Pink.Gear.zip)

@marcwalsh let me know if you need anything else for this.

**Comment by sabrinang** [comment]
## Post MozFest Documentation

On level 4 - Big Space, the pink gear logo was projected with a slow rotation in the high center of the wall. It was accompanied by changing patches of coloured light ranging from pinks, blue, greens, oranges, blues accompanied by lots of natural light.

![mozfest-logo-wall-projection small](https://cloud.githubusercontent.com/assets/2492510/20079232/a1f511b8-a4f8-11e6-8166-2813613cbcb2.gif)
![30600614106_a2f7e5e47e_k](https://cloud.githubusercontent.com/assets/2492510/20079638/6b8b340c-a4fa-11e6-8960-12c9ceadb24e.jpg)

Just below level 4 (above the open space facing the entrance), MozEx used a wall projection to showcase a loop of their work with the space icon adjacent to the right. It also projected the mozilla festival wordmark too. 

![mozfest-mozex-wall-projection small](https://cloud.githubusercontent.com/assets/2492510/20079236/a46303ce-a4f8-11e6-8a21-45fa3f7c21cd.gif)
![30534911851_b8d5a28969_k](https://cloud.githubusercontent.com/assets/2492510/20079427/75dc42e4-a4f9-11e6-928c-3756a8e91df1.jpg)
