### ISSUE TITLE
Draft article for Medium: The Makers of MozFest - Sarah

### ISSUE THREAD

**Issue by StevieBenton** [MozillaFoundation/Mozfest2016_production#189]
Hello everyone,

I've finished up the first draft of the second Makers of MozFest piece, this time the focus is on Sarah and [the article is here](https://docs.google.com/document/d/1Lh6vTZPW7Drk1v4AkekQLGcBkPbvcihcUcerHDeYedY/edit?usp=sharing).

Please do take a look and feel free to edit, comment etc. 

Tagging @edrushka @Saallen @KevZawacki @KGorr as people who may be interested.

**Comment by StevieBenton** [comment]
This is now ready for adding to Medium. We can hold as draft for as long as we like, there's no rush to publish. @Saallen do you have any images you'd like me to use?

**Comment by Saallen** [comment]
Let me have a look @StevieBenton

**Comment by StevieBenton** [comment]
Some suggested images below. If everyone is happy I can publish whenever we like.

https://www.flickr.com/photos/mozfest/22848063806/in/album-72157658649418943/
https://www.flickr.com/photos/mozfest/22251296084/in/album-72157658649418943/
https://www.flickr.com/photos/mozfest/22252802803/in/album-72157658649418943/

**Comment by StevieBenton** [comment]
Hello folks,

I've published this piece now to live. [You can see it here](https://medium.com/mozilla-festival/the-makers-of-mozfest-sarah-allen-8ac0b5417fde#.i9gtcdwwo). 

Thanks for all of your input!
