### ISSUE TITLE
Creating legacy within our Festival guide

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/Mozfest2016_production#19]
Below are pictures of a really great information booklet from a hotel in Berlin. 
Rather than add all the boring housekeeping rules on a laminated page or within a bound leather folder the hotel created fairy tales. In those tales, told on postcards or within a small book, was the key information for staying within the hotel . All these postcards were displayed within a little box

**Comment by Saallen** [comment]
![tmp_15714-img_20160507_105903-341542292](https://cloud.githubusercontent.com/assets/10194015/16778717/23050356-4867-11e6-8a32-11c3c6f283e1.jpg)
![tmp_15714-img_20160507_105731-137349422](https://cloud.githubusercontent.com/assets/10194015/16778729/2dc58838-4867-11e6-8dda-1dd712273297.jpg)
![tmp_15714-img_20160507_105645-382866914](https://cloud.githubusercontent.com/assets/10194015/16778739/397076de-4867-11e6-9597-e91f6268db2a.jpg)
![tmp_15714-img_20160507_105523-979230235](https://cloud.githubusercontent.com/assets/10194015/16778747/42c064ec-4867-11e6-9684-6a9b02c86472.jpg)

**Comment by Saallen** [comment]
![2016-07-12 19 37 55](https://cloud.githubusercontent.com/assets/10194015/16778946/27f824d2-4868-11e6-8b6f-8957e9bf8427.jpg)
![2016-07-12 19 38 16](https://cloud.githubusercontent.com/assets/10194015/16778958/32a6fa8e-4868-11e6-9926-aa922a16133b.jpg)

**Comment by edrushka** [comment]
Closing this beautiful ticket, but I've added some of the elements to the nice-to-have list.
