### ISSUE TITLE
Design sign for #MozHelp desk

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Mozfest2016_production#191]
@marcwalsh @edrushka do you think we need a sign for the #MozHelp desk, or do we already have something?

**Comment by kristinashu** [comment]
I will make a sign of this. @marcwalsh does the help desk have a pinboard behind it like the info desks? Or should I make something to go on the table?

**Comment by marcwalsh-zz** [comment]
@kristinashu I think this should be for the table

**Comment by kristinashu** [comment]
@marcwalsh here's an A4 sign for the table. Could we print 2 of these to go on top of the table sandwich board style? Printed on cardboard would be ideal but if not then we can just to it at Ravensourne and spay mount it on formcore.

Here's the print PDF with crop marks:
https://drive.google.com/open?id=0B2irLVDJivhLc1lLQ0RsTW5TeW8

<img width="961" alt="screen shot 2016-10-20 at 11 04 23 am" src="https://cloud.githubusercontent.com/assets/1068783/19571944/00108630-96b5-11e6-8047-728fe0b6280e.png">

**Comment by marcwalsh-zz** [comment]
Printed! In Production Office

**Comment by sabrinang** [comment]
## Post MozFest Documentation

The paper sign was mounted on cardboard to create a small sandwich board #MozHelp sign. The sign was placed on the help desk on level 5.

![30725957316_5531e2c9ca_k](https://cloud.githubusercontent.com/assets/2492510/20121210/09439840-a5c5-11e6-9f2a-77e0f3f7300e.jpg)

**Comment by SpikeUK** [comment]
Great picture of Fuzzyfox and AVDan - ace MozFest volunteers. May I please have your permission please @sabrinang to share that image?

**Comment by sabrinang** [comment]
Hey @SpikeUK I found the photo on Flickr here: https://www.flickr.com/photos/livvya/30725957316/ I didn't take this photo so you'll need their permission, not mine!

**Comment by SpikeUK** [comment]
Thank you @sabrinang - the photographer (Livvy Adjei) was one of our wonderful Local Volunteers and I put her on special mission to picture as many other Volunteers as possible :)

**Comment by kristinashu** [comment]
If the help desk is in the same spot next year, we could also have a small sign on the railing. This way it will viewable in the atrium.
