### ISSUE TITLE
Draft for review: Volunteerism at the heart of open

### ISSUE THREAD

**Issue by StevieBenton** [MozillaFoundation/Mozfest2016_production#194]
Hello folks,

Following last night's event, at which I spoke to some great people (thanks @Saallen for pointing them my way!) I've put together a piece about how volunteering is at the heart of the open movement. [The draft is here](https://docs.google.com/document/d/16CQ6ANTVNw9C1MNa07FwtEujaEv3oeMgPLuB3saXjow/edit?usp=sharing).

I have a photo or two on my phone that I can put in the article when we publish. I'd be really grateful if you guys could have a look and let me know what you think through comments and edits.

Thanks!

cc @edrushka @KevZawacki @KGorr

**Comment by KevZawacki** [comment]
This is a great post, @StevieBenton. Thanks!

**Comment by StevieBenton** [comment]
Aw, thanks @KevZawacki !

**Comment by StevieBenton** [comment]
Does anyone have any further thoughts on this or shall I go ahead and publish?

**Comment by edrushka** [comment]
Go for it!

**Comment by StevieBenton** [comment]
[And we're live](https://medium.com/mozilla-festival/volunteerism-the-heart-of-the-open-movement-73da9263cab5#.32j2bimv1) :) 

Thanks for the input guys.
