### ISSUE TITLE
Draft for review - Makers of MozFest: Claire Selby

### ISSUE THREAD

**Issue by StevieBenton** [MozillaFoundation/Mozfest2016_production#195]
Hello everyone,

I had a really good conversation with Claire Selby from Ravensbourne this afternoon. She gave me some really good insights into the college's perspective of the festival.

I've put together a draft Makers of MozFest piece based on the interview. [It's here](https://docs.google.com/document/d/1sEs2YaNuXVu9XBn06oyhzwvU0E0-9NOiMK4qlnzAj_Y/edit?usp=sharing). Please do feel free to edit, comment etc. Claire also has the doc, and she has sent me some great photos to use (including one of the Play-Doh emoji!

**Comment by StevieBenton** [comment]
Tagging @edrushka @KevZawacki @KGorr

**Comment by KGorr** [comment]
Love this perspective @StevieBenton. I added some comments on the doc for things that could be clarified a bit. Let me know if you have any questions. Nice piece!

**Comment by StevieBenton** [comment]
Thanks for the really useful feedback @KGorr ! Have amended the text accordingly. The photo is very helpful, too.

I'm waiting to see if Claire has any further comments, then will go ahead and publish if we are all happy.

**Comment by KevZawacki** [comment]
@StevieBenton Good to go!

**Comment by StevieBenton** [comment]
Hello again,

This piece is [live now](https://medium.com/mozilla-festival/the-makers-of-mozfest-claire-selby-3218ff9c6b49#.flggpefod). Thanks everyone for the input!
