### ISSUE TITLE
List of terms for Closed Captioning & BSL

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/Mozfest2016_production#196]
We need to provide the BSL and closed captioning people with a list of weird terms and acronyms people might use on mainstage and in D&Ds.

Step 1: @marcwalsh is reaching out to View Source team for their list

cc @KevZawacki

**Comment by KevZawacki** [comment]
FLOSS -- Free/Libre and Open-Source Software

**Comment by edrushka** [comment]
There is a list of tech terms [here](http://techterms.com/category/acronyms). If you sort by tech factor, we'll like only here things in the 1-4 out of 10 range. Here are the most likely:

FLOSS -- Free/Libre and Open-Source Software
IoT -- Internet of Things
[WYSIWG](http://techterms.com/definition/wysiwyg)
[VPN](http://techterms.com/definition/vpn)
[VoIP](http://techterms.com/definition/voip)
[URL](http://techterms.com/definition/url)
[USB](http://techterms.com/definition/usb)
[GIF](http://techterms.com/definition/gif)
[HTML](http://techterms.com/definition/html)
[FAQ](http://techterms.com/definition/faq)
