### ISSUE TITLE
Finalize and Print Pulse & Net Mapping posters

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/Mozfest2016_production#198]
We will have a kiosk for Pulse and Network Mapping. With signage:
- large poster to draw attention
- small sign for context/instructions

Draft desigin: https://github.com/MozillaFoundation/Mozfest2016_production/issues/156#issuecomment-252122482

Next steps
- [x] @acabunoc to review copy and shortlink with @liberaliscomputing
- [x] Designer to update draft design 
- [x] Designer to handoff to @marcwalsh 
- [ ] @liberaliscomputing to share URL with @xmatthewx for shortlink

**Comment by abbycabs** [comment]
Discussed a short link with @liberaliscomputing -- we'd like mzl.la/map. He'll spin up a heroku instance to point to and drop it here later.

**Comment by kristinashu** [comment]
@xmatthewx @marcwalsh here are the two A4 posters with 3mm bleed and crop marks:

[MozFest Pulse Signs A4.pdf](https://github.com/MozillaFoundation/Mozfest2016_production/files/543011/MozFest.Pulse.Signs.A4.pdf)

<img width="482" alt="screen shot 2016-10-20 at 2 59 20 pm" src="https://cloud.githubusercontent.com/assets/1068783/19579491/d4fd01aa-96d5-11e6-9a86-aa675c335642.png">
<img width="482" alt="screen shot 2016-10-20 at 2 59 27 pm" src="https://cloud.githubusercontent.com/assets/1068783/19579492/d501e120-96d5-11e6-9df0-653b4d983e0d.png">

What size makes sense for the larger vertical banners? I was thinking of putting the two banners onto one A0 (close to what Matthew has mocked up) or one A1 (smaller). Would these be printed at Ravensourne or at the printer.

<img width="654" alt="screen shot 2016-10-20 at 3 00 36 pm" src="https://cloud.githubusercontent.com/assets/1068783/19579535/098eb1b6-96d6-11e6-93fe-4c59c0bcd71b.png">

**Comment by kristinashu** [comment]
@sabrinang has pointed out the white box corners aren't right. Do either of these look better to you?
<img width="1111" alt="screen shot 2016-10-21 at 9 31 03 am" src="https://cloud.githubusercontent.com/assets/1068783/19605683/39d030a2-9771-11e6-8137-602b704f2eb8.png">

**Comment by xmatthewx** [comment]
No strong opinions here on box corners. I knew that mine were a sad approximation.

I'm flexible on size. The large one should be visible from across the science fair. I'd say 30" wide is the minimum. 24" is probably too small. For science fair, having this mounted on cardboard would be very very helpful.

**Comment by kristinashu** [comment]
@sabrinang do you have a preference?

@xmatthewx to simply and not overcrowd the table, we should just do one version for Map and one version for Pulse. I'll update the A3 poster to A4 and scrape the version with the point.

**Comment by xmatthewx** [comment]
I'm a little confused. Are you suggesting we just make the small sign bigger? And don't do the bigger sign with vertical text? 

The smaller pieces serve to orient people who do walk up to try the kiosks. I care less about the quality of these. 

We need to keep the bigger sign with large vertical text. It will hang above the kiosk throughout the weekend. The small sign's design won't serve well to draw in users as they dash between sessions. People won't see the kiosks without them. You can skip the arrow. We can cut if there's time and it makes sense when we install. 

re: Box corners. One on the right is a bit more readable. One of the left keeps with fest design better. I'm fine with either. Maybe slight preference for one on the left.

**Comment by kristinashu** [comment]
Oh ok, from our call I thought we weren't hanging anything but since we are, here are the two vertial banners on one A0:

I've left lots of glitch pattern around the text so we can trim as needed at Ravensbourne.

<img width="689" alt="screen shot 2016-10-21 at 12 31 36 pm" src="https://cloud.githubusercontent.com/assets/1068783/19609149/550d9378-978a-11e6-852a-d813e6078ff7.png">

**Comment by sabrinang** [comment]
@kristinashu If you are going with the left style I suggest to adjust the vertical spacing a bit above/below the letters so it frames the inverted letters giving it a bit more contrast. Example:
<img width="888" alt="screen shot 2016-10-21 at 12 33 10 pm" src="https://cloud.githubusercontent.com/assets/2492510/19609180/91447280-978a-11e6-93a4-452ca5708297.png">

**Comment by kristinashu** [comment]
Updated! 
<img width="468" alt="screen shot 2016-10-21 at 1 23 34 pm" src="https://cloud.githubusercontent.com/assets/1068783/19610515/b3d8391a-9791-11e6-98b2-d3b937d31bb0.png">
<img width="467" alt="screen shot 2016-10-21 at 1 23 42 pm" src="https://cloud.githubusercontent.com/assets/1068783/19610516/b3dfceb4-9791-11e6-9e80-7aa44b3bcf98.png">
<img width="500" alt="screen shot 2016-10-21 at 1 23 51 pm" src="https://cloud.githubusercontent.com/assets/1068783/19610514/b3d769a4-9791-11e6-8776-9c397352bee4.png">

Here's the print ready PDF: https://drive.google.com/open?id=0B2irLVDJivhLZmhRd1NLNEtJTVE

**Comment by marcwalsh-zz** [comment]
Printed and in Production Office
