### ISSUE TITLE
Reserve computers for Pulse & Mapping kiosk

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/Mozfest2016_production#199]
@marcwalsh – need anything from me to do arrange for this? 

We'll need 
- two iMacs or Mac minis. 
- two keyboards & mouse
- powerstrip
- standing desk or table

It would be good to have this during the science fair. But if you don't have enough computers, I can prep set up on Thurs/Fri, but wait until Saturday to put it out.

**Comment by marcwalsh-zz** [comment]
Sure thing, I'll get this sorted for you today. We should be able to get you two laptops to us if that's okay?

**Comment by xmatthewx** [comment]
I'll take what I can get, but would prefer iMac or mac mini if possible. 

Also... We  need security cables. While we will station this somewhere central, we don't plan to staff the table throughout the day.

**Comment by marcwalsh-zz** [comment]
Cool, I'll have a look and see. There's two Mac Mini's available however the only screens we have on-site are 40" which would probably be overkill for what you need!

I'll get locks either way!
