### ISSUE TITLE
Localising of Call for Proposals

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/Mozfest2016_production#2]
Is it possible?
Who owns this?
How to elevate sessions to other spaces?

**Comment by edrushka** [comment]
We did it! 🎆 CFP localized into [Arabic] (https://mzl.la/MozFestArabic), [French] (https://mzl.la/Fran%C3%A7ais) and [Spanish] (https://bit.ly/MozFestSpanish).   

Also made a field in the EN form allowing people to list other languages they can hold their session in.
