### ISSUE TITLE
Link to Pulse from Mozfest site (post Festival)

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/Mozfest2016_production#200]
If use of Pulse goes well at the festival, we should find a way to link to it from the festival site. Design-wise, could sit near link to archive of talks. 

Adding this to a new November 4th milestone for post-festival work.
- [ ] make sure things have been tagged with mozfest
- [ ] link to https://mzl.la/mozfest-pulse?keyword=mozfest

**Comment by edrushka** [comment]
@xmatthewx I am scoping site updates to go live _immediately_ after the festival (Sunday night or Monday morning) based what's on staging: http://mozillafestival-org-staging.herokuapp.com/

Let me know if you would like me include a link to pulse in the top nav. We could put it where Tickets is now. Suggest 'PULSE' as link text.

**Comment by xmatthewx** [comment]
An item in the top nav could work. Will "Watch Live" be changed to something like "See Videos"? We could also have a button next to that says "Browse Projects" or something similar.  

I do think we should see how it goes with Pulse before we add the link. Make sure we have enough good Mozfest specific substance.

**Comment by edrushka** [comment]
@xmatthewx Yes, "watch live" will become "opening keynote" and "speaker series". You can see the changes here https://github.com/MozillaFoundation/2016.Mozillafestival.org/issues/120
Do you want to coordinate with @alanmoo  and let him know Sunday night if you want Pulse added to the top nav?

**Comment by xmatthewx** [comment]
@alanmoo – let's check in on Sunday. Most likely, yes, we'll want to change top nav link to point to Pulse.

**Comment by kristinashu** [comment]
This is covered in https://github.com/mozilla/mozillafestival.org/issues/482
