### ISSUE TITLE
Design assets for the Registration table

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Mozfest2016_production#201]
Would be great to make the Registration table feel a little more official. Are there any signs you can think of that we should design?

Instead of signs like this:
<img width="662" alt="screen shot 2016-10-20 at 3 37 57 pm" src="https://cloud.githubusercontent.com/assets/1068783/19580491/6be76178-96db-11e6-8805-ad644351e743.png">

@edrushka @marcwalsh @sabrinang

**Comment by kristinashu** [comment]
We'll have a MozFest banner hanging down the front of the table https://github.com/MozillaFoundation/Mozfest2016_production/issues/183

**Comment by sabrinang** [comment]
2 signs will probably be needed for the table:
- 1) for sign-in or pickup your name card
- 2) for collecting your swag

**Comment by SpikeUK** [comment]
Possibly a third activity:
- 3) for selecting your "I speak ........ language" stickers ref #149

**Comment by marcwalsh-zz** [comment]
Sounds good! Lets print onsite and mount on foam board. I'll get @DanRad95 to order some!

**Comment by sabrinang** [comment]
possible location for:
- 4) the icebreaker matching game https://github.com/MozillaFoundation/plan/issues/839

@marcwalsh @DanRad95 I think some cardboard or thick card stock is fine! (not a big fan of the foam board/core but if it is ordered already it will do)

**Comment by sabrinang** [comment]
I'm planning that we have 3 signs for the various steps in the registration process:
- 1) **Sign-in & Register Here**
  - check name off list? 
- 2) **Customize Your Name ID**
  - marker station to write name
  - language sticker area
  - icebreaker sticker area 
- 3) **Collect Your Swag**
  - festival guide package, water bottle, stickers etc.

@edrushka Can you review the copy for 3 signs and are these steps correct? See redpen example: https://redpen.io/p/htf91a4ad25f272ea2

For the dimensions, I am thinking A4 size horizontal.

**Comment by kristinashu** [comment]
Awesome @sabrinang! I just wonder if we should swap step 2 and 3? People could take a while at Step 2.

**Comment by edrushka** [comment]
Copy looks mostly good. I'd change to "Customize your name card" or "...name tag" or "lanyard". Name ID sounds kinda weird. 

Agree with Kristina's suggestion to put customization station last if possible as people will take longest there.

**Comment by sabrinang** [comment]
Great - thanks for the feedback! I changed the steps, updated to name tag and iterated on the colours seen in the redpen.

**Comment by sabrinang** [comment]
.pdf on google drive for print: https://drive.google.com/file/d/0B4Q8pzCpDS_eUmRKcHIyeVVHZHc/view

**Comment by sabrinang** [comment]
## Post MozFest Documentation

For Friday, the main registration table was set up with large pink horizontal mozfest posters along with small sign-in & register here and welcome signs taped along the side of 4 tables. This table had name card and lanyards for distribution along with participation guidelines printed on the table for reference. The customization table had the customize your name tag sign and welcome sign taped on the table side as well with language and sticker match labels available. A small sticker match description sign was placed standing on this table too.

On Saturday and Sunday, there was a dedicated table for youth & press and a large vertical sign was taped to the front of one table. The swag table was set up with festival guide packs and water bottles for pickup and a small sign for collect your swag was placed in front.

Behind the registration table, the privacy alert poster is seen to indicate that yellow lanyards could also be distributed here and for attendees to be aware of what it means.

![mozfest-documentation-photos_registration-table](https://cloud.githubusercontent.com/assets/2492510/20151058/9acac40c-a66d-11e6-8bd6-e47697120a14.png)

![mozfest_28oct_117_29987892824_o](https://cloud.githubusercontent.com/assets/2492510/20151777/4aa8d312-a670-11e6-8ae1-eed139328512.jpg)
