### ISSUE TITLE
Please design design "Volunteers Only" sign to be locally printed

### ISSUE THREAD

**Issue by SpikeUK** [MozillaFoundation/Mozfest2016_production#202]
Please design design an A4 "Volunteers Only" sign (to be locally printed) based upon the background in #191.
Could please also version without text so that we could design and print locally ad hoc signage.
@kristinashu ?

**Comment by edrushka** [comment]
@SpikeUK could these work for your ad hoc signage? https://redpen.io/p/mq6690195fde6aad51

**Comment by SpikeUK** [comment]
That would probably be fine @edrushka

**Comment by SpikeUK** [comment]
We made our own in the end
![20161030_113125small](https://cloud.githubusercontent.com/assets/1629474/19836341/6b390d3c-9e95-11e6-8746-215579d6c0a0.jpg)
