### ISSUE TITLE
Prepare graphics for AirMo & Facebook streams

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/Mozfest2016_production#206]
#### AirMo Background

To replace clouds seen [here](https://air.mozilla.org/monthly-speaker-series-metadata-with-harlo-holmes-2016-10-12/)
- [x] Need a static, muted version of one of our patterns. Keep in mind AirMo logo will go over it. 16x9 (1920x1080)
#### Logos & Wordmarks
- [x] PNG version of logo & wordmark
- [x] PNG version of One Web circle (white/clear circle version)
- [x] PNG version of gear icon on its own
#### Title Cards (16:9, 1920x1080)

To replace Mozilla heart seen [here](https://air.mozilla.org/monthly-speaker-series-metadata-with-harlo-holmes-2016-10-12/)
- [x] MozFest 2016 Opening Keynote
- [x] MozFest Dialogues and Debates Speakers Series

@KevZawacki do we need individual title cards for each speaker, or can we just use a single generic one? (I vote for simple/generic.)

**Comment by edrushka** [comment]
cc @xmatthewx and @kristinashu Live stream team has requested these by EOD Wednesday if possible. Thanks!

**Comment by KevZawacki** [comment]
@edrushka Generic is fine!

**Comment by kristinashu** [comment]
Here you go @edrushka!

For the background, we could use this:
<img width="1920" alt="airmozilla-background" src="https://cloud.githubusercontent.com/assets/1068783/19656441/e11f432e-99d4-11e6-91fa-8384b907203f.png">

Which would look like this:
<img width="1920" alt="airmozilla-background1" src="https://cloud.githubusercontent.com/assets/1068783/19656279/3004e864-99d4-11e6-82ea-076742b77fff.png">

Intro slides (let me know if you want any different text):
<img width="1920" alt="airmozilla-openingkeynote" src="https://cloud.githubusercontent.com/assets/1068783/19656578/72a3c95a-99d5-11e6-8bd9-601ee115bcbf.png">
<img width="1920" alt="airmozilla-speakerseries" src="https://cloud.githubusercontent.com/assets/1068783/19656579/72bcfa56-99d5-11e6-8ed7-f9b136d94ead.png">

Here are all the logos, in both pink (for white backgrounds) and white (for colored backgrounds):
[Logos.zip](https://github.com/MozillaFoundation/Mozfest2016_production/files/548540/Logos.zip)

@sabrinang do these look ok to you?

**Comment by sabrinang** [comment]
@kristinashu Neat! One feedback I have is how the teal triangle cuts across the white content which may not be enough contrast for some screens/eyes and it shifts depending on length of content it seems. 

Ideas:
- You can try to have the triangle smaller so it doesn't ever dissect the content 
- Some other slides have smaller triangles in the upper left, lower right if you wanted to try a two triangle composition 
- Alternatively, you can also try separating the mozfest logo placing it larger on the teal triangle in blue (inverted) and left align the wordmark with the titles all over the blue.

**Comment by kristinashu** [comment]
Thanks @sabrinang! I've updated the corners. 

@edrushka here are the assets: there are two versions for the Keynote slide (one with Marc's name and one without)
https://drive.google.com/open?id=0B2irLVDJivhLaTJidS1zbzBVamM

**Comment by edrushka** [comment]
Thanks!
