### ISSUE TITLE
Draft for review - Makers of MozFest: Dan

### ISSUE THREAD

**Issue by StevieBenton** [MozillaFoundation/Mozfest2016_production#207]
Hello everyone,

Just finished my write up of the interview I had with Dan earlier in the week.  [You can see the draft here](https://docs.google.com/document/d/1oi-5yWBUHehZnW17gprQNQlynHp3EiRa-X61OVHokB8/edit).

This piece I think really captures some of the essence of the community spirit behind the festival. Dan is going to review it also because there's a story in there about another volunteer that really needs to be right.

As ever, thoughts, comments edits welcome. 

cc @edrushka @KevZawacki @KGorr

**Comment by KevZawacki** [comment]
@StevieBenton Once Dan signs off, let's publish 👍

**Comment by StevieBenton** [comment]
Great! This piece is now [live on Medium](https://medium.com/mozilla-festival/the-makers-of-mozfest-dan-5b97f29b6ab7#.3hhae9gx0).

Thanks for all input :)
