### ISSUE TITLE
Draft for review: Makers of MozFest - Spike

### ISSUE THREAD

**Issue by StevieBenton** [MozillaFoundation/Mozfest2016_production#208]
Hello everyone, 

I had a great chat with Spike on Thursday. His knowledge and experience of MozFest were really interesting, especially from the perspective of someone who puts in so much hard work but doesn't see the end result.

[I've written up the interview here](https://docs.google.com/document/d/1sYyIjzwlh8fAYA9aeVNwGaTNO7N7JpINOOLP--flcFI/edit?usp=sharing). As ever, the doc is open so edits, comments and thoughts welcome.

Spike has also sent me some images, so once we're all happy please let me know so I can publish.

Thanks!

cc @edrushka @KevZawacki @KGorr

**Comment by KevZawacki** [comment]
@StevieBenton Looks great -- let's publish  👍

**Comment by SpikeUK** [comment]
Well and I am OK with it as well - the  word 'voluntarism' does not appear ;-)

**Comment by StevieBenton** [comment]
Thanks all, I'll get this published. Spike, I added in the line you requested as well.

**Comment by StevieBenton** [comment]
Just to confirm, this is now [live on Medium here](https://medium.com/mozilla-festival/the-makers-of-mozfest-spike-8cdd0e5cd4f6#.lf7mzef4u). 

Thanks for all input :)
