### ISSUE TITLE
Catering Supplier

### ISSUE THREAD

**Issue by marcwalsh** [MozillaFoundation/Mozfest2016_production#21]
Looking for a catering company to supply for 1600 people for lunch on Saturday and Sunday as well as canapes on the Friday night and Sunday night. 

- [x] Initial Research
- [x] Three Shortlisted Suppliers
- [x] Tasting Days Scheduled
- [x] Contract Drawn Up

**Comment by marcwalsh-zz** [comment]
Talking to Feast on Thursday AM to discuss options for this year.

**Comment by marcwalsh-zz** [comment]
Feast Contract is currently with Legal pending approval.

**Comment by marcwalsh-zz** [comment]
Will close as we're working with Feast and we're just in the process of making payment. 🍕
