### ISSUE TITLE
For review - View from the Fringe: Can Machines See the Invisible?

### ISSUE THREAD

**Issue by StevieBenton** [MozillaFoundation/Mozfest2016_production#212]
Hello everyone. 

Here's a draft write-up of Monday's fringe event at BCS. [Can machines see the invisible?](https://docs.google.com/document/d/1376EftOfiXW6Z-vXY0GmecsuOPt4WCbq4Eluhjl3kp0/edit?usp=sharing) The doc is open so please do take a look and edit / comment.

This was really fascinating if a bit complex. I think it could be really good fuel for discussion, especially around ethics and AI. The draft is also with the presenter, who is currently reviewing to make sure I have the technical elements correct.

When we are all happy I will publich on Medium.

Thank you!
cc @edrushka @KevZawacki @KGorr @HPaulJohnson

**Comment by KGorr** [comment]
Super interested read, @StevieBenton! Made some small suggestions. Nice job!

**Comment by StevieBenton** [comment]
Thanks @KGorr ! Was an incredibly thought-provoking session, so much to take in. There was loads more that could have gone in there but would have made the piece way too long. 

Dr Redi is happy with it too, she made a few tweaks but likes it.

Something that fascinates me is the different ways we seem to use commas - I always find things like that interesting!

**Comment by StevieBenton** [comment]
Hello folks, I've gone ahead and published. [You can see the piece here](https://medium.com/mozilla-festival/view-from-the-mozfest-fringe-can-machines-see-the-invisible-6ba5c8743d2e#.w0ptpa89a)

I'm really pleased with it, and it has definitely awoken my slightly dormant interest in the ethics of technology.
