### ISSUE TITLE
Speaker series graphics for twitter

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/Mozfest2016_production#213]
I stumbled across @HPaulJohnson and he mentioned that it would be nice to have an image for twitter to advertise each speaker or speaker series. Photo, name, title. Could be adapated from the [posters](https://redpen.io/p/om396ce7b3b9594de5) by @taisdesouzalessa. 

Installation is top priority Thurs & Friday. But, if there's an idle moment, this seems like a relatively easy and valuable asset.

@HPaulJohnson – can you describe what you imagine? One per speaker, or one per series?

cc @kristinashu

**Comment by taisdesouzalessa** [comment]
@xmatthewx tomorrow I will work on those. Today at the end of the day I sat with @kristinashu to see the plan for tomorrow and I'll help with installation in the morning and work on those Twitter assets in the afternoon. 

@HPaulJohnson what is the most important information you want to highlight for Social Media? I find it will be too busy if we add all the info we have in one poster inside a Twitter image... I was wondering if you could share here the goal want to achieve with those images so we choose the proper information to highlight.

Thank you

**Comment by taisdesouzalessa** [comment]
@xmatthewx and @HPaulJohnson here is the first template. Since we have limited space, I highlighted the most important info. If there is any additional info I would suggest to add to the tweet post in text form since they are clickable and we can link to, like the livestream link for instance. Please let me know what you think and I can work on the other 4 this afternoon.

![twitter-speaker-series1](https://cloud.githubusercontent.com/assets/22157921/19803611/72781152-9cbe-11e6-83e6-f02666bb2359.jpg)

cc: @kristinashu 

Thanks,

**Comment by HPaulJohnson** [comment]
Since we will likely be promoting these from both @mozilla and @mozillfestival accounts could we add Mozfest to the title, so "Mozfest Speaker Series"?

Otherwise these look great and I think we can go ahead and build the rest of the versions. 

Thanks!

**Comment by taisdesouzalessa** [comment]
@HPaulJohnson here are all the banners with the requested revision. Please let me know if you need any other revision done :)

Thanks!

![twitter-speaker-series1](https://cloud.githubusercontent.com/assets/22157921/19811290/8e409b30-9ce5-11e6-8ad8-69d52609120d.jpg)
![twitter-speaker-series2](https://cloud.githubusercontent.com/assets/22157921/19811291/8e420790-9ce5-11e6-86a3-10162f937b6c.jpg)
![twitter-speaker-series3](https://cloud.githubusercontent.com/assets/22157921/19811292/8e424ce6-9ce5-11e6-88d5-33de4ce74040.jpg)
![twitter-speaker-series4](https://cloud.githubusercontent.com/assets/22157921/19811288/8e3d5a4c-9ce5-11e6-8d6d-4e98cda83fa1.jpg)
![twitter-speaker-series5](https://cloud.githubusercontent.com/assets/22157921/19811289/8e3e2d50-9ce5-11e6-8430-7d6c11c05aa3.jpg)

cc: @xmatthewx @kristinashu
