### ISSUE TITLE
Draft for sign-off - piece about the ToDo installation

### ISSUE THREAD

**Issue by StevieBenton** [MozillaFoundation/Mozfest2016_production#215]
Hello everyone,

I've finalised the draft of the qrticle about the ToDo installation. [It's here](https://docs.google.com/document/d/1w34jgfl70y4_snsPyh_OrIT3ZB1K6kGWqreSxrZVsPo/edit?usp=sharing). 

Please do take a look and advise of any comments or issues. Would be great to publish this today!

Thanks all :)

cc @edrushka @KevZawacki @KGorr @HPaulJohnson

**Comment by StevieBenton** [comment]
Teaser video links

https://vimeo.com/189018091

https://vimeo.com/189274779

**Comment by KGorr** [comment]
Made some minor suggestions. So cool - sad I'm missing it!

**Comment by StevieBenton** [comment]
Thanks @KGorr ! Really helpful. I'm about to speak to the guys from Tate and V&A about MozEx but will look to publish afterwards.

**Comment by StevieBenton** [comment]
This is now live - https://medium.com/mozilla-festival/interactive-art-at-mozfest-experience-the-webs-key-issues-f22bbf627138#.i06ihatl8

If there are other thoughts or comments, please let me know as I can always go back and edit.
