### ISSUE TITLE
Add link to online Festival Guide

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Mozfest2016_production#221]
Guide is here:
- https://mzl.la/mozfest-2016
- https://mzl.la/mozfest-2016-wranglers

We could link to this from the site.

**Comment by kristinashu** [comment]
Since the website already has all the wrangler bios, we only need to link to the main Festival Guide.

I recommend we link from the ['What to Expect' page ](https://mozillafestival.org/expect). At the end of the last paragraph of the 'What is MozFest like?' section. 

Copy: "Read our Festival Guide." and the sentence links to https://mzl.la/mozfest-2016

![screen-shot-2016-11-08-at-9 47 02-am](https://cloud.githubusercontent.com/assets/1068783/20110422/2cfcc882-a599-11e6-926d-248936377858.jpg)

cc @xmatthewx @alanmoo

**Comment by xmatthewx** [comment]
This works. 

_What if_ we put a nice big photo of the guide below the text? Maybe with `View the Guide` overlay? Whole image as link.

I had hoped to just embed the issuu viewer, but looks like it requires flash.

**Comment by kristinashu** [comment]
@xmatthewx do you still want an image added?

**Comment by xmatthewx** [comment]
I think it'd be nice to help that guide live on. And also make this page more interesting. It's not crazy critical, and nobody will notice if we skip it, but it should be relatively easy and worth the wee bit of effort.

**Comment by kristinashu** [comment]
How about something like this? Where the image links to the guide.

![01](https://cloud.githubusercontent.com/assets/1068783/21329359/2645cd44-c5ed-11e6-853e-c9cf8289fa53.jpg)

Here's a jpg of the image:
![guide](https://cloud.githubusercontent.com/assets/1068783/21329388/4ba2e0ea-c5ed-11e6-896d-72a81783f4b5.jpg)

It could have a hover state like this, but that might be too much:
<img width="1092" alt="screen shot 2016-12-19 at 1 17 18 pm" src="https://cloud.githubusercontent.com/assets/1068783/21329435/86184cc4-c5ed-11e6-93d5-7bbeae542805.png">

**Comment by xmatthewx** [comment]
👍 – maybe @alanmoo or @mmmavis can implement if they have a quiet moment from other things.

**Comment by mmmavis** [comment]
I just merged the PR. Changes will be on production site soon.

**Comment by mmmavis** [comment]
https://mozillafestival.org/expect

**Comment by kristinashu** [comment]
Sweet, thanks!
