### ISSUE TITLE
Create title and end cards for D&D videos

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/Mozfest2016_production#227]
We're creating high-quality videos of each individual D&D talk.
Need a title card for each, and a single end card to use for all of them, using the MozFest 2016 branding.

**Title cards should say:**
MozFest 2016
Dialogues and Debates 
[speaker name]

**End card should say:**
MozFest
The world's leading festival for the open internet movement.
www.mozfest.org

**Specs**
1920x1080 
PNG format 

**Deadline**
Jan 13, 2017 please!

@Saallen @KevZawacki Any thoughts before I assign this to the design team?

**Comment by Saallen** [comment]
This seems like a very long title- Dialogues and Debates speaker series
can we reduce it to Dialogues and Debates ?

**Comment by KevZawacki** [comment]
@Saallen OK by me!

**Comment by edrushka** [comment]
Cool - I've made that update in the first comment.  Cc-ing @xmatthewx to assign.

**Comment by edrushka** [comment]
**List of speaker names:**
Zeynep Tufekci
Brian Behlendorf
Maggie Vail
Mark Surman & Mitchell Baker
Sahar Aziz
Katherine Maher
Chris Soghoian
Ashe Dryden
Volker Birk
Katharina Borchert
Simone Browne
Eliot Higgins

**Comment by xmatthewx** [comment]
@edrushka – this looks good. We should be able to recycle slides from the deck or stage/poster artwork to keep this quick and simple. 

Do you have dimensions?

@kristinashu, if you have some spare time this week, it'd be nice to knock this out before new projects get rolling in January (though it sounds like there's a bit of time then).

**Comment by kristinashu** [comment]
Here are some possible cards.

Intro without image:
![01a](https://cloud.githubusercontent.com/assets/1068783/21408173/5ffa5ffe-c788-11e6-8037-0f84247771b8.png)
Or intro with image:
![01b](https://cloud.githubusercontent.com/assets/1068783/21408172/5ff7d2d4-c788-11e6-8813-b1e26ca11cf1.png)
End card:
![02](https://cloud.githubusercontent.com/assets/1068783/21408174/5ffee4e8-c788-11e6-9b30-ca4d1a165749.png)

Let me know if these work for you and if you prefer image or no image. Then I'll add in all the other speakers.

**Comment by edrushka** [comment]
Thanks for mocking these up so quickly, Kristina. I think I prefer the version with the photo (I like that tiny splash of pink) but either version works for me. @KevZawacki? @Saallen?

**Comment by Saallen** [comment]
These look great! Thanks @kristinashu I prefer with Image :camera_flash:

**Comment by kristinashu** [comment]
Great! Here are all the speakers plus the end card: https://drive.google.com/open?id=0B2irLVDJivhLbVpVLTdfNjhsODg
