### ISSUE TITLE
Junior Designers

### ISSUE THREAD

**Issue by marcwalsh** [MozillaFoundation/Mozfest2016_production#23]
Junior Design contracted to complete work assigned under [Asset Review](https://docs.google.com/spreadsheets/d/1J4LS4ILtG5x-jxwHEwGuDzXHRHC9IQM4t9fg2OUeRBs/edit#gid=1773878800) 

- [x] Job spec drawn up - #11 #12 
- [x] Role advertised - #13 #45 
- [x] Shortlist three portfolios
- [x] Contract drawn up #59

**Comment by marcwalsh** [comment]
Here's a couple of recommended portfolios:

[Jessica Bird](http://youvebeenjessed.com/)
[Simon Allen](http://www.simonallen.eu/) 

I'll add more as I receive recommendations. 

@edrushka @xmatthewx Maybe we can have a call at some point soon and work out the SOW as well as a timeline for when we would need the designer to start. We could also use the time to go through the various portfolios.

**Comment by marcwalsh** [comment]
Another potential designer: [Thomas Walskaar](http://www.walska.com/index.html)

**Comment by marcwalsh** [comment]
Another potential: [Mark Forrest](www.markforrestdesign.com/)

**Comment by kristinashu** [comment]
Thanks for these @marcwalsh! 

I've stated a spreadsheet with a few notes and comments. Please add any thoughts you might have.

https://docs.google.com/a/mozilla.com/spreadsheets/d/1LS_rG6ulLF2_l9Iy9ViZx80h3SPfW3IKgfYaBibfY1o/edit?usp=sharing

cc @xmatthewx

**Comment by xmatthewx** [comment]
Everyone – Bobby is building a list of potential contractors and a refined system for engaging with them on projects. He's visiting this thread as an observer. 

@secretrobotron - We're specifically looking for a London based designer to handle production projects, starting with people connected to Ravensbourne. You can track our review of people in #47 to see if anyone might be useful for other projects post Mozfest.

**Comment by edrushka** [comment]
Bobby the observer.

![spy](https://cloud.githubusercontent.com/assets/4515662/17527097/d5410ef8-5e1e-11e6-81f9-1eb70dc99e43.gif)

**Comment by kristinashu** [comment]
@marcwalsh any luck scheduling an interview with Jessica? 

Could you also please share any portfolios you've received so far from the Ravensbourn posting?

**Comment by marcwalsh** [comment]
@kristinashu - I've added comments onto the portfolios as well as for Jessica.

**Comment by marcwalsh-zz** [comment]
@kristinashu - Jessica is currently working full time at an internship, so is unsure about time commitments. I'm gathering some more as well as doing some research into alumni that I can contact.

**Comment by marcwalsh-zz** [comment]
- [Nihal Shah 1](https://www.behance.net/Nihalshah) & [2](https://www.instagram.com/_BreakTheFoundation_/)
- [Oliver Jordan](http://www.oliverjordandesign.com/work)
- [Ed Yau](http://edwardyau.co.uk) - Ed is currently working full time however he has said he would pair with another freelancer who would be able to assist with the install. I have previously worked with Ed when I ran The Degree Show at Ravensbourne back in 2014.

**Comment by kristinashu** [comment]
Thanks, I've added them to the spreadsheet along with a few notes.

cc @sabrinang

**Comment by marcwalsh-zz** [comment]
@kristinashu Ed has proposed to work with [Carrie-Ann James](http://carrieannjames.com/) on the project. Would be great to get feedback on here also and if we would want to move forward with both of them.

**Comment by kristinashu** [comment]
Contractors would like more context about due dates so I've started adding some info (dates and any github tickets we have) to our Mozfest Design Assets 2016 doc https://docs.google.com/a/mozilla.com/spreadsheets/d/1P4co4m11LE7hNQoM3xf0AgSEcl9KY-lrqcU-xINWEq0/edit?usp=sharing 

@marcwalsh @edrushka @sabrinang please add any other info might have.

Also working on contract here https://github.com/MozillaFoundation/Mozfest2016_production/issues/59

**Comment by kristinashu** [comment]
Contracts have been sent to the contractors by Pamela!
