### ISSUE TITLE
Logistic Assistants Contractors

### ISSUE THREAD

**Issue by marcwalsh** [MozillaFoundation/Mozfest2016_production#26]
Require 2 logistic assistants for over the Mozilla Festival.

One person will be required to work the 1 or 2 weeks before MozFest as prep for supplies for spaces and sessions, as well as coordinating deliveries for them. Another Logistics Assistant will be required to worked from during the week of MozFest. End date will be the Monday after MozFest for get out. 

- [x] Job Spec drawn up - @Saallen to share asap
- [x] Job advertised
- [x] Shortlist
- [x] Contracts drawn up

**Comment by marcwalsh-zz** [comment]
Done!
