### ISSUE TITLE
Photographer Contractors

### ISSUE THREAD

**Issue by marcwalsh** [MozillaFoundation/Mozfest2016_production#27]
Team of photographers required for the event days from Friday - Sunday. Last the team was 1+2 working the full weekend.
- [x] Job spec and style requirements drawn up
  - [x] responsible @sallen / @edrushka #72 
- [x] Research into festival / event photographers
- [x] Portfolios shortlisted
- [ ] Contract drawn up

**Comment by marcwalsh-zz** [comment]
Awaiting quote from Paul Clarke, he's currently on holiday until next week.

**Comment by marcwalsh-zz** [comment]
Received quote OK, waiting for T&Cs and contract to sign.
