### ISSUE TITLE
Offering the call for proposals in different languages

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/Mozfest2016_production#3]
Off the back of MozRetreat many ppl requested the Call for Proposals to be translated into other languages such as French, Arabic and/or Spanish
In order for this work to happen some key management systems would need to be in place

* Where would the localised form be found from the English version?
* What languages would we accommodate?
* Would this localisation just be an offer for the Localisation call?
* Who would manage this on the back end of the google spreadsheet/github
 * if this was an offer to all spaces who would translate
* Would this session be on the schedule in its own language?

**Comment by edrushka** [comment]
done! See #2
