### ISSUE TITLE
Contract DBS Supplier

### ISSUE THREAD

**Issue by marcwalsh** [MozillaFoundation/Mozfest2016_production#30]
Electronic DBS checks required for staff and volunteer leaders in the Youth Zone. 

- [x] Supplier found and vetted
- [x] Security checks carried out on supplier
- [x] Contract agreed with Legal
- [x] Contracts signed

**Comment by Saallen** [comment]
Update- we have started the vendor review system again due to worries over the last vendor
We are now looking at Peoplechecker

**Comment by marcwalsh-zz** [comment]
Update - Matt W is now in contact with the new possible vendor and the check is in progress.

**Comment by marcwalsh-zz** [comment]
Privacy checks have been completed and passed. Passed to legal to sign off.

**Comment by marcwalsh-zz** [comment]
Contract signed by PeopleCheck and Mozilla Foundation. Uploaded to box. 

Closing... 🙌
