### ISSUE TITLE
Swag Master!

### ISSUE THREAD

**Issue by marcwalsh** [MozillaFoundation/Mozfest2016_production#32]
Main issue for all swag for the festival.

Required:
- [ ] Water Bottles - #33 
- [ ] Notebooks - #34
- [ ] Sharpie -  
- [ ] Lanyards -
- [ ] Clips -

**Comment by edrushka** [comment]
Hey! Would love to discuss swag and limiting our environmental footprint. See page 19 of the [Moodboards] (https://drive.google.com/a/mozillafoundation.org/folderview?id=0B2irLVDJivhLMnRqc0ZzX0NfTzQ&usp=drive_web&tid=0B2irLVDJivhLQkEtXzJodDhHSTA) that Sabrina and Kristina have been working on. Some of these options could reduce the need for water bottles, tote bags etc.

**Comment by edrushka** [comment]
@marcwalsh I booked a call on Thursday to chat about this.
