### ISSUE TITLE
Swag - Water Bottle

### ISSUE THREAD

**Issue by marcwalsh** [MozillaFoundation/Mozfest2016_production#33]
1600x water bottles required for swag bags. 

- [x] Design 
- [x] Supplier Found
- [ ] Sent to Print
- [ ] Proof Signed Off
- [ ] Delivery Date Agreed

**Comment by marcwalsh-zz** [comment]
Three options are available here: 

Similar to the 2014:
https://www.yourproductsbranded.co.uk/?q=flexbottle

Aluminum bottles:
http://www.totalmerchandise.co.uk/products/details/350ml-Aluminium-Sports-Bottles
or
http://www.totalmerchandise.co.uk/products/details/500ml-Aluminium-Sports-Bottles

**Comment by marcwalsh-zz** [comment]
Specs for this:
1 colour spot print
Print Area: 70mm x 30mm

**Comment by marcwalsh-zz** [comment]
This is also avilable in various colours:
Apple Green, Light Blue, White, Neon Pink, Neon Yellow, Red/Black, Blue/Black, Steel Blue, Silver

**Comment by kristinashu** [comment]
If we going with http://www.totalmerchandise.co.uk/products/details/350ml-Aluminium-Sports-Bottles then @sabrinang and I think we should go with the white bottle and teal logo. Here are a couple mocked up versions:

![waterbottle-01](https://cloud.githubusercontent.com/assets/1068783/18803442/ea064e80-81a4-11e6-93a3-ff8d08cf5534.jpg)
![waterbottle-02](https://cloud.githubusercontent.com/assets/1068783/18803441/ea04607a-81a4-11e6-86a7-f7f05a19c465.jpg)

**Comment by xmatthewx** [comment]
I love using just the logomark, without the words. While it might seem like it doesn't advertise the festival as well, it still serves as a conversation starter, which is the most important thing. 

@Saallen – What say you? Can we go with logomark alone? It's way more hip.

Beyond that, this is ready to ship.

**Comment by Saallen** [comment]
I also am a fan of the watermark- I am soo hip 👵

**Comment by kristinashu** [comment]
Great! @marcwalsh the attached folder contains:
- eps of the gear logo
- insitu mock up of logo on the water bottle
- color specs (should try to match Pantone Coated 333 C)

Using the specs mentioned above, the gear would be 30 x 30mm. It would be great if it could be a little bigger 50 x 50mm, but if not then 30 x 30mm is good.

[For print.zip](https://github.com/MozillaFoundation/Mozfest2016_production/files/514273/For.print.zip)

Files are also in Drive: https://drive.google.com/open?id=0B2irLVDJivhLcFdnNFk5MjFGV1k

**Comment by kristinashu** [comment]
@sabrinang just pointed out the gear icon was not at the proper angle. I've just updated the files above ^ to reflect how it should look:

![insitu](https://cloud.githubusercontent.com/assets/1068783/18885009/b26bf66c-849e-11e6-9659-6143604c8a9f.jpg)

**Comment by marcwalsh-zz** [comment]
Printing! 🍾

**Comment by sabrinang** [comment]
## Post MozFest Documentation

The white 350ml aluminium bottles with the teal mozest logo were available to take from the swag table.
![mozfest-documentation-water-bottles](https://cloud.githubusercontent.com/assets/2492510/20171131/2912676c-a6e4-11e6-85e0-8c838f875da3.png)
