### ISSUE TITLE
Swag - Notepads

### ISSUE THREAD

**Issue by marcwalsh** [MozillaFoundation/Mozfest2016_production#34]
1600x stationary sets / notepads etc. required for swag bags. 
- [x] Design 
- [x] Supplier Found
- [ ] Sent to Print
- [ ] Proof Signed Off
- [ ] Delivery Date Agreed

**Comment by marcwalsh-zz** [comment]
Notepads are available through two suppliers:
- [PixArt Printing](https://www.pixartprinting.co.uk/digital-litho-printing/office-products/customised-notebook/) - These have a full color print on the outside and then 90gsm ivory paper on the inside and are 60 pages and sewn bound. 
- Aspect Press (Local Printers) - Can print either stapled or sewn notepads.

Cost comparison spreadsheet link will be available in the #32

**Comment by sabrinang** [comment]
![dsc06685](https://cloud.githubusercontent.com/assets/2492510/18569783/c522d01c-7b59-11e6-9257-f40355c315fa.JPG)
An idea is to reduce having a separate notebook and to have blank pages incorporated in the festival guide to serve as a notepad. Alternatively, it could also work with the size of the festival guide size so it can be all kept together when clipped.

**Comment by kristinashu** [comment]
I echo that. I definitely like idea of having fewer loose pieces. But if we do want a separate notebook, we should just have something small like Field Notes which only has about 24 pages (which we could clip to the guide, as Sabrina mentioned).

<img width="238" alt="screen shot 2016-09-15 at 3 48 51 pm" src="https://cloud.githubusercontent.com/assets/1068783/18570074/f203dde0-7b5b-11e6-8432-9952eb290542.png">

@edrushka @marcwalsh what do you think?

**Comment by kristinashu** [comment]
As discussed in our stand, we're going to keep this swag.

I've opened a dedicated design ticket https://github.com/MozillaFoundation/Mozfest2016_production/issues/150 

@marcwalsh please add the deadline once you have it.

**Comment by sabrinang** [comment]
## Post MozFest Documentation

The A6 (10.5 x 14.8cm) notebooks are clipped to the festival guide/map accompanied with a sharpie. It has 60 pages of 90gsm ivory paper sewn bound with yellow thread.

![mozfest-documentation-notebook](https://cloud.githubusercontent.com/assets/2492510/20171926/c62eddf2-a6e7-11e6-80dc-7501d268687b.png)
