### ISSUE TITLE
Swag - Something Special

### ISSUE THREAD

**Issue by marcwalsh** [MozillaFoundation/Mozfest2016_production#35]
Are we including an extra gift in this year's bag?

- [ ] Sponsored gift - Contact potential sponsors.
- [ ] Design 
- [ ] Supplier Found
- [ ] Sent to Print
- [ ] Proof Signed Off
- [ ] Delivery Date Agreed

**Comment by kristinashu** [comment]
Closing this ticket. If anything pops up in the future, we can open a new ticket.
