### ISSUE TITLE
Swag - Lanyards

### ISSUE THREAD

**Issue by marcwalsh** [MozillaFoundation/Mozfest2016_production#36]
2000 lanyards required for the entire weekend. 

- [x] Check to source internally
- [x] Supplier Found
- [x] Delivery Date Agreed

**Comment by kristinashu** [comment]
The only design needed is to chose a color. Is that right?

**Comment by marcwalsh-zz** [comment]
@kristinashu - Yes it is, we're going to try and see if we can source these for free from somewhere in MoCo or MoFo also.

**Comment by SpikeUK** [comment]
Can we please be sure that whatever lanyards we get they have the safety break option.
Spike (with his Health and Safety hat on)

**Comment by marcwalsh-zz** [comment]
@SpikeUK - Of course, this is something that I'd expect as standard. 

@kristinashu - just FYI we have left over yellow lanyards that we used as the 'No Photo' option last year, so if we can avoid something close to that it would be great!

**Comment by SpikeUK** [comment]
@marcwalsh I am sure that was the case Marc, I thought it worth documenting for the avoidance of doubt ;-)

**Comment by kristinashu** [comment]
This year we will have two attachment points at the top, so they don't flip. Because of this, we will need to order new yellow lanyards.

Linking name card design ticket to this one: https://github.com/MozillaFoundation/Mozfest2016_production/issues/148

**Comment by marcwalsh-zz** [comment]
Ordered! 💅🏼

**Comment by sabrinang** [comment]
## Post MozFest Documentation

Blue lanyards with 2-point metal swivel lobster clasp style clip were the main style. Yellow lanyards were used to indicate they did not want photo/video taken of them. Both lanyards have a safety release in the center.
![mozfest-documentation-lanyard](https://cloud.githubusercontent.com/assets/2492510/20187514/67839170-a729-11e6-957e-9cdb1deffde5.png)
