### ISSUE TITLE
Swag - Swag Bags

### ISSUE THREAD

**Issue by marcwalsh** [MozillaFoundation/Mozfest2016_production#37]
1600 swag bags required for the weekend.

- [ ] Design 
- [ ] Supplier Found
- [ ] Sent to Print
- [ ] Proof Signed Off
- [ ] Delivery Date Agreed

**Comment by edrushka** [comment]
@marcwalsh have we determined for sure we won't have these, or are they still a maybe?

**Comment by marcwalsh-zz** [comment]
@edrushka - I'd like to avoid it, having the 'pack' like in the original moodboard I feel is a lot nicer and something different.

**Comment by edrushka** [comment]
OK. I will close this and remove it from the assets spreadsheet. We can re-open if plans change.
