### ISSUE TITLE
Thursday Night Venue

### ISSUE THREAD

**Issue by marcwalsh** [MozillaFoundation/Mozfest2016_production#38]
Looking for a historical / arts venue in London to host around 150 people. 
- [x] Research 
- [x] Shortlist three venues
- [x] Contract signed
- [x] Confirm drinks order
- [x] Confirm catering requirements
- [x] Music / DJ booking

**Comment by marcwalsh-zz** [comment]
A venue tracker is available [here](https://docs.google.com/a/mozilla.com/spreadsheets/d/1oF1jPNi12txl_hVPE14X-kt1puqkT9GlrES_7f3QJnE/edit?usp=sharing)...
