### ISSUE TITLE
Session format question addition 

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/Mozfest2016_production#4]
New question to be added around session formatting-

Aim- to provide clarity around the type of session or workshop being submitted.
        the facilitator submits their session highlighting the designed format of their session
        this provides the Space Wrangler information on how how long the session should be, its intended format and by choosing the type of format earlier in the process the SW can design their space format and timings alot earlier

Potential question format:
**Please choose the format and/or timings you think most suits your proposal-**
Demo- short showcase of your work or teachings
Learning lab- session format where audience are involved in both listening and making components
Fireside chat - talk format with q&a session within, normally 45mins- 1 hour
Design sprint-  long workshop building and hacking

**Comment by edrushka** [comment]
Done! Final wording reads:

MozFest accepts many different session formats. What do you think would work best for your session? (you may select multiple formats) *
Demo or Lightning talk - 5-15 minute showcase of completed work or product
Learning Lab - 60 minute hands on skillshare or small group discussion (technical or other)
Fireside chat - 45 minute talk with time for questions and answers
Hands-on workshop - 1-3 hours for hacking, making, designing or producing a 'thing'
Game
I am not sure
Other
If you chose "other" above, please outline why.
