### ISSUE TITLE
Mozfest website onboarding for engineers

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Mozfest2016_production#43]
@mmmavis to onboard @alanmoo so that we can distribute responsibility for the site!

**Comment by alanmoo** [comment]
@mmmavis I'm pretty sure we've got this covered, right? Unless there's any other special things I need to know.

**Comment by mmmavis** [comment]
@alanmoo yup yup! Thanks @alanmoo 👍 If we need to remove proposal related code I'm happy to do that / help since that chunk of code is not that well organized 😅

**Comment by alanmoo** [comment]
I'm not concerned about that-we might need it again next year
