### ISSUE TITLE
Choose a theme!

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Mozfest2016_production#44]
We need to choose a theme that can be shared with attendees, and used to inform event and production design. (For reference, last year's theme was "Shape the Web.")

**Comment by edrushka** [comment]
cc @KevZawacki and @KGorr - I'll book the 3 of us a block to brainstorm!

**Comment by Saallen** [comment]
👍

**Comment by edrushka** [comment]
Here's a brainstorming doc: https://docs.google.com/document/d/1mE8CO4h4BsMvssFqMps3BGKQYrQt8jReyg4DR1di3nM/edit

**Give us your best 3-5 word tagline for MozFest 2016!**

cc @Saallen @chrislarry33 @HPaulJohnson @brettgaylor @ldecoursy

**Comment by ldecoursy** [comment]
Added a few ;)

**Comment by edrushka** [comment]
Closing, as we have chosen 'One Web'.
