### ISSUE TITLE
Write junior designer job description

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/Mozfest2016_production#45]
Based on the Scope of Work in #12, I've done a first draft of the job description.

@xmatthewx @kristinashu can you review? Then we can hand to @marcwalsh to post at Ravensbourne.

https://docs.google.com/document/d/1pEUAf8jzXdIJEV2MEYrS5krlLflWSbbtVCLJRqQStDE/edit#heading=h.lkbglj5wd9fx

**Comment by kristinashu** [comment]
Looks great to me!

**Comment by edrushka** [comment]
I'll bring this up in today's stand, but I've incorporated all the feedback so it looks like we're almost good to go. If anyone has further thoughts, weigh in now!

**Comment by edrushka** [comment]
@marcwalsh We're ready to post this. Deadline for applicants is August 12, but we'll review as they come in (i.e. don't wait until the deadline to apply). Need a brief CV and link to portfolio.

Thanks!

**Comment by xmatthewx** [comment]
Job description done. Yay.

**Comment by xmatthewx** [comment]
@secretrobotron for your reference. contractor job description finessed by Erika based on the one i did for our full time design job posting.
