### ISSUE TITLE
Change template message for new issues

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/Mozfest2016_production#46]
On the Program 2016 repo, please change the template when people create new issues to:

**The call for proposal is now closed.** 

Please do not submit new session proposals directly through Github as they will not receive the unique identifiers required for the curation process and inclusion in the final schedule. 

Please contact the festival production team at festival@mozilla.org if you have questions. 

Thanks!

**Comment by edrushka** [comment]
cc @marcwalsh @Saallen will this do? Let me know and I'll assign to Mavis.

**Comment by Saallen** [comment]
That looks great to me
S

**Comment by edrushka** [comment]
@mmmavis can you change the template when you have a minute? Thanks!

**Comment by mmmavis** [comment]
Done! https://github.com/MozillaFoundation/mozfest-program-2016/issues/new 🌹
