### ISSUE TITLE
Scope of work for Live streaming

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/Mozfest2016_production#48]
Scope of work for live streaming in the  Dialogues and Debates rooms

Responsable folks are @KevZawacki with support from @marcwalsh 
Mark has started and will upload here asap

Responsable for scope of work for post production work by this broadcaster is @edrushka 

Please keep @edrushka  & myself in theda loop

**Comment by edrushka** [comment]
I'll assign myself here as well. Meeting with MoCo for an exploratory discussion on where the videos might eventually live, which may influence this scope of work.

**Comment by Saallen** [comment]
Beautiful

**Comment by edrushka** [comment]
@KevZawacki I'm helping Marc scope this in more detail so we can approach contractors. For the live-streaming element (not the archived videos), do we want to live stream on Facebook, or just on the MozFest website? I don't think we came to a firm decision in the meeting with Moco.

**Comment by KevZawacki** [comment]
@edrushka Facebook as option 1, since we have the largest audience there. I believe the tool we'd use is Facebook Live.

YouTube or our website as back-ups.

**Comment by Saallen** [comment]
Hey pinging @marcwalsh for update regarding shortlisting contractors- any movement?
@edrushka & @KevZawacki did you talk to MoCo?

**Comment by KevZawacki** [comment]
@Saallen We did. My impression was that they can help market / promote the video segments in the months afterward, but can't do much in terms of A/V support on the ground.

Does that sound right, @edrushka?

**Comment by edrushka** [comment]
I think we may be talking about different MoCo teams 😁  Yes, my understanding is that the marketing team (Greg, Janice etc) will not offer support on the ground. Sarah is working with the MoCo A/V team, who may be able to help.

**Comment by KevZawacki** [comment]
Oops, pardon my above confusing comment. Deleting...

**Comment by edrushka** [comment]
Closing as I believe we'll be working with MoCo here.
