### ISSUE TITLE
Build video brief for videographer team

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/Mozfest2016_production#49]
Brief needed for Video for 2016

- [ ] Share the MozFest story
- [ ] Key elements to capture
- [ ] Updated look from 2015
- [ ] Use as pitch reel

cc @edrushka

**Comment by edrushka** [comment]
Going to put a due date of Aug 19 for a first draft on this, assuming I can connect with Mark S before then.

**Comment by Saallen** [comment]
@edrushka  Do you want last years brief to help form the new one for Dosed?

**Comment by edrushka** [comment]
I've got it already! 

Waiting until we have the MozFest website chat with Mark next week before I start work on this.

**Comment by marcwalsh** [comment]
@Saallen @edrushka - Would it be worth looking into other ways to tell the story apart from just a highlights video. Maybe one per day, or also some 15 second clips / mini-interviews that we can drop throughout the push for 2017?

**Comment by edrushka** [comment]
Absolutely, yes. I don't think we can simply repeat what we've done in years past, given than changes are afoot for the festival. Let's have a chat about fresh ideas before we draft the SOW.

**Comment by edrushka** [comment]
Update: not planning to shoot a promo video at MozFest this year, so SOW will be much less. Visual highlights and some interviews. Just waiting for Sarah to get back from PTO to confirm.

**Comment by edrushka** [comment]
2nd Update: after much discussion, we are re-visiting the idea of a promo video. A few notes:
- should capture the diversity of the festival
- should highlight the wild and wonderful types of sessions and interactive pieces.
- could focus more on images/sounds and less on talking 
- could draw inspiration from [Maker Faire videos](https://www.youtube.com/user/MakerFaireVideo)

@marcwalsh if you have any further info on Dosed's idea, please share!

**Comment by edrushka** [comment]
Closing as we're underway! I've met with Dosed two times and we have a plan of action to do a documentary style video this year. "Characters" have been shortlisted. I'll file follow-up tickets if needed.
