### ISSUE TITLE
Feedback on " What to expect " Page

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/Mozfest2016_production#5]
As my driving topic for comversation is the festival currently, a lot of people are giving me feedback around the festival and the website. One piece has stood out and been highlight from two different sources

- What to expect page- this page does not actually tell the reader what to expect when attending the festival- it does not tell the reader
- [ ] About format- what you will see when you walk in the door- no info about talks or interactive sessions
- [ ] that you can submit sessions to be part of the schedule
- [ ] What are spaces and why are they important?

@edrushka this is valuable feedback and something I think we should critically look at for the festival website

**Comment by edrushka** [comment]
Good feedback. I added to the specific ticket: https://github.com/MozillaFoundation/2016.Mozillafestival.org/issues/7

**Comment by edrushka** [comment]
Copy on both the 'what to expect' and 'about' pages were revised to offer more detail.
