### ISSUE TITLE
Space Considerations for D&D

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/Mozfest2016_production#51]
There will be 15 speakers over 5 events between 40-60 mins in lenght

* Video format to be slick and thus large production elements
* Taking place in an intimate space but one that is visable and open
* Sense of ambiance, drawing participants in through curosity rather than broadcast
* Allowing for noise to filter out attracting people in
* 50-100, but with no more than 70 seated

**Comment by edrushka** [comment]
Based on convo with Mark and Sarah's Aug 5 email, we'll develop a two-option proposal for Mark offering a) Walker Space and b) a more intimate classroom space for 30 participants.

Other elements to potentially incorporate:
- part of Todo's installation
- live broadcast around London

**Comment by edrushka** [comment]
Closing, as we have decided on Walker Space.
