### ISSUE TITLE
Create list of github handles for all Space Wranglers

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/Mozfest2016_production#54]
Doing this here in a locked GDoc for privacy. We can use this doc later to build out the SW bios. Ping if you need access.

https://docs.google.com/spreadsheets/d/100wmCld-YGysLHCpzYgovwctJkezPqQgFcOJ65mjyUk/edit#gid=0

@Saallen there are a number missing. Can you help track these down before the next SW call? cc @marcwalsh

**Comment by Saallen** [comment]
hEY @edrushka 
everyone on this list has been asked to send over their github names so if we dont have them they choose not to send them as they are not on github or are not part of the curation piece
I did notice one or two folks who I know do have handles so will  ping
