### ISSUE TITLE
List key milestones that will affect design

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/Mozfest2016_production#55]
@Saallen @marcwalsh This is rough. Please help me build out so we can share with design team, as they have requested this.

Aug 1 - Call for proposals closes

Aug ? - Wrangler bios due for festival guide

Sept - Curation closes

Sept ? Physical spaces assigned in Ravensbourne

**Comment by Saallen** [comment]
Hey

Aug 1 - Call for proposals closes

Aug 31st - Wrangler bios due for festival guide

Sept 5th - Curation closes and list of facilitators available for festival guide if needed

Physical spaces assigned in Ravensbourne- We need to understand each each Spaces requirements and session numbers before we allocate. Then we fit our production elements around these allocations, then tempory installations. This is really hard as a lot is still moving until right up to the festival.
I realise this is not helpful for designing but if we could create assets that dont rely on assigning spaces to definite floors  or where we can write in the floor number as 2014.
