### ISSUE TITLE
Scope printed Festival Guide

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/Mozfest2016_production#58]
We need to discuss content, which will determine format.

Kickoff meeting booked for Thursday Aug. 11

**Comment by xmatthewx** [comment]
Dates that impact design:
- Aug 1 - Call for proposals closes
- Aug 31st - Wrangler bios due 
  - approximate number of wranglers?
  - details we might include in guide?
- Sept 5th - Curation closes and list of facilitators available
  - approximate number of facilitators?
  - details we might include in guide?
- Mid October - physical spaces assigned
  - Too late for guide

**Comment by edrushka** [comment]
Here are all the wranglers' details: https://docs.google.com/spreadsheets/d/100wmCld-YGysLHCpzYgovwctJkezPqQgFcOJ65mjyUk/edit#gid=0  There's 32 of them.
Approximate # of facilitators is 300-350
Not sure what details we'll include in the guide. Will scope that in Thursday's meeting.

**Comment by edrushka** [comment]
Content has been scoped here: https://docs.google.com/document/d/1Cz3kZSrwmvnaO8GDlTl8VTcvPjZ4TmjfVvaul8rhOvQ/edit#
