### ISSUE TITLE
Identify a list of 500 “must-have” influencers to invite

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/Mozfest2016_production#62]
Create a list of 500 "must-have" influencers to invite to the festival. 

Need:
- [x] media suggestions from @KevZawacki 
- [x] festival partner suggestions from @Saallen 
- [ ] crowd-sourced suggestions from hubs

Then we'll reach out with personal appeals via email and social.

**Comment by edrushka** [comment]
Checking in on this. @KevZawacki are you on track to deliver the media suggestions by end of week? @HPaulJohnson can you draft a crowd-sourcing ask for the hubs? There's an MLN call this Thursday, so would be good to add it to the agenda cc @ldecoursy

**Comment by KevZawacki** [comment]
@edrushka Yep, I can build a London media influencer list before EOD Friday.

@HPaulJohnson MoCo's EU comms team would have great ideas to contribute, too. But, we're asking a lot of them right now for copyright -- I'm hesitant to add another ask. Once we're into mid-September, we should loop them in.

**Comment by edrushka** [comment]
Sarah's festival partners list: https://docs.google.com/spreadsheets/d/1QcoqOiMa_z8AcCuJaUgLNNC-xeVWbbXImg2yWvS-ugY/edit?ts=57ae0f1a#gid=0

**Comment by HPaulJohnson** [comment]
Created a spreadsheet (currently empty) where we can start compiling this list: 

https://docs.google.com/a/mozilla.com/spreadsheets/d/1XFZtwqQy_Eo2CRaNbC4pMiMUPPIAadq76YGhkoqnCJ4/edit?usp=sharing

We can share this with MLN on weekly call and then I will compile everything into a single list. Might need one additional week to crowd source enough names.

**Comment by KevZawacki** [comment]
@HPaulJohnson @edrushka Media contacts added to Paul's spreadsheet. Mostly UK-based, with a few journalists from Germany, France, Ireland and Spain who might be up for the trip.

**Comment by edrushka** [comment]
@HPaulJohnson if you have an ask for the MLN team re: influencers to invite, we can email them. Should specify that they can email personally if they don't want to add the email to our spreadsheet.

**Comment by edrushka** [comment]
Update: 
This week, Paul will:
1) draft an invite for influencers
2) send an email to mln@ crowd-sourcing influencers from hubs. 

Next week we'll:
- investigate using a service that scrapes Twitter for keywords relating to our 5 issues (I didn't explain this well, Paul has more details). 
- compare our list with Rizwan's to ensure we haven't left anyone out
- finalize our list

Following week we'll start sending invites.

**Comment by KevZawacki** [comment]
Re: scraping Twitter, I built some [detailed Sprinklr dashboards](https://docs.google.com/document/d/1Tj3Pylsvs9DZcf-qr3CP0XF9vBPeEXYigTzbA5nkqvU/edit) that provide real-time key issue insight. 

We could use these to identify possible influencers. For example, our Privacy & Security dashboard tells us the most influential individuals talking about that topic on Twitter are Cory Doctorow, Glenn Greenwald, Marc Andreessen, and Wil Wheaton.

**Comment by Saallen** [comment]
Hey  @edrushka on this plan is there a timeline for blurb for key partners to start emailing their networks?
I have started to get requests.

**Comment by edrushka** [comment]
@HPaulJohnson can you paste your invite text?

**Comment by HPaulJohnson** [comment]
@KevZawacki was nice enough to crank this out for me today. copy here: 

https://docs.google.com/document/d/1c-kf5IwBU5okzKlQyCfpNBWQ0z8Tsd6FkDD-aa3gV74/edit

**Comment by edrushka** [comment]
Thanks Kev. @Saallen will this work for your list of invitees?

**Comment by Saallen** [comment]
Been thinking @HPaulJohnson the other folks we should be inviting this year are potential sponsors for next year - who do we think could be the key leaders here, the opportunity for potential funders to see the value and the access they would get

**Comment by HPaulJohnson** [comment]
update: @KevZawacki and I will be sending out all the invites on Monday (Monday better than end of week for getting their attention). We have a few hundred to invite via email and then I'm going to supplement with some direct messages on Twitter to an additional 50-100 top influencers.

@Saallen if you have a list of potential sponsors you want us to contact please let me know.

**Comment by edrushka** [comment]
Can we close this, @HPaulJohnson , or are we still adding to this list?

**Comment by HPaulJohnson** [comment]
We can close. Still doing some adhoc messaging on twitter but for all intents in purpose this is wrapped.
