### ISSUE TITLE
Map post-festival emails 

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/Mozfest2016_production#64]
As part of the [Marketing Plan](https://docs.google.com/document/d/18F6tazG8I1b5CZz38EWxYBEZKmzTTk2X7KNFEAihgm4/edit), let's map out what emails should be included after the festival ends.
1) email to all attendees celebrating the weekend and thanking them for participating (sent Sunday night or Monday)
2) a survey of the experience 
3) content from the festival they may have missed, like D&D videos 
4) a CTA to get/stay involved with MLN in some ongoing way.

Anything else that should go in here @Saallen @KevZawacki @HPaulJohnson @KGorr

**Comment by Saallen** [comment]
For me on the most important pieces will be the stay involved. We will be creating a way to share projects and notes- yet to be confirmed but here is the best place to encourage the participation, ongoing connections and continued sharing- 
Folllowing SRCCONS example I would also love to encourage sharing of blogs, write ups notes etc
SRCCON text

> Please share your slides, link lists, notes, and all else related to your SRCCON experience here: https://public.etherpad-mozilla.org/p/SRCCON2016-onward
>     (We're working on this, too, but would love a hand with collecting things.)
> 
> Lastly (and this is a little more time-intensive):
> 
> ```
> We're seeking writeups about SRCCON, for Source, the publication of OpenNews. It's a chance to synthesize and share some bigger lessons, or to recap sessions for those who missed them. Send a heads-up about what you'd like to write at source@opennews.org. More details.
> ```

**Comment by KevZawacki** [comment]
This list looks good to me. @KGorr, want to add these to our email calendar document?

**Comment by KGorr** [comment]
Great! Added to the email calendar [here](https://docs.google.com/spreadsheets/d/1GLRzGDa2EDVhcdcTGpNmHlY12CrPk88Skl7ybUrxIrY/edit#gid=1086948807). I added send dates, but feel free to suggest other times.

**Comment by edrushka** [comment]
@KGorr when does it make sense to start drafting these? The survey, in particular, would be good to have ready well in advance but my goal would be to have everything sent in the 4 weeks after the festival written and approved ahead of time. Traditionally, everyone collapses for a while after MozFest, plus the production team takes some time off. I realize August is a bit early ;) so just let me know what makes sense and I can add to our production calendar.

**Comment by KGorr** [comment]
@KevZawacki and I discussed it this morning. It's on our to-do list for October. Does that work for you?

**Comment by edrushka** [comment]
👍
