### ISSUE TITLE
Session timings 

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/Mozfest2016_production#70]
**Saturday**
- 9:00-9:30 main stage
- 10:00 -11:00 Session 1
- 11:15- 12:15 Session 2 and D&D 1
- 12:30 -13:30 Session 3
- 12:00- 14:00 Lunch
- 13:00 - 13:45 Sessions 4 and D&D 2
- 14:00-15:00 Sessions 5
- 15:15- 16:15 Sessions 6 and D&D 3
- 16:30- 17:30 Sessions 7
- 18:00 Evening activities begin

**Sunday**
- 09:30 - 10:45 MozFest Breakfast
- 11:00 - 12:00 Session 8
- 12:15 - 13:15 Session 9 and D&D 4
- 12:30 - 14:00 Lunch
- 13:00 - 13:45 Session 10
- 14:00 - 15:00 Session 11 and D&D 5
- 15:15 - 16:15 Session 12
- 16:30 - 17:30 Sessions 13
- 18:00 - Closing Demo Party 

Note: These are start times. Sessions can go longer than 1 hour, but all sessions will start at one of these times.

**Comment by edrushka** [comment]
Updated Sept 16

**Comment by KevZawacki** [comment]
@edrushka May want to update times above. 

Saturday, 13:00 - 13:45 Sessions 4 and Lunch cont. --> Saturday, 13:00 - 13:45 Sessions 4 and Lunch cont. + D+D

**Comment by edrushka** [comment]
Updated Oct 4

**Comment by edrushka** [comment]
Refer to festival guide for timings.
