### ISSUE TITLE
Create scope of work for Photographer

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/Mozfest2016_production#72]
We are going to use Paul Clarke once again as our photographer for MozFest

@edrushka can you please review scope of work from 2015 and let @marcwalsh know if there are any updates required. cc @marcwalsh 

**Overall package -** 
Full coverage of festival over the three days
providing any post-shooting selection and editing 
Includes additional photographer
Uploading of photographs under creative commons licensing to MozFest Flickr account

**Art Direction**
Variety of photo compositions. Some where the subject is dead center, some where it is off to the sides, some where it is horizontal in a line or toward the tops and bottoms of an image. (This will provide us with assets we can use in a variety of positions and layouts in our web and print design work)
Large-scale views of the event (room- and venue-wide buzz and activity) as well as smaller moments (hands making things, etc) 
Participatory learning: people learning together in circles or other group activities
Volunteers helping people
Shots grouping people of varieties of age, gender, ethnicity.
Shots that capture moments of celebration, excitement.
Shots that give a sense of different types of sessions.
Portrait capture for The State of the Web

Copyright and Privacy issues
The photographer/s will acknowledge the No photos lanyard and ensure that group shots are kept to a minimum. 

The finished photos will have a Creative Commons Attribution Share Alike (BY-SA) license and shared onto our Mozfest Flickr account. (not Mozilla EU)

**Comment by marcwalsh-zz** [comment]
@edrushka and @Saallen - I've copied the 2015 scope of work into a new document, do we all want to suggest edits on there. 

I'll share you in on it now.

**Comment by edrushka** [comment]
I reviewed this. It looks good.

**Comment by SpikeUK** [comment]
I am hopeful of having a photographer as a Local Volunteer too. I have asked her if she could focus (see what I did there?) on capturing pics of volunteers if possible but there may be some overlap with what Paul will be doing.

**Comment by edrushka** [comment]
Is this done @marcwalsh? Can we close?

**Comment by edrushka** [comment]
Need to add:
- D&Ds - document stage and portraits of speakers
- TODO installation - people interacting with them, plus the installations themselves
- Anagram - elements integrated in the festival during Saturday daytime, theatrical elements on walk to venue, beginning of party

**Comment by edrushka** [comment]
Can we close this @marcwalsh - Paul's contract has been signed, correct?
