### ISSUE TITLE
Firefox tile for MozFest.org

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/Mozfest2016_production#73]

**Comment by marcwalsh-zz** [comment]
If it's possible again this year, I can't see why not. I'm sure it boosted visitors massively when I looked on ti.to after it went live last year!

**Comment by marcwalsh-zz** [comment]
@Saallen is looking up last year's info for this

**Comment by Saallen** [comment]
Got it 🎏 
There will be no impressions or click data but we can send over the design and Jean will help us out.
Specs required outlined below
[Partner_Specs_Directory_Tiles.pdf](https://github.com/MozillaFoundation/Mozfest2016_production/files/445644/Partner_Specs_Directory_Tiles.pdf)

**Comment by Saallen** [comment]
Week of the 12th of Sept required for a tile is
- [ ]  Creative- do we want to just use the banner for this year
- [ ] Time line for the tile- I am recommending a month pre festival
- Is this something we added into the designers scope of work? @kristinashu 
  cc @edrushka

**Comment by marcwalsh-zz** [comment]
@Saallen @edrushka - Looking at the specs there's a possibility of having the tile localised also.

It would be great if we were allowed to have a tickets CTA pre-festival and then a new tile over festival to push the stream of D&D.

**Comment by marcwalsh-zz** [comment]
@xmatthewx @kristinashu - is this something we could assign to the contractors? It massively pushed ticket sales last year so it would be great to get this up again as soon as possible.

**Comment by xmatthewx** [comment]
Let's do this in-house. Should be quick and easy and contractors have plenty on their plate right now. Do you agree @sabrinang? Tile specs are in comment above. (This shouldn't bump Gigabit work – we could prep this Friday or Monday.)

**Comment by marcwalsh-zz** [comment]
@xmatthewx @sabrinang - Just wondering if there's been any progress here, we'd like to get the process in motion as soon as possible to make sure it's get the most exposure possible.

**Comment by kristinashu** [comment]
I can do this asap!

**Comment by marcwalsh-zz** [comment]
Last year's artwork:
https://drive.google.com/open?id=0B20-0lpP23c0aVlIN3V1OHNYRjg

**Comment by kristinashu** [comment]
Thanks @marcwalsh! Here's a quick mock up. The Feature tile is similar to last year's and then the rollover state shows our 'one web' theme. @edrushka @KevZawacki let me know if you have any other copy suggestions or if we want localized versions. 

<img width="580" alt="mozfest_styletiles_01-01" src="https://cloud.githubusercontent.com/assets/1068783/18795536/e4aaa132-8179-11e6-92f6-df8d7fa3f31e.png">
<img width="580" alt="mozfest_styletiles_01-02" src="https://cloud.githubusercontent.com/assets/1068783/18795537/e4b2e298-8179-11e6-874d-d8df439ce3db.png">

**Comment by KevZawacki** [comment]
This looks great, @kristinashu! 

I recommend changing the copy in the first one to "Grab tickets to MozFest."

**Comment by kristinashu** [comment]
Much better! 

<img width="580" alt="tiles_01-01" src="https://cloud.githubusercontent.com/assets/1068783/18802319/ea999cce-819c-11e6-9f40-530089806e93.png">

**Comment by KevZawacki** [comment]
@kristinashu Perfect!

**Comment by kristinashu** [comment]
What's the next step with this? 

cc @edrushka

**Comment by xmatthewx** [comment]
@KevZawacki - is it possible to A/B test "One Web" vs Mozfest or Mozilla Festival as the primary clickbait?

These look really good. Keep in mind that tiles appear with half the width and height as the mockup above. Little logo is okay, but it likely distracts more than it strengthens our CTA to the passing glance of a busy firefox user. 

<img width="290" alt="tiles_01-01" src="https://cloud.githubusercontent.com/assets/1068783/18802319/ea999cce-819c-11e6-9f40-530089806e93.png">

**Comment by edrushka** [comment]
Has anyone already been in touch with the MoCo snippet team about this? @marcwalsh @Saallen?

**Comment by Saallen** [comment]
Yup- jean is waiting on us

Sarah Allen

Events Manager and Mozilla Festival Producer
Mozilla Foundation

Find out more about MozFest https://mozillafestival.org/ and follow the
conversation on twitter https://twitter.com/mozillafestival?lang=en-gb

**Comment by KevZawacki** [comment]
@xmatthewx Not sure if we A/B test homepage tiles. @HPaulJohnson, do you know?

**Comment by HPaulJohnson** [comment]
Hi all- not sure exactly what site this is for but things have changed for both directory tiles and mozilla.org in the last six months so I don't think either of these is an option for promotion at this point. 

Directory Tiles - which showed up on the new tab in Firefox - were discontinued late last year and therefore don't support this type of promo any longer. 

Mozilla.org - recently a bunch of design tests occurred and the new version has been rolled out within the last few weeks. If you haven't seen it yet, you will shortly. It also has a far different design and the standard moz.org promotional tiles no longer exist. There are few links that we could consider requesting updates to, most notably the one that says "Teach the Web". Take a look and see if that's something you might want use for Mozfest instead. 

The main channel for FF promos is now snippet. Not sure if we've used this for Mozfest in the past - it's kind of a blunt instrument for this type of promo. Looking forward is sounds like activity stream will be replacing a lot of the snippet and new tab real estate and there will be space there to promote things like Mozfest in the future; that's coming in 2017 as I understand it.

**Comment by Saallen** [comment]
Hey, I spoke with Jean in Aug and got this reply "We have default tiles in place and haven't touched them in awhile because metrics have been turned off by the product team. But that's not to say we can't help you get a tile in there for a short time period if you don't mind not having impression or click data" I just pinged her again for an update and hopefully next steps

**Comment by Saallen** [comment]
Updates from Jean on the tile 
Where do we want this? I have said global, which means the click through should be to home page rather than ticket page- but it means when the festival is live it shows the D&D videos
Do we want this localised? if yes, it will take a bit longer to initiate as we need to localise the tile and the title of the tile
We cannot track impressions but we can tag clicks - how do we want the click tagged?

Format for tile is : 580 x 360 pxl
URL-https://mozillafestival.org/

**Comment by kristinashu** [comment]
Here are the two images (feature and hover) at the requested dimensions:
[PNGs.zip](https://github.com/MozillaFoundation/Mozfest2016_production/files/503389/PNGs.zip)

If we want to localise, let me know the translations and I will update the comps.

**Comment by Saallen** [comment]
Thanks @kristinashu 💐 
I think we should localise as we are pushing for this in other areas
cc @edrushka @KevZawacki @HPaulJohnson

**Comment by edrushka** [comment]
I recommend we just submit the EN version for now. The window for buying tickets is very slim.

We only have an informal mechanism process on our end (through Heather and her network) and I have no idea how long it will take.

**Comment by Saallen** [comment]
And we are LIVE 🎆 
http://rlr.github.io/webtiles-previewer-redux/

Thanks everyone !
