### ISSUE TITLE
Prepare Style Guide

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/Mozfest2016_production#76]
Plan for the upcoming heartbeat is set. @sabrinang will provide creative. @kristinashu will drive the structure with an eye toward communicating essentials for contractors. 

This draft will include basics (i.e. type, wordmark, issues treatment, background text, background patterns). It will also include a demonstration of application to fest guide cover, stage backdrop.

Driver @edrushka 
Accountable @xmatthewx (on PTO)
Responsible @kristinashu @sabrinang 
Informed @hannahkane

**Comment by kristinashu** [comment]
Sabrina has already done a lot of the work here https://docs.google.com/presentation/d/1Wr2XK-ogr-72XnMqdmLU2Rf64S-5ctC23OimMwnsquY/edit#slide=id.g12989256b1_0_726

Still need to:
- [x] Find Pantone equivalents for the colors so printers know what to aim for. @lovegushwa do you have a Pantone book? 
- [ ] Explore icon style directions (will need the space icons asap)
- [x] update with Matthew's feedback (simplify)
- [x] Make a pdf of everything
- [ ] Make high res texture
- [x] Update body copy to Fira

**Comment by kristinashu** [comment]
Style Guide will include:
- [x] 2016 logo 
- [x] 'one web' lockup (2 standard + 2 more unique of motion)
- [x] example of 5 issues in the lockup
- [x] 3-4 patterns 
- [x] colors (2-3 core + 2 highlight + few shades of grey) with CMYK/RGB/PANTONE values
- [x] texture art 
- [x] typography (display type + body copy type + localized type)
- [ ] 1 icon to show style
- [ ] example mockups: stage, poster, guide, name card

**Comment by kristinashu** [comment]
Feedback on tne Web tag with Mark & Chris https://github.com/MozillaFoundation/Mozfest2016_production/issues/123

**Comment by sabrinang** [comment]
![mozilla-festival_visual-exploration_one-web-style-guide](https://cloud.githubusercontent.com/assets/2492510/18217068/90a6b8e8-710f-11e6-98c8-36cacdd82c5e.png)
.ai file: https://drive.google.com/file/d/0B4Q8pzCpDS_eemJXWHFBclFwc00/view
This contains tileable patterns, shapes, grid system, colour value documentation 
- Mozilla Festival 2016 Logo & One Web Lockups (with 5 strategic area lockups): https://drive.google.com/drive/u/1/folders/0B4Q8pzCpDS_eT09zaVNjMFpveTA
- Colour Swatch (.ase file): https://drive.google.com/drive/u/1/folders/0B4Q8pzCpDS_eRmVUZmlfVUYzT2M
- Fonts: https://drive.google.com/drive/u/1/folders/0B4Q8pzCpDS_eaDNCQjJLcjhxLTg

I will file a separate issue for the art and work in the issue for space icons https://github.com/MozillaFoundation/Mozfest2016_production/issues/88

**Comment by sabrinang** [comment]
high res art issue: https://github.com/MozillaFoundation/Mozfest2016_production/issues/132

**Comment by kristinashu** [comment]
@sabrinang can you also add the example mockup for the stage, poster, guide, and name card?

**Comment by sabrinang** [comment]
example of mockups are in slide deck: https://docs.google.com/presentation/d/1Wr2XK-ogr-72XnMqdmLU2Rf64S-5ctC23OimMwnsquY/edit#slide=id.g16564ebac6_0_119

**Comment by kristinashu** [comment]
Will need to updated colors based on https://github.com/MozillaFoundation/Mozfest2016_production/issues/139#event-798228730

**Comment by sabrinang** [comment]
![mozilla-festival__one-web-style-guide](https://cloud.githubusercontent.com/assets/2492510/18933870/9b0869ae-858b-11e6-9380-33203a165cc7.png)
https://drive.google.com/file/d/0B4Q8pzCpDS_eemJXWHFBclFwc00/view
- updated pantone/cmyk colour notation from ticket #139
- updated localized language examples (note: arabic is "one inclusive web" all the other languages are "one web") from ticket #124
- updated art with pixel sort examples from ticket #132
- updated with space icons from ticket #88

**Comment by edrushka** [comment]
Just want to give a huge shout out to @sabrinang and the design team for completing this awesome, comprehensive, high-quality style guide. Having this in place will help us raise the bar -- yet again -- for MozFest design.

#### THANK YOU!!!

![200](https://cloud.githubusercontent.com/assets/4515662/18934520/101427f8-858f-11e6-8d24-95241c1b8415.gif)
