### ISSUE TITLE
Heartbeat plan for Mozfest schedule app

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/Mozfest2016_production#77]
Plan for upcoming heartbeat is set. 

@mmmavis will begin setup of app instance for mozfest, triage a few bugs from the backlog, plan upcoming work, provide feedback on design feasibility. 

@kristinashu will begin a UI refresh integrating some of our universal design elements. She will check with Mavis to identify easy wins and avoid an unwieldy scope. 

Driver @edrushka 
Accountable @xmatthewx (on PTO)
Consulted @cadecairos @acabunoc 
Informed @hannahkane

**Comment by kristinashu** [comment]
Closing this ticket, progress can be tracked in the app repo https://github.com/mozilla/schedule-app-core/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22September+2%2C+2016%22
