### ISSUE TITLE
Swag - Name Cards - Deadline Oct 11

### ISSUE THREAD

**Issue by marcwalsh-zz** [MozillaFoundation/Mozfest2016_production#78]
1600x A6 name cards, double sided printed on double layered 350GSM card.

**Comment by marcwalsh-zz** [comment]
Here's an example of SourceCon's name card. Could we look into using a double clip, but we'd like to avoid using the plastic holder as it's more wasteful.

![img_5024](https://cloud.githubusercontent.com/assets/14007066/17970733/bf9d59d6-6acf-11e6-8751-766696974112.JPG)
![img_5025](https://cloud.githubusercontent.com/assets/14007066/17970737/c17377cc-6acf-11e6-8261-7e3d8b3d3dd6.JPG)

**Comment by edrushka** [comment]
I think we should discuss this asset during one of our daily stands, as we need to scope the contents and decide on the format. I'd like to review some of @sabrinang's awesome design thinking from earlier this year ([outlined in this doc](https://docs.google.com/document/d/16OyJUATrh79M3Gpm8Rpj7yvxmAFgXRiBsGHyctUWHfc/edit)) to see what ideas to incorporate.

**Comment by kristinashu** [comment]
We have a dedicated design ticket now https://github.com/MozillaFoundation/Mozfest2016_production/issues/148
