### ISSUE TITLE
Beer!

### ISSUE THREAD

**Issue by marcwalsh-zz** [MozillaFoundation/Mozfest2016_production#79]
Looking for a local brewery to supply beer for the Science Fair and Demo Party...

**Comment by marcwalsh-zz** [comment]
I've found three suppliers, all are indies and they have a nice story behind them:
- [Southwark Brewing Co](http://southwarkbrewing.co.uk/)
- [Anspach and Hobday](http://www.anspachandhobday.com/)
- [FourPure](http://www.fourpure.com/)

I'm just awaiting quotes for each and will put them into a spreadsheet for comparison. 

@Saallen they can have taste testing, so lets arrange a time when we can head down and try them! (They're all based along by Maltby Street Market)

**Comment by Saallen** [comment]
Nice work
Luckily for you I have tried them all 🍻 
How about you arrange to go with a friend one Saturday afternoon?
S

**Comment by marcwalsh-zz** [comment]
Sure thing! Do you have any preferences from the three?

**Comment by marcwalsh-zz** [comment]
Sorted, waiting for payment to be made and will be delivered on Friday morning.
