### ISSUE TITLE
June 1st email

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/Mozfest2016_production#8]
We will need a snappy, quirky celebratory email for the junes 1st website update.

Receivers of this email will be
- [ ] Last years facilitators ( 400)
 -[ ] Action specific
- [ ] Last years registrants (2150)
 - [ ]  Informative email
- [ ] Mozlearning email groups
 - [ ]  Informative email
- [ ] 2016 update emails (100)
 - [ ]  Informative email
- [ ]  other?

@KevZawacki and @edrushka if you could assist with copy once I do first draft that would be amazeballs ⚽ 

Last years emails
* https://docs.google.com/document/d/1xgjk-9eAbyRZ0V3Gqs_MGcQd9E_BUG7MFrtDQYhMZFc/edit
* https://docs.google.com/document/d/1f4HuagFOENX2JkqySNiDJ1uPI8nRIiKP9z6OVAzEUkw/edit

**Comment by Saallen** [comment]
@adamlofting when I send an email to  Last years registrants (2150)
I will let them know about the call for proposals but  should I ask the to re-sign up to continue to receive further emails from Mozfest?

**Comment by KevZawacki** [comment]
@Saallen You got it!

**Comment by adamlofting** [comment]
@Saallen it depends on the wording of the sign-up form last time.

Did they opt in to receive 'emails about Mozfest' or 'emails about Mozfest 2015' for example. I suspect it was a more generic opt-in, and we don't need to ask for new permission each year, but we should check that language.

**Comment by Saallen** [comment]
The opt was for Mozilla Festival @adamlofting 
So I can email all these folks a couple of times around the festival but I will add an opt out on the emails here too
