### ISSUE TITLE
Swag - MozFest Stickers - Deadline Sept 16

### ISSUE THREAD

**Issue by marcwalsh-zz** [MozillaFoundation/Mozfest2016_production#80]
2500 - 3000 stickers, die cut - Min size is 5cm x 5cm. 

[Supplier - Pixart Printing](https://www.pixartprinting.co.uk/printing-labels-tags/stickers/)

**Comment by kristinashu** [comment]
Deadline: Sept 16

**Comment by ed-yau** [comment]
From our MozFest Design Checkin meeting, we wanted to know @marcwalsh whether for production we could have multiple stickers and multiple colours?

We like the idea of having the **MozFest 2016** logo printed as well as the **One Web** logo printed. These would be in single block colours inspired from our design thinking for the vinyls concept in ticket #131 where we liked the idea of having large scaled block colour logo vinyls on floors around the building.

Are we limited to one sticker design or would it possible to have 2/ more with a range of colours in each? Visual of our idea below:

![stickers](https://cloud.githubusercontent.com/assets/21972436/18495563/fe81b98e-7a16-11e6-9db2-830f9f1813f9.jpg)

Let me know your thoughts!
@Carrie-ann @xmatthewx @sabrinang @kristinashu

**Comment by sabrinang** [comment]
Thanks for sharing your progress Ed :) 

If we can have a variety of stickers that would be amazing but it might come down to production costs (would be equal to print 15 unique stickers? or would it be cheaper?) those are some thoughts for Marc to provide guidance on.

I have some thoughts that might help reduce the choices. If we had to reduce the amount of stickers, I would lean towards the 2 designs: a wordmark/logo combo sticker & a one web sticker. I would prefer the “One Web” sticker to feel different and more unique from the wordmark sticker to provide more sticker variety. Instead of an outline we can do a fill (solid colour? pattern?) and the sticker could go right to the edge (no white border) which would make it feel more different too for collectors. If we used a multi-colour fill for one web sticker, that could also reduce that design choice from 5 to 1 too if we are tight on sticker budget.

I'm also curious to hear other thoughts!

**Comment by marcwalsh-zz** [comment]
This sounds great. I would look to get 2 x 1500 or 3 x 1000 stickers. 

Are you able to let me know what dimensions you're looking at @ed-yau and I'll get these priced up. (They need to be a minimum of 5x5cm)

**Comment by kristinashu** [comment]
@ed-yau for reference, the big round stickers are 7.5cm and the Science Lab sticker is 9cm long.
![img_7781](https://cloud.githubusercontent.com/assets/1068783/18569020/10e325e2-7b55-11e6-98ff-c4896ba9c293.JPG)

@marcwalsh are we using the same supplier as last year? They weren't very good quality.
<img width="590" alt="screen shot 2016-09-15 at 3 06 17 pm" src="https://cloud.githubusercontent.com/assets/1068783/18569189/f6d5e760-7b55-11e6-836d-bbdf50752106.png">

**Comment by SpikeUK** [comment]
Can we include "I speak xxxxx language" sticker in this bug or should I raise another one. I was originally considering these for "my" Local Volunteers only but I think they could be really great for all attendees.

**Comment by xmatthewx** [comment]
Let's file a separate bug for that @SpikeUK. Those stickers will have different requirements for production type and quality (non-glossy for easy writing).

**Comment by marcwalsh-zz** [comment]
@kristinashu - we're not the using the same supplier as last year. We're using [Pixart](https://www.pixartprinting.co.uk/printing-labels-tags/stickers/) for the stickers this year.

**Comment by ed-yau** [comment]
@Carrie-ann and I have produced 3 designs based on the comments above. **2 x One Web** Circle stickers: 7.5cm in diameter and **1 x Moz Fest 2016 Wordmark Lock-Up** Logo sticker: 9cm x 2.7cm. We have saved this in the google drive in 3 formats, ai file, pdf, and a jpeg. Please see the designs below...
![sticker_oneweb_7 5cm](https://cloud.githubusercontent.com/assets/21972436/18602940/427876aa-7c65-11e6-8272-c6286d134fc8.jpg)
![sticker_oneweb_2-7 5cm](https://cloud.githubusercontent.com/assets/21972436/18602943/4cda0c62-7c65-11e6-90c9-9ad39a6c5372.jpg)
![wordmark sticker - 9cm-01](https://cloud.githubusercontent.com/assets/21972436/18602997/b812c334-7c65-11e6-98fe-c5ab05a7e7f2.jpg)

Please note these files have been design all in CMYK for print. But on here they appear in the RGB colour on screen...

**Comment by xmatthewx** [comment]
Two quick comments: 
- Would we want lines behind One Web to run diagonal? (I have no strong opinion)
- When you post images to github, you can add larger image files. Github will size them nicely, and let us click thru to view high fidelity.

**Comment by sabrinang** [comment]
I like the first one web sticker palette and thickness of the bands over the second one. It may be due to the resolution but the vertical direction clashes with the text on the second.  

I think trying the diagonal angle will tie into the visual system (like the wayfinidng banner you had).

**Comment by kristinashu** [comment]
Agree, diagonal lines are the way to go! Also, I think the pink sticker could just be solid pink (with out the glitch on the gear icon). 

@marcwalsh this is the sticker printer we've used who doesn't have a size restriction https://www.stickermule.com/ Are the prices comparable to what you looked at?

**Comment by kristinashu** [comment]
I've updated the glitch stickers so the lines are diagonal and removed glitch from the Mozilla Festival version. @marcwalsh which type of Pixart stickers are you thinking of doing? Seems like they do custom sharps and have a minimum of 1cm for some of them.

Suggesting the round ones are 6x6cm and the Mozilla Festival one is 9x2.8cm.

<img width="255" alt="stickers-01_mozfest" src="https://cloud.githubusercontent.com/assets/1068783/18802181/299b4e00-819c-11e6-9dc1-10ceca619f5d.png">
<img width="170" alt="stickers-01_one web 1-01" src="https://cloud.githubusercontent.com/assets/1068783/18802183/29a22004-819c-11e6-9163-f2fa015ea534.png">
<img width="170" alt="stickers-01_one web 1-02" src="https://cloud.githubusercontent.com/assets/1068783/18802182/299e826e-819c-11e6-8cbb-a439e92e7d40.png">

**Comment by xmatthewx** [comment]
This artwork is good to go when printing decisions are finalized. Thanks @kristinashu.

**Comment by marcwalsh-zz** [comment]
Awesome! @kristinashu I'm happy with the sizes. I'll check the costs for the circular stickers but I'll go for Sticker Mule for the wordmark version.

**Comment by kristinashu** [comment]
Thanks @marcwalsh! Here's a folder with:
- eps for each sticker
- ai file with all the stickers
- jpgs for reference
- color (should try to match Pantone 232C)

Dimensions are: 6x6cm and 9x2.8cm.

[For print.zip](https://github.com/MozillaFoundation/Mozfest2016_production/files/514258/For.print.zip)

Files are also in Drive: https://drive.google.com/open?id=0B2irLVDJivhLdjJoRmttQkU1YWM

**Comment by marcwalsh-zz** [comment]
It's printing! ✌🏼

**Comment by sabrinang** [comment]
## Post MozFest Documentation

The 3 sticker designs were placed on the customize name tag table station during registration for attendees to take.
![dsc06852-small](https://cloud.githubusercontent.com/assets/2492510/20154648/35372c1a-a67d-11e6-8a44-88380e5ed875.jpg)
