### ISSUE TITLE
Swag - Volunteer T-Shirts - Deadline Sept 16

### ISSUE THREAD

**Issue by marcwalsh-zz** [MozillaFoundation/Mozfest2016_production#81]
Design for #mozhelp volunteer tshirts.

Approx. 130 to be ordered in vairous sizes (to be confirmed by @SpikeUK - order date is early October) 

Design needs to be given as A4 for chest print or A3 for full side printing.

[Supplier - Xamax](http://www.xamax.co.uk/100-gildan-coloured-t-shirt-free-print-offer.html) - Colour choices are available on the website.

**Comment by SpikeUK** [comment]
Loved last year's design; with the two-colour printing (red+white) in dark blue background. Will we be having icons/symbols to represent spaces this year?

**Comment by ioana-chiorean** [comment]
Hey all - If u do not have a design yet - u might wanna post an issue on the Open Design repo - https://github.com/mozilla/OpenDesign

**Comment by ed-yau** [comment]
Design Update:

For the T-Shirt design we are thinking of just using logo marks this year and will not be including icons like last year. We will use the One Web logo on the front and potentially a smaller mozfest logo at the back with #mozfest #mozhelp

**Clear** to visitors, **Simple** and **impactful** for the volunteers to stand out.

Colour Thoughts:
Based on the supplier suggested above, the closest colours we can match with the T-shirt colours to the style guide colour palette is potentially the Pink, Blue & Purple, or using black / white as the T-shirt colour.

Colour palette below:
![colours](https://cloud.githubusercontent.com/assets/21972436/18473731/74997b72-79b6-11e6-9025-e6338288cfbf.jpg)

Alternative Idea: (Need thoughts on this)
An idea option will visualise is possibly having 2 shirt variants this year for the volunteers?
So e.g. maybe using white logo on blue. and then an inverse blue 
Volunteer shirts could be in one who are more front of house, and backstage volunteers could wear the alternate. Is this a liked idea/ a possible route to progress on based on costs etc? @edrushka @marcwalsh

**Comment by marcwalsh-zz** [comment]
Hey @ed-yau, it's a great idea however our volunteers normally swap and change their roles throughout the weekend which is why we normally stick to one tshirt for all.

**Comment by kristinashu** [comment]
Thanks @ed-yau! Would you be able to share screen caps of the Pink, Blue & Purple t-shirt colors (that vendor website is not very clear!)?

**Comment by SpikeUK** [comment]
Interesting ideas thank you @ed-yau but (as @marcwalsh quite rightly says} our volunteers will do many and various things over the weekend. Nobody is "back of house" when they are a #mozhelp volunteer.
I would like please us to concentrate on having the purple colour above as the t-shirt background colour with text in a contrasting colour.
Traditionally we have #mozhelp on the back in white text - I would like to keep that please.

**Comment by ed-yau** [comment]
@kristinashu I've just put these pages together prior mocking some designs to clarify with everyone the colour selection based on the vendor page and how these come as coloured t-shirts. @SpikeUK I agree and definitely feel the purple could work really well out of the three colours to choose from. I will keep #mozhelp included at the back of the designs. 
![volunteer t-shirts colour](https://cloud.githubusercontent.com/assets/21972436/18494739/1697529c-7a10-11e6-8a01-baa0e97e77d1.jpg)
![volunteer t-shirts colour2](https://cloud.githubusercontent.com/assets/21972436/18494742/20bd7dbe-7a10-11e6-97fa-5ecbfbc0c41f.jpg)

**Comment by kristinashu** [comment]
Awesome, thanks for sharing those! Yes, purple would be great.

**Comment by ed-yau** [comment]
Two design options have been created based on the comments above. The front and back design are a one colour print and sit on an A4 size document. These can be found in the google drive in 3 formats, ai file, pdf, and a jpeg. Please see the designs below...
![volunteer t-shirts option1](https://cloud.githubusercontent.com/assets/21972436/18611471/0990ef8e-7d32-11e6-83a4-62b212bda2e9.jpg)
![mozshirt purple](https://cloud.githubusercontent.com/assets/21972436/18611475/22a0debc-7d32-11e6-914d-d1d139037184.jpg)
![volunteer t-shirts options2](https://cloud.githubusercontent.com/assets/21972436/18611473/0e20c9a2-7d32-11e6-93a2-c0dfb18d6de0.jpg)
![mozshirt purple-plain](https://cloud.githubusercontent.com/assets/21972436/18611477/2ad896a6-7d32-11e6-8039-5b2ff54a8cdf.jpg)

**Comment by SpikeUK** [comment]
Thank you @ed-yau they look amazing. I think I like the first option; with the one web roundel and "MOZFEST 2016" in the front and "#MozHelp" on the back all in white. But I like the yellow print as well.
Two comments if I may. Can we please lose the space between "MOZ" and "FEST" - we tend to use this as one word. And can the "#MozHelp" on the shoulders be bigger - printed on A4 landscape maybe - A4 portrait may make it a bit small on an XXL shirt ;-) 
Below is picture of an XL for 2015 with an A4 sheet of paper for scale
![mozfest2015_tshirt_back](https://cloud.githubusercontent.com/assets/1629474/18614810/2026af7a-7d8e-11e6-9a3c-fd11d362ca7f.jpg)

**Comment by marcwalsh-zz** [comment]
@SpikeUK @ed-yau 

I think that keeping the A4 would work best, it's a lot of wasted space on an A3 print which costs a fair amount more and then may look too big on smaller sizes. 

I do agree, the text should read "MOZFEST 2016" and I'd vote for option 1! :)

**Comment by SpikeUK** [comment]
@marcwalsh @ed-yau The #MozHelp can still be A4 but landscape rather than portrait - see my pic above, that is an 2015 shirt with a portrait A4 for scale.
Option 1 content but option 2 colours is my vote.

**Comment by kristinashu** [comment]
Thanks @ed-yau for mocking this up, it's super helpful to see. The designers and Marc chatted and here is a summary of our feedback:
- like the size of "ONE WEB" in Option 2 but would love to see it solid (like in Option 1) and moved to the left so it's center on the shirt
- with "MOZFEST" below "ONE WEB" (remove "2016")
- back of Option 1 looks good
- we all prefer the yellow color

**Comment by sabrinang** [comment]
@ed-yau If the circle is looking a bit plain in one colour, you can try introducing some diagonal elements inspired from the style guide to reflect some of the visual textures would be a nice tie to the pixel sort patterns we have going on this year.
<img width="950" alt="screen shot 2016-09-19 at 11 49 15 am" src="https://cloud.githubusercontent.com/assets/2492510/18644681/2ae2cc06-7e5f-11e6-9846-debe89c8f2cb.png">

I was thinking about "MOZFEST" and was thinking to rather have it spelt out completely as "Mozilla Festival" to be more on brand as it is seen in its entirety on the lockup too. I don't think we have "MOZFEST" anywhere else and maybe keep this abbreviated version as an internal thing?

**Comment by edrushka** [comment]
I think it's ok to use MozFest if that works better for design. All the copy in the guide refers to MozFest, so it's a term we use both internally and externally. Note that we don't generally write it in caps but spell it this way: MozFest.

Mozilla Festival works for the t-shirt as well, if that's better for design.

**Comment by rtsayles** [comment]
Very Nice, can't wait to wear one :)

**Comment by kristinashu** [comment]
Based on feedback, here is an updated version. I was having trouble fitting "MozFest" in but let me know if that's a must have and I'll make it work.
![shirt-insitu-01](https://cloud.githubusercontent.com/assets/1068783/18797266/03e24f3e-8182-11e6-919a-c3ebf27ee391.jpg)

**Comment by SpikeUK** [comment]
Thank you @kristinashu - that looks brilliant!!
I would like to have 'MozFest 2016" on the front somewhere if possible please, even if it is in a fairly small font right justified below the ONE WEB logo.
(Geek event t-shirt collectors will understand ;-) )

**Comment by kristinashu** [comment]
MozFest text doesn't work on the front because of the lines coming out of the circle but I've added it to the back.

![shirt-insitu-02](https://cloud.githubusercontent.com/assets/1068783/18802601/a5ef6b88-819e-11e6-820d-d1f840a516f7.jpg)

**Comment by SpikeUK** [comment]
Thank you @kristinashu, would something like this work?
Or maybe with 'MozFest2016' 50% smaller? But bottom right of the print area as shown.
![mozfest16_vol_tshirt](https://cloud.githubusercontent.com/assets/1629474/18805445/37aa4392-8206-11e6-85ce-5117ad408487.jpg)

**Comment by kristinashu** [comment]
We'll share a few version with Sarah and the design team and let you know!

**Comment by SpikeUK** [comment]
Apologies for interfering @kristinashu - my only authority with this is that I have worn the MozFest volunteer t-shirt for five years years running now and have an interest in the design.
Spike - out

**Comment by xmatthewx** [comment]
Thanks @SpikeUK for your interest, input, and flexibility 😄 ✨

**Comment by xmatthewx** [comment]
Let's run with @kristinashu's design with "MozFest 2016" on the back. 

@marcwalsh and @kristinashu – please confirm with the print shop that the line weight and color will work on a dark t-shirt. Some roughness or inconsistencies could actually look interesting, or like a bad accident. They probably have a minimum line weight recommendation.

@kristinashu – how big do you plan to go with the circle? IMHO 10-12cm would be nice. 15cm max. 20cm not so cool. 

Following that, I think we're go to go!

**Comment by kristinashu** [comment]
Here's a folder with:
- eps for front and back of shirt
- ai file with front and back of shirt
- insitu example for reference
- color (should try to match Pantone Pastels Neons Coated 809C)

Shirt color is purple.

Dimensions are:
- Circle is 12cm wide
- #MozHelp is 21cm wide

[For print.zip](https://github.com/MozillaFoundation/Mozfest2016_production/files/514253/For.print.zip)

Files are also in Drive: https://drive.google.com/open?id=0B2irLVDJivhLWmhtZUlGeVVVdWc

**Comment by SpikeUK** [comment]
@marcwalsh 
Size breakdown for volunteer t-shirt sizes:
XS        5
S        23
M      34
L        21
XL      15
XXL    10
Total 108

This does not include the Rave "volunteers" (10 of various sizes)

**Comment by marcwalsh-zz** [comment]
All sent to printers! Arriving the Wednesday/Thursday of MozFest week.

👕 🙌

**Comment by sabrinang** [comment]
## Post MozFest Documentation

The volunteers were easy to spot and were lookin' good in the bold purple tees! :raised_hands:
![mozfest-documentation-volunteer-shirts](https://cloud.githubusercontent.com/assets/2492510/20159448/844e6c88-a695-11e6-9f8d-bcae695294e9.png)

**Comment by SpikeUK** [comment]
The volunteer t-shirts were a great success - I have lost count of how many (non-volunteers) asked how they could get one.
The printing of the text came out much greener than I had expected - was expecting more of a goldy colour - may mean I need to calibrate my laptop screen ;-)

ps - many thanks @sabrinang of the wonderful job you are doing here documenting how the design work panned out in reality.
