### ISSUE TITLE
Onboarding design contractors

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Mozfest2016_production#82]
Before they start:
- [x] clarify sign off process: all assets need sign off from Marc for print specs + from Matthew, Sabrina, or I for design (we need to decide who)
- [x] each asset needs a ticket with a milestones, background info, deadline, print specs, last years design for reference...
- [x] style guide https://github.com/MozillaFoundation/Mozfest2016_production/issues/76
- [x] set up kick off meeting
- [x] set up design meeting twice a week

Once they start:
- [x] explain our Github workflow 
- [x] give access to Mozfest2016_production Github account
- [x] give access to MozFest Drive folder 
- [x] explain Drive folder structure
- [x] intro to vidyo
- [x] access to redpen
- [x] review list of all assets https://docs.google.com/a/mozilla.com/spreadsheets/d/1P4co4m11LE7hNQoM3xf0AgSEcl9KY-lrqcU-xINWEq0/edit?usp=sharing
- [x] share pics from last year https://www.flickr.com/photos/mozfest/albums/with/72157660181490099
- [x] time tracker
- [ ] 

cc @edrushka @marcwalsh @sabrinang @xmatthewx

**Comment by edrushka** [comment]
> each asset needs a ticket with a milestones, background info, deadline, print specs, last years design for reference...

I can help with this.

**Comment by kristinashu** [comment]
Thanks! I think [this assets doc](https://docs.google.com/a/mozilla.com/spreadsheets/d/1P4co4m11LE7hNQoM3xf0AgSEcl9KY-lrqcU-xINWEq0/edit?usp=sharing) is a good check list of tickets we'll need and which heartbeat they'll fall into.

**Comment by kristinashu** [comment]
Here's an email draft I'll be sending to the contractors before they start https://docs.google.com/a/mozilla.com/document/d/1SARBFa_Iqm2n9J-ExgGdACRmxjFadclx36MGHVVTUu8/edit?usp=sharing

Please add any missing pieces @xmatthewx @edrushka @marcwalsh @sabrinang

**Comment by kristinashu** [comment]
I've send the email to them.
