### ISSUE TITLE
Design social graphics for Twitter and Facebook - Deadline Oct 7

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Mozfest2016_production#84]
#### Info:

About 6 different graphics resized for Twitter and Facebook. Images should feature this year's "One Web" tagline and style.

Style Guide: #76

Comms ticket: https://github.com/MozillaFoundation/Mozfest2016_production/issues/83
#### Last year's:
- Working files in Drive https://drive.google.com/drive/folders/0B20-0lpP23c0NFg3SmhlZ2M0c2s?usp=sharing
- GitHub ticket https://github.com/mozilla/mozillafestival.org/issues/226

**Comment by kristinashu** [comment]
@edrushka @KevZawacki are there any particular posts you want images for? Or should we just do a few different version of "One Web"?

@taisdesouzalessa is going to start working on this.

**Comment by edrushka** [comment]
Let's bring @KGorr and her super duper [MozFest social calendar](https://docs.google.com/spreadsheets/d/1W9O30WNK1BLWfqj-DjkZs_0k0gYq4hMAlrVUWTdJDco/edit#gid=0) into this convo.

**Comment by KevZawacki** [comment]
@kristinashu A few different versions of One Web work for me. But I will let @KGorr chime in, too -- she's our MozFest social content lead.

**Comment by KGorr** [comment]
@kristinashu - I agree with Kevin. I think keeping it general to the festival theme is best. Thank you!

**Comment by kristinashu** [comment]
Perfect, thanks everyone!

**Comment by taisdesouzalessa** [comment]
Hi, here are the options (I started with Twitter first and once we have those locked down and approved I'll use the same templates for Facebook): https://redpen.io/p/qwaf5cfe4531a63744 

For Twitter I also worked on a gif. It would be nice to have a copy that accompanies the "One Web" tagline - I just have a placeholder there for now. 
![animation-twitter-v8](https://cloud.githubusercontent.com/assets/22157921/19057513/3791bfc6-8985-11e6-8357-5dd035320436.gif)

Please let me know your thoughts on them. Thanks!

**Comment by edrushka** [comment]
Love that, @taisdesouzalessa! So fun!! 

Here's some ideas for text. Let me know what length works best.
- The world's leading festival for the open internet movement.
- Build, debate, and explore the future of a healthy internet.
- Grow your network and get inspired.
-  Design tools to support and protect our essential internet freedoms.  
- MozFest - building and protecting a free and open internet.
- For those who care about a free and open internet, MozFest is the place to be.

**Comment by KevZawacki** [comment]
This is so cool!

I really like @edrushka's last bullet: "For those who care..."

**Comment by edrushka** [comment]
@StevieBenton gets the credit for that line :) @taisdesouzalessa let us know if you need something more or different.

**Comment by taisdesouzalessa** [comment]
Thanks for the text @edrushka! They all fit. I chose some of them and applied to the animation. Please take a look and let me know what you think or if you would like to see any other text applied there.
![twitter-v1-opt6-build-debate](https://cloud.githubusercontent.com/assets/22157921/19094280/28993ade-8a44-11e6-91ba-2e0b19981f93.gif)

![twitter-v1-opt6-mozfest-building](https://cloud.githubusercontent.com/assets/22157921/19094282/28b2cd50-8a44-11e6-9f2e-782f034ebecf.gif)

![twitter-v1-opt6-mozfest-for-those](https://cloud.githubusercontent.com/assets/22157921/19094281/28b00458-8a44-11e6-8318-3ba970a4b4a9.gif)

![twitter-v1-opt6-mozfest-grow-network](https://cloud.githubusercontent.com/assets/22157921/19094283/28b76de2-8a44-11e6-98be-eb6adf5d19ef.gif)

I also made a gif for one of the static versions - based on @flukeout's suggestion:
![twitter-v1-opt5](https://cloud.githubusercontent.com/assets/22157921/19094314/5844609c-8a44-11e6-9ce6-e6257b9d112a.gif)

**Comment by taisdesouzalessa** [comment]
The RedPen is updated according to the latest feedback I received:
https://redpen.io/p/qwaf5cfe4531a63744

@kristinashu, @edrushka, @KevZawacki, @KGorr, @xmatthewx  please let me know if you have any revisions you would like me to make. 

After those options are approved, I'll work on the Facebook dimensions. Thank you!

**Comment by KevZawacki** [comment]
@taisdesouzalessa They are **awesome**. Really excited to get them up on Twitter.com/Mozilla!

**Comment by xmatthewx** [comment]
These are a amazing. 

I suggest that we shorten the length on these so they can be read in a blink.  
- ~~Build, debate, and explore~~ The future of a healthy internet. 
- ~~Mozfest~~ Build~~ing~~ and protect~~ing~~ a free ~~and~~ & open internet. 
- Grow your network ~~and~~ & get inspired. 
- ~~For those who care about a free and open internet, MozFest is the place to be.~~

**Comment by taisdesouzalessa** [comment]
I agree with @xmatthewx that the sentences could be shorter. Specially on social media, where the attention spam is so short, the faster we can convey the message, the better. 

Kudos to @flukeout, @sabrinang, @kristinashu for their feedback on the animation on RedPen , they helped it to evolve to the stage it is now :)

Here are the new iterations, with shorter sentences:
![twitter-v2-build-protect](https://cloud.githubusercontent.com/assets/22157921/19125875/8bd41bb0-8aed-11e6-8247-c06412e75dba.gif)

![twitter-v2-grow-network](https://cloud.githubusercontent.com/assets/22157921/19125879/8db0bd9e-8aed-11e6-9452-208236703714.gif)

![twitter-v2-the-future](https://cloud.githubusercontent.com/assets/22157921/19125883/8f49d55a-8aed-11e6-80dc-395c9297f301.gif)

**Comment by edrushka** [comment]
+1 to shorter copy. These look fabulous.

**Comment by taisdesouzalessa** [comment]
Hey, thanks for all the contributions here!

Here are the final deliverables:
Twitter:
[Twitter-jpgs.zip](https://github.com/MozillaFoundation/Mozfest2016_production/files/517028/Twitter-jpgs.zip)
[Twitter-gifs.zip](https://github.com/MozillaFoundation/Mozfest2016_production/files/517029/Twitter-gifs.zip)

Facebook:
[Facebook-jpgs.zip](https://github.com/MozillaFoundation/Mozfest2016_production/files/517030/Facebook-jpgs.zip)

Note that the Facebook folder doesn't have gif versions because as far as I know, they don't allow post your own gif (just if it is hosted somewhere else). If you need gif for Facebook, please let me know. 

Thanks

**Comment by KevZawacki** [comment]
🎆 @edrushka @xmatthewx Are these ready to be shared with the world? If so, I can put them to work Monday.

**Comment by xmatthewx** [comment]
> they don't allow post your own gif (just if it is hosted somewhere else)

@mmmavis or I can drop those animated gifs with the other assets on the mozfest site. So you could share a link. They won't appear on the site, just sit in a directory like [this](https://mozillafestival.org/assets/images/about-3.jpg). Does that work?

**Comment by edrushka** [comment]
I'm excited to share as soon as MW gives his final thumbs up! Awesome job everyone 😍

**Comment by xmatthewx** [comment]
> Are these ready to be shared with the world? If so, I can put them to work Monday.

@KevZawacki – design wise, they're good to go. As long as size and everything else works for you. 

Yippee! 🚀

**Comment by taisdesouzalessa** [comment]
@xmatthewx yay!! So great we can host the gifs somewhere and post on Facebook, thanks for letting me know! I'll prepare the gifs then for Facebook dimensions and add a zip here shortly.

**Comment by mmmavis** [comment]
@xmatthewx sorry if I misunderstood - if we are sharing these images out on Twitter/Facebook we can upload images directly there. If that's true we don't have to hotlink to assets on mozfest.org.

**Comment by xmatthewx** [comment]
No problem @mmmavis. @taisdesouzalessa mentioned that Facebook doesn't allow users to upload a gif with animation. But, they will let you link to one. I bet that they cache their own copy, so I wouldn't be worried about hotlinking. I haven't researched any of this, so please continue to question my suggestion. 

Maybe we post to imgur or another service instead of our site, and then share to facebook?

**Comment by taisdesouzalessa** [comment]
@mmmavis when I post a gif to Facebook directly it doesn't work unless I provide an external link, like that:
![posting](https://cloud.githubusercontent.com/assets/22157921/19205857/c1faa13e-8c99-11e6-8d6b-dee4c01551c7.gif)
If you know a way to upload directly to Facebook and make it work, let me know! I would love to learn!

**Comment by mmmavis** [comment]
@xmatthewx Gotcha! Good practice is that website/repo should only contain assets that the website uses. If we need to host those images for social share purposes only we should create a S3 bucket and drop those files there. /cc @cadecairos here for next step. 😄

**Comment by cadecairos** [comment]
An S3 Bucket should suit our needs. 

I could also drop them onto a CDN for better performance worldwide. We've got stuff.webmaker.org available.

**Comment by mmmavis** [comment]
🍻 🍻 🍻 🍻 🍻

**Comment by taisdesouzalessa** [comment]
Awesome, thanks for the solution @mmmavis @cadecairos and @xmatthewx . Here are the Facebook gifs that should be hosted somewhere else. Once you upload them, could you please provide the links in this thread?:
[Facebook-gifs.zip](https://github.com/MozillaFoundation/Mozfest2016_production/files/517175/Facebook-gifs.zip)

Thanks and let me know if you encounter any size or other restrictions when you post them @edrushka and @KevZawacki.

**Comment by taisdesouzalessa** [comment]
Closing this task here!

**Comment by kristinashu** [comment]
Also https://github.com/MozillaFoundation/Mozfest2016_production/issues/213
