### ISSUE TITLE
Design email graphics - Deadline Oct 7

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Mozfest2016_production#85]
#### Info:
- CTA = Ticket sales, send to all
- MoCos only, Expectations. Sarah or Marc to send from Festival@ address

Related to Comms & marketing https://github.com/MozillaFoundation/Mozfest2016_production/issues/83
#### Deadline:
- Oct 7
#### Last year's:
- GitHub ticket https://github.com/mozilla/mozillafestival.org/issues/237

**Comment by kristinashu** [comment]
@edrushka @KGorr I'm not sure where this info came from, is it still relevant? Would you like some a "buy tickets" graphic and/or a few generic "one web" ones?

**Comment by KGorr** [comment]
@kristinashu - all of the emails are pretty much done now, so I think the general one web designs will be fine for use if we still want to use them in email. Thanks

**Comment by edrushka** [comment]
Yah, this was probably added waaay back when we were first making lists of assets. Let's close.
