### ISSUE TITLE
Design Space Icons

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Mozfest2016_production#88]
#### Info:

Five new icons and might need to update icons set to match new creative direction.

The spaces are:
- [x] Digital Arts and Culture (new in 2016)
- [x] Journalism
- [x] Open Science
- [x] Open Badges
- [x] Fuel The Movement  (new in 2016)
- [x] Localisation
- [x] Youth Zone
- [x] Demystify the Web  (new in 2016)
- [x] A Tale of Two Cities: Dilemmas in Connected Spaces  (new in 2016)
- [x] MozEx (Art Exhibit)  (new in 2016)

These will appear on: banner flags, schedule app, website, festival guide...
#### Deadline:
- Sept 9th
#### Blockers:
- blocked by: style guide
- blocking: banners, schedule app, festival guide... 
#### Last year's:
- Working files in Drive https://drive.google.com/open?id=0ByxhqwUuz00oOFV4VTd2a3NBalk
- GitHub ticket https://github.com/mozilla/mozillafestival.org/issues/213

<img width="529" alt="screen shot 2016-08-23 at 12 58 19 pm" src="https://cloud.githubusercontent.com/assets/1068783/17908012/67cfcf42-6933-11e6-9063-212cd8bf2c67.png">

<img width="621" alt="screen shot 2016-08-23 at 1 13 09 pm" src="https://cloud.githubusercontent.com/assets/1068783/17908010/64861314-6933-11e6-8cde-705800f8fe22.png">

**Comment by edrushka** [comment]
@sabrinang @kristinashu is it reasonable to have the new-for-2016 space icons designed in the first week of the next heartbeat? We'll need those for other printed assets.

**Comment by kristinashu** [comment]
Yes, I think that's a good idea. @sabrinang we should explore icon style directions for the style guide this heartbeat.

**Comment by sabrinang** [comment]
Space wrangler meetings are on Thursday if we want to get some input from the wrangler on icons.

**Comment by xmatthewx** [comment]
@edrushka @Saallen – despite what I said when we all met earlier, we'll run with an updated set of space icons similar to last year. 

>  A Tale of Two Cities: Dilemmas in Connected Spaces

This space name is way longer than all the rest. I think we should expect to use the shortened "Dilemmas in Connected Spaces" in most print items.

**Comment by Saallen** [comment]
👍 
Currently they are identified as  ATOTCADOCS......
😵

**Comment by sabrinang** [comment]
**Redesign of original icons:**
- streamlined width of icons, avoiding fills
- proportionate height as a set
- spacing and angles based on One Web’s grid system
- note: badges is a new icon, 2015 did not have an icon for badges

<img width="790" alt="screen shot 2016-09-09 at 9 30 42 am" src="https://cloud.githubusercontent.com/assets/2492510/18394719/2370a368-7670-11e6-8918-66b5a930ed7a.png">
<img width="917" alt="screen shot 2016-09-09 at 9 04 59 am" src="https://cloud.githubusercontent.com/assets/2492510/18394367/819385fc-766e-11e6-8cbb-26411558ce77.png">
Application examples of various widths, colours and texture:
<img width="1274" alt="screen shot 2016-09-09 at 9 06 00 am" src="https://cloud.githubusercontent.com/assets/2492510/18394369/82efb628-766e-11e6-8ccb-a349f5fed587.png">

Depending on scale and application, you can adjust width of the stroke optically (using path version) to balance out the weight of the icon when it is next to type or standing alone .

SVG icon outlines and paths version exported here: https://drive.google.com/drive/u/1/folders/0B4Q8pzCpDS_eR01fX0FodVZOS3c

Next steps, second set of new icons to follow.

**Comment by Saallen** [comment]
Hey @sabrinang  I am loving theses designs, especially the font and colours. 🎨 
One piece of feedback from Youth zone over the years,  is  that the community do not like their age seen as indicative of their talents. So I would avoid any logos or images that may be perceived as childish or a young person

**Comment by xmatthewx** [comment]
These are fab. I am way more excited about icons than I was before. I particularly like the one on the top right. 

@Saallen – can you ask the Youth Zone wranglers for a list of things that could represent the zone? A long messy list is better than a specific request. A mix of abstract words and specific things would be great, e.g. _fast_,  _games_, fist bump.

@sabrinang – is this a good idea? Would it be helpful to get lists from the new spaces as well?

**Comment by sabrinang** [comment]
@xmatthewx I think it would be really helpful from the new spaces as well since there are no previous reference and knowing what they do not want is also equally as useful

@Saallen thanks for the feedback will incorporate in next round of iterations

**Comment by thornet** [comment]
@Saallen @xmatthewx we'd be fine changing our name to just "Dilemmas in Connected Spaces" for sanity, signage and more.

**Comment by edrushka** [comment]
@Melechuga @omnignorant @mozexhibit:  [Please review this redpen](https://redpen.io/vje77895a40e81fe4e) and comment on the potential directions we can go with your Space Icon. Let us know which images you like/don't like. If you don't like any of these images, give us some words/concepts/emotions you'd like Sabrina to explore.

**Comment by Melechuga** [comment]
@edrushka Sounds good! Is Tuesday EOD ok? Gotta ping a few people who are spread out and traveling...

**Comment by edrushka** [comment]
The sooner the better @Melechuga - if you can even give a hint as to which direction you like, Sabrina can start iterating.

**Comment by MozExhibit** [comment]
@edrushka @Saallen @xmatthewx @sabrinang - We love the first two icons (top left) for MozEx. The first one is an interesting representation of connection, forming somehow an intricate X. The second one still relates to connections (and channels) but forms an E.

As we are an Exhbition/Experience/Exchange, perhaps the E represents all this whilst at the same time fits with as "E"xhibit.

If you are putting colours into the final image, can we match a bit with our MozEx ban we are using at Tate and V&A, also also the publication? Sarah, this is the one we also used on part of the call, so perhaps you can share it with Matthew and Sabrina? Just the colour-palette would do, and we could then use the icon into our developments too.

Let me know.

**Comment by Melechuga** [comment]
@edrushka @Saallen @xmatthewx @sabrinang 
Thanks for these! 
One of the goals of Fuel the Movement is to engage, organize, and mobilize people for action. We were hoping we could capture that sentiment in the logo by showing the power of grassroots community -- hopefully a diverse community that reflects worldwide internet users.

Would something like a crowd working together/protesting capture this sentiment? Also, for this year, it'd be awesome if one of the flags/picket signs had the copyright © on it. 

The fist is definitely a symbol of solidarity and resistance, but it also brings with it a lot of historical/political baggage. And especially in a European context, where it's linked closely to communist movements in the East, it might be a good idea to avoid. 

Happy to chat through any of this; feel free to ping. And thanks again!

**Comment by sabrinang** [comment]
<img width="1315" alt="screen shot 2016-09-26 at 5 22 29 pm" src="https://cloud.githubusercontent.com/assets/2492510/18856226/e138a60c-840d-11e6-908f-861964bf6712.png">
Thank you for all for leaving feedback last week space wranglers! Just an update, it helped inform the content of the icons and they are designed to work together as a set or when used alone. I am in the process of cleaning up the lines and exporting them so expect them to be ready soon!

**Comment by Saallen** [comment]
These look great. Thanks Sabrina, for all the hard work and peer assists!

**Comment by edrushka** [comment]
Awesome job!! :art: Final exports should be ready by Thursday's Space Wranglers call. Thanks Sabrina!

**Comment by sabrinang** [comment]
The .svgs and .ai file are exported in the gdrive! https://drive.google.com/drive/u/1/folders/0B2irLVDJivhLaEZ2RTk1Q0JWZE0

**Comment by sabrinang** [comment]
## Post MozFest Documentation

The space icons are seen in white on large wayfinding banners hanging from the balustrades on each level adjacent to the one web and floor # banners. The space icons scaled well, the lines had great contrast against the dark blue and was identifiable from a distance.
![mozfest-documentation-photos_space-icons-1](https://cloud.githubusercontent.com/assets/2492510/20094059/70f46878-a554-11e6-92ba-03524d9a9dfb.png)

Medium sized space icons are seen on banners with space names placed at the information desks on the corresponding level. If the level didn’t have it present, it was found on the level else where. 
![mozfest-documentation-photos_space-icons-2](https://cloud.githubusercontent.com/assets/2492510/20094058/70f17c08-a554-11e6-88d4-5b03c0270421.png)

The space icons are on another smaller poster with space descriptions and was behind the information desks as well.
![mozfest-documentation-photos_space-icons-3](https://cloud.githubusercontent.com/assets/2492510/20094060/70f8db56-a554-11e6-9d85-9b491831f5ef.png)

Smaller space icons are seen in blue printed on the festival guide spaces section. Also, these were seen on the web on the mozfest [website](http://mozillafestival.org) and the [schedule app](http://schedule.mozillafestival.org). The space icons for the web were optimized to have a 1px stroke width to achieve the visual balance on smaller applications.
![mozfest-documentation-photos_space-icons-5](https://cloud.githubusercontent.com/assets/2492510/20094387/d2bb8c20-a555-11e6-9ea0-ae23e64ff6ea.png)

It was fun to spot space icons applied in unique ways around the venue too! It was seen hand drawn, hand cut out of cardboard, projected on walls, on projects, printed on paper and t-shirts by the spaces.
![mozfest-documentation-photos_space-icons-4](https://cloud.githubusercontent.com/assets/2492510/20094061/70f9bf44-a554-11e6-8687-73ebd3a3bc44.png)
