### ISSUE TITLE
Design Wayfinding: Info booths

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Mozfest2016_production#90]
#### Info:

Based on epic ticket - Design Wayfinding #131 
### 1) Poster for each space (includes: space icon, space name, space description).
- Digital Arts and Culture
- Journalism
- Open Science
- Open Badges
- Fuel The Movement
- Localisation
- Youth Zone
- Demystify the Web 
- Dilemmas in Connected Spaces 
- MozEx

These will be posted behind the info table on the pin board. Up to the designer to choose a size.
<img width="620" alt="3993d078-77fe-11e5-8f74-24452246b614" src="https://cloud.githubusercontent.com/assets/1068783/19322581/819aee4a-906e-11e6-8275-63b4ae938e07.png">

Copy for space descriptions can be pulled from website: https://mozillafestival.org/spaces-and-sessions

Icons: https://drive.google.com/open?id=0B2irLVDJivhLaEZ2RTk1Q0JWZE0

Design could tie in with banner design https://github.com/MozillaFoundation/Mozfest2016_production/issues/178 or any with some of the patterns used https://redpen.io/p/br47a8e04658ed72f9

Example from last year:
<img width="536" alt="screen shot 2016-10-12 at 11 24 29 am" src="https://cloud.githubusercontent.com/assets/1068783/19322582/819f3fd6-906e-11e6-831f-1f49d27af344.png">
### 2) Info sign:

Each info both needs a sign to let people know it is an info booth.
Need to print one for each space.

Example from last year:
<img width="198" alt="screen shot 2016-10-12 at 11 24 17 am" src="https://cloud.githubusercontent.com/assets/1068783/19322583/819fdefa-906e-11e6-9e60-9c7dda2cc3a7.png">
#### Last year's specs and info:
- Print at https://www.pixartprinting.co.uk
- Working files in Drive https://drive.google.com/open?id=0B2qu3ExKWIlvZmg4NFVtSXVvVTA
- GitHub ticket https://github.com/mozilla/mozillafestival.org/issues/280

**Comment by kristinashu** [comment]
Thanks @taisdesouzalessa! I've updated the info above to better reflect what we talked about.

**Comment by taisdesouzalessa** [comment]
I was wondering how much I should leave as bleeding area. Could you please let me know? Thanks!

**Comment by kristinashu** [comment]
@marcwalsh any idea how much bleed we should include?

**Comment by taisdesouzalessa** [comment]
@kristinashu @sabrinang @xmatthewx here are the poster options:
https://redpen.io/p/hk6d0021f97dd28991

I prepared a rationale sheet (it is also in RedPen so you can add your thoughts there if you have any questions or disagree with any point I made there):
![rationale](https://cloud.githubusercontent.com/assets/22157921/19364589/9f11e548-9143-11e6-84e3-7d6fd82e29a8.jpg)

Once we choose one of the three poster options, I will work on the other posters for all spaces (10 in total).

@kristinashu is the deadline for all those options EOD Wed (Oct 19th) next week?

**Comment by kristinashu** [comment]
Looks great @taisdesouzalessa! I've left a few comments in redpen. 

@marcwalsh when do you need these by? Is mid next week ok?

**Comment by taisdesouzalessa** [comment]
@kristinashu based on your and Sabrina's feedback, here is the chosen poster with the adjustments requested:
https://redpen.io/ofd04d10fc0ed608d8

We will use the pink info sign - it has more contrast. 

Please let me know your thoughts on that. After your feedback, I'll do the other 9 posters following the same template. 

Thanks!

**Comment by kristinashu** [comment]
Looks great @taisdesouzalessa! I think you can go ahead and layout the rest of the spaces.

**Comment by taisdesouzalessa** [comment]
@kristinashu @sabrinang @xmatthewx - here are all the posters:
https://redpen.io/p/hk6d0021f97dd28991

I also did a sheet with all of them:
![all-posters](https://cloud.githubusercontent.com/assets/22157921/19460427/78f22af8-9490-11e6-8093-9eecc9bacbd0.jpg)

Please let me know if you have any feedback on them by tomorrow lunch time if possible. I'll be exporting the final files tomorrow afternoon so we can get them printed on time. If you need more time for feedback please let me know and we can find a way to accommodate :)

**Comment by kristinashu** [comment]
These look great! 

@edrushka or @marcwalsh could you please give these a once over and then @taisdesouzalessa will export them for print? Copy was pulled from the website.

**Comment by edrushka** [comment]
@taisdesouzalessa I can't zoom into the actual text on the redpen. Can you pls tell me where you pulled it from?

**Comment by taisdesouzalessa** [comment]
Hi @edrushka I got the text from the website: https://mozillafestival.org/spaces-and-sessions

However I would recommend you check the copy from the posters to make sure they are all correct. I am sending you a zip file here:
[posters.zip](https://github.com/MozillaFoundation/Mozfest2016_production/files/536793/posters.zip)

Let me know if you need anything else :).

**Comment by edrushka** [comment]
Sorry - I didn't realize all the individual pages were also in the Redpen. I found them, and made copy edits there -- changed all the capitalized Webs and Internets to lower case. :face_with_head_bandage:

**Comment by taisdesouzalessa** [comment]
@edrushka here are the posters with the requested changes (I didn't change the thumbnail version, just the individual big posters) - all the ones who changed have now a "v2" next to their name:
<img width="278" alt="screen shot 2016-10-18 at 2 49 54 pm" src="https://cloud.githubusercontent.com/assets/22157921/19497597/f26f02f0-9541-11e6-90bb-1aec4aa29125.png">

https://redpen.io/p/hk6d0021f97dd28991

**Comment by kristinashu** [comment]
These look good @taisdesouzalessa! Can you please export them for print? I think a pdf with 3mm bleed and crop marks should be good.

**Comment by taisdesouzalessa** [comment]
@kristinashu here they are. I added a 5mm bleed for the posters since they are bigger. The info sign has a 3mm bleed.
Please take a look:
[Mozfest-2016-info-booth-posters-420x594mm.pdf](https://github.com/MozillaFoundation/Mozfest2016_production/files/537565/Mozfest-2016-info-booth-posters-420x594mm.pdf)

[Mozfest-2016-info-booth-icon-297x297mm.pdf](https://github.com/MozillaFoundation/Mozfest2016_production/files/537567/Mozfest-2016-info-booth-icon-297x297mm.pdf)

**Comment by kristinashu** [comment]
Thanks @taisdesouzalessa!

@marcwalsh these are ready to print! I guess we need one of each Space and 10 info signs.

**Comment by marcwalsh-zz** [comment]
Printed!

**Comment by sabrinang** [comment]
## Post MozFest Documentation

The info booths set up for each space had a banner with the space description along with an info sign and participation guidelines. These signs were pinned on movable space dividers behind a table or taped on the wall or column behind the table. Some spaces shared floors so the booths were seen side by side.
![mozfest-documentation-info-booths](https://cloud.githubusercontent.com/assets/2492510/20153565/2d49bd10-a678-11e6-8be1-185b8d719efb.png)

![30695351566_7d4aca0064_k](https://cloud.githubusercontent.com/assets/2492510/20154959/8bdb69f4-a67e-11e6-9da8-d99064f1068d.jpg)
