### ISSUE TITLE
Design Wayfinding: Floor plan maps - Deadline Oct 11

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Mozfest2016_production#91]
#### Info:

Based on epic ticket - Design Wayfinding #131 

We will build off last year’s maps. Just need to update colors and move a few things around (for example Spaces and adding a secondary stage)
### Two types of maps (see below for examples from last year):

1) **Overview map:** 
- a high level map showing all the floors
- poster size
- will appear in elevators, just outside elevators, stairs, in foyer, at info booths, scattered around building... 
- will also be folded into an insert in Festival Guide

2) **Zoomed in map for each floor:** 
- this is a posters on each specific floor (example: detailed map of floor 6 will only be on the 6th floor)
- need a different version for each floor

Map should include (same content as last year, just need to update some of the locations:
- Spaces (list of spaces and icons https://github.com/MozillaFoundation/Mozfest2016_production/issues/88)
- Lunch areas
- Coffee
- D&D stage
- Main speaker stage
- Prayer room
- Supplies room
- Creche
- Toilets
- Water
- #mozhelp, info booth

These locations will be updated in redpen: https://redpen.io/tp8c68c697ba47ced8
#### Deadline:
- Oct 11 of offsite printing
#### Blockers:
- Space locations will become available at the last minute.
#### Last year's:
- Working files in Drive https://drive.google.com/open?id=0B20-0lpP23c0d0RWaW42T242SW8
- GitHub ticket: Large maps for wayfinding https://github.com/mozilla/mozillafestival.org/issues/279
  You can see how it will need to stand out against all the diy posters.

**Overview map:** 
<img width="534" alt="screen shot 2016-09-22 at 1 45 05 pm" src="https://cloud.githubusercontent.com/assets/1068783/18765515/e27f106e-80ca-11e6-8192-b32c21ed6e79.png">

**Zoomed in map for each floor:**
<img width="537" alt="screen shot 2016-09-22 at 1 44 55 pm" src="https://cloud.githubusercontent.com/assets/1068783/18765516/e27f20d6-80ca-11e6-9deb-940662b68a24.png">

**In situ Example**
<img width="343" alt="screen shot 2016-08-23 at 1 00 33 pm" src="https://cloud.githubusercontent.com/assets/1068783/17907873/b3c189d2-6932-11e6-8497-284ee5870bdf.png">

**Comment by kristinashu** [comment]
Tracking locations as they are assigned here https://github.com/MozillaFoundation/Mozfest2016_production/issues/155

**Comment by kristinashu** [comment]
cc @ed-yau

**Comment by marcwalsh-zz** [comment]
@ed-yau @carrie-ann @kristinashu 

Do we have a size for the insert map into the festival guide. I'm guessing it will be smaller than A5?

**Comment by kristinashu** [comment]
Carrie-ann mentioned it would be A4 folded down (it could be A3 or A2) https://redpen.io/ygd08696f1ba731c2f

**Comment by Carrie-ann** [comment]
@marcwalsh 

We have been actually looking at it to be bigger, around A4 when folded so the maps could be A2 quartered or A3 halved?

**Comment by marcwalsh-zz** [comment]
thanks @Carrie-ann I'll get quotes on both

**Comment by kristinashu** [comment]
@ed-yau will we be able to see the first version of these maps for Monday? You should be able to do everything except for Space locations.

**Comment by xmatthewx** [comment]
To reiterate a discussion from our last call: these maps need a refresh, not a redesign ... just content, colors, and easy improvements.

**Comment by ed-yau** [comment]
@kristinashu @xmatthewx I will have a mocked map ready by Monday! Thanks.

**Comment by kristinashu** [comment]
@ed-yau has mocked up one example map: https://redpen.io/p/yfad874f695291a82c

We've given some feedback on colours and he will update, build out the rest of the floors and the overview map.

Note the mounted maps have a separate glitch pattern behind them to help them stand out. Maybe this pattern could match the back of the folded map?

![red-pen-559cda94-3e9a-4d86-ebc5-2e30f17ebe3a](https://cloud.githubusercontent.com/assets/1068783/19163619/8b4962ee-8bb1-11e6-8590-2a46499b42c5.jpg)

**Comment by kristinashu** [comment]
@sabrinang could I get your feedback on the maps? https://redpen.io/p/nca82e6ea157535639

The new space names didn't fit well in last years rectangles so I just put them as text.

**Comment by kristinashu** [comment]
Here are all the maps. 

@marcwalsh could you please review the maps https://redpen.io/p/nca82e6ea157535639 and the quantities (below). If everything looks good to you, then they are ready to print!

Dimension: A3 

Overview map:
- in each elevator x5
- left side of each elevator x44

Each level's detail map (to appear on the right side of each elevator on that floor):
- x4 for each of the 11 levels (example: 4 copies of the Level 1 detail map)

Purple glitch: 
- behind each map x93

If possible, these should be printed on thick cardboard (alternative to foam core but will still stand out).

Print files are here (.ai + pdf with cropmarks):
https://drive.google.com/open?id=0B2irLVDJivhLYy1qbjhjYm9jWGc

**Comment by kristinashu** [comment]
Updated the maps (https://redpen.io/p/nca82e6ea157535639) and placed in the template from the printer.

Dimension: A3 on 4mm cardboard

Updated quantities to:

Overview map:
- in each elevator x5
- left side of each set of elevators x22

Each level's detail map (to appear on the right side of each elevator on that floor):
- x2 for each of the 11 levels (example: 2 copies of the Level 1 detail map)

Purple glitch: 
- behind each map x49

Print pdf is attached and also in [Drive](https://drive.google.com/open?id=0B2irLVDJivhLUU9JbDVUUjZoRXM)
[Maps-Print (outlined).pdf](https://github.com/MozillaFoundation/Mozfest2016_production/files/540240/Maps-Print.outlined.pdf)

**Comment by marcwalsh-zz** [comment]
Sent to print! 🗺

**Comment by kristinashu** [comment]
I think we ended up halving these numbers (an overview in every elevator and then an overview and a detail on each floor next to each _set_ of elevators). The cardboard it was printed on worked out well but it was extra effort taping the two boards together. I'm still not sure the maps stood out enough against all the diy signs. 

![_41_4672](https://cloud.githubusercontent.com/assets/1068783/20195624/25f1625a-a74c-11e6-90d1-42a1162b523b.jpg)

Note, this is what inside an elevator looks like!
![30521257132_ce48362c98_o](https://cloud.githubusercontent.com/assets/1068783/20195697/6ecd20d6-a74c-11e6-85ee-bab732a1b69e.jpg)
