### ISSUE TITLE
Design Wayfinding: session signage - Deadline Oct 11

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Mozfest2016_production#92]
#### Info:

Based on epic ticket - Design Wayfinding #131 

Hackable signs to appear on session tables. Session leader will fill in with session name and place on table.
#### Deadline:
- Oct 11
#### Last year's:
- Working files in Drive https://drive.google.com/open?id=0B20-0lpP23c0N3lCSkh2eU55VU0
- GitHub ticket https://github.com/mozilla/mozillafestival.org/issues/282
- specs: fit 2 to an A3 paper size along with a bleed on ~200gsm paper

<img width="531" alt="screen shot 2016-08-23 at 1 41 24 pm" src="https://cloud.githubusercontent.com/assets/1068783/17908965/5c79db98-6937-11e6-882a-944721ffc47d.png">

<img width="514" alt="screen shot 2016-08-23 at 12 59 59 pm" src="https://cloud.githubusercontent.com/assets/1068783/17907955/0f09d9a2-6933-11e6-843d-0cb78c6d2661.png">

**Comment by kristinashu** [comment]
These should be more square than last year so they don't droop (these were too long). Thicker paper won't fit into the mental stands.

**Comment by kristinashu** [comment]
@marcwalsh here's a possible card dimension compared to last years. Do you think these will work? They should fit 3 to an A3 (with bleed).

![cards](https://cloud.githubusercontent.com/assets/1068783/19372464/23acbf3a-9171-11e6-941a-d87f73ea59d4.jpg)

@sabrinang @xmatthewx any design feedback?

**Comment by xmatthewx** [comment]
Looks great. 

@marcwalsh – want to test writing a lengthy session title at that size?

**Comment by kristinashu** [comment]
They're still quite large so the names should fit fine.

@marcwalsh here is the print ready file (.ai file + pdf with 3mm bleed and crop marks): 
https://drive.google.com/open?id=0B2irLVDJivhLb3Q1bW9YMXVtcDQ
These should be double sided.

**Comment by marcwalsh-zz** [comment]
These have been printed off-site and will be delivered today/tomorrow.

**Comment by sabrinang** [comment]
## Post MozFest Documentation

Session sign cards were distributed with metal stands and session hosts wrote the session name and brief descriptions (or room number, duration, hashtags etc.) which were found on tables nearby.
![mozfest-documentation-session-cards](https://cloud.githubusercontent.com/assets/2492510/20152305/9b3aab0a-a672-11e6-9fb3-19d6c2297954.png)
