### ISSUE TITLE
Design sponsorship banners - Deadline Sept 23

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Mozfest2016_production#93]
#### Info:

Need info
#### Specs:
- resolution
- dimensions
#### Deadline:
- Sept 23
#### Blockers:
- Need to know who sponsors are
#### Last year's:
- Working files in Drive
- GitHub ticket https://github.com/mozilla/mozillafestival.org/issues/223

**Comment by kristinashu** [comment]
@edrushka @marcwalsh do we have more info on this? When will we know who the sponsors are,  roughly how many sponsors, where will the banners be, what size should the banners be...?

**Comment by xmatthewx** [comment]
When do we expect to have names and logos for this? @edrushka 

Please start to request logos now as this often takes longer than expected. 

Let's update the deadline accordingly?

**Comment by edrushka** [comment]
@xmatthewx we don't actually _have_ any sponsors yet ;) @marcwalsh is on this, and will let us know if any are secured.

**Comment by kristinashu** [comment]
Closing this ticket, if we end up needed this we can open a new one.
