### ISSUE TITLE
Design science fair and closing demo info cards - Print at Ravensbourne

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Mozfest2016_production#94]
#### Info:

Card to go on tables at the science fair and closing demos. People will write in the name themselves. 
Based on epic ticket - Design Wayfinding #131 
#### Specs:

A4 card folded into 4 lengthways to make a triangle.
Printed on-site at Ravensbourne using the standard copiers.
#### Last year's:
- Working files in Drive https://drive.google.com/open?id=0B20-0lpP23c0MWZWV2w4ZHpkMkE
- GitHub ticket https://github.com/mozilla/mozillafestival.org/issues/234

Looks like people used them for other things as well.
<img width="1033" alt="screen shot 2016-08-23 at 1 01 23 pm" src="https://cloud.githubusercontent.com/assets/1068783/17907937/f547ee82-6932-11e6-9e91-9a091fc120f2.png">

**Comment by marcwalsh-zz** [comment]
These will be printed on-site at Ravensbourne using the standard copiers.

**Comment by sabrinang** [comment]
Revised "made at mozfest" cards with updated palette and subtle pixel sort pattern on top: https://redpen.io/p/mq6690195fde6aad51

@kristinashu Should I make another generic card that doesn't have "made at mozfest"? and let me know if you have design feedback on redpen :)

**Comment by kristinashu** [comment]
@sabrinang I think we should keep the white background since it will be printed at Ravensbourne so we won't want any bleed. We also don't know where people will fold them (in 2 vs 4) so having a white box might be limiting. 

I simplified the design a little so the same design could work if people fold it in two or in four. Also updated the glitch a little so if people don't fold it exactly in the middle, the glitch will still look good.

https://redpen.io/p/mq6690195fde6aad51

@marcwalsh @edrushka is this enough? Made at MozFest version is for closing demos and just the MozFest logo is for the science fair and other misc things. 

Looking at last year, we had a bunch of different templates for facilitators https://redpen.io/p/qy81d1e4d8db976f67 Did these actually get used, is it ok not the have all those options this year?

**Comment by edrushka** [comment]
👍 to limiting to two options. R+ from Sarah and I on https://redpen.io/p/mq6690195fde6aad51

**Comment by kristinashu** [comment]
Great! Here are the print ready PDFs: https://drive.google.com/open?id=0B2irLVDJivhLd2k1ZWhRN3FVNnc

**Comment by sabrinang** [comment]
## Post MozFest Documentation

The science fair and closing demo prints were handed out and participants folded them in half to make standing cards. They wrote their project name or description and placed it on the tables.

![mozfest-documentation-science-fair-closing-cards](https://cloud.githubusercontent.com/assets/2492510/20123004/f35b6da8-a5d0-11e6-9ba2-74616a25c8a2.png)
