### ISSUE TITLE
Design popup session posters

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Mozfest2016_production#95]
#### Info:

Template for facilitators to write their session info on. Closely related to https://github.com/MozillaFoundation/Mozfest2016_production/issues/92 - not sure we need both?
#### Specs:
- resolution
- dimensions: A3
#### Deadline:
- Sept 23
## 
#### Last year's:
- Working files in Drive https://drive.google.com/open?id=0B20-0lpP23c0VHVuS0RXMW1LQ3M
- GitHub ticket https://github.com/mozilla/mozillafestival.org/issues/235

**Comment by edrushka** [comment]
@Saallen or @marcwalsh can you explain the difference between these, and the normal session signage in #92?

**Comment by marcwalsh-zz** [comment]
@edrushka - these were just headed paper that can be used for sessions to write the details of sessions that are not on the schedule. 

The last page in last year's document has headings. Is it worth having these, or can we just get plain and coloured paper for people to get creative and draw their own?

**Comment by kristinashu** [comment]
Did they get much use last year? It would be great if we could streamline things and skip this piece.

**Comment by Saallen** [comment]
We can skip this

**Comment by edrushka** [comment]
Cool - one less thing! I'll remove from the asset spreadsheet.
