### ISSUE TITLE
Design MozFest poster - Deadline Oct 11

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Mozfest2016_production#96]
#### Info:

Posters for around the building and available for people to take home with them. Last year's hackable poster was a great success!

We will localize the poster with https://github.com/MozillaFoundation/Mozfest2016_production/issues/124
#### Specs:
- resolution
- dimensions
#### Deadline:
- Oct 11
#### Last year's:
- Working files in Drive
- GitHub ticket https://github.com/mozilla/mozillafestival.org/issues/224

<img width="1044" alt="screen shot 2016-08-23 at 12 55 17 pm" src="https://cloud.githubusercontent.com/assets/1068783/17907774/4180e02a-6932-11e6-882c-086fab46866a.png">
<img width="516" alt="screen shot 2016-08-23 at 12 57 05 pm" src="https://cloud.githubusercontent.com/assets/1068783/17907788/461e9ab4-6932-11e6-9b1d-ffebd2c445a7.png">

**Comment by marcwalsh-zz** [comment]
Last yeah these were part of the festival guide. Would we look to print at Ravensbourne (there would be a white edge around the prints) or get these done professionally. 

(I'll get a quote either way for offsite printing.)

**Comment by kristinashu** [comment]
Offsite would be great so we can get a better quality print. Also, one less thing to do at the venue.

**Comment by Carrie-ann** [comment]
@kristinashu Am I right in saying (based from our conversation on Monday) that we are now not doing posters? but a possible graphic on the back of the map insert? 

I'm just having a look through all print material now, so was just checking. :)

**Comment by kristinashu** [comment]
@Carrie-ann We are doing a poster to put up on walls around the building.

At our check in on Monday, I think we mentioned having a pattern on the back of the map. We could however make the back of the map insert a poster if we wanted to. But that is up to you.

**Comment by sabrinang** [comment]
redpen for hackable posters: https://redpen.io/p/od0688c140744084ab

**Comment by xmatthewx** [comment]
To simplify a bit, I propose that we: 
- Localize the One Web poster
  - not hackable
  - one design of color/pattern for all language versions
- Have a single English hackable poster
  - different color scheme than the one above
  - not localized – complex to ensure we get this grammatically correct at this late stage

What do you think @edrushka? 

After we get this and everything else done, we could revisit design variety and localization, but I think we should proceed with simplest path toward done.

**Comment by edrushka** [comment]
Works for me! People can still hack the English version with other languages.

**Comment by kristinashu** [comment]
Sounds good! The poster are beautiful but we will simplify them to two designs:
- English Hackable version - 1 design
- Localised Non-Hackable version - 1 design but with different text (7 languages since we'll include English)

Redpen designs of 1, 2, 5 and 6 are my favs!

**Comment by sabrinang** [comment]
Redpen for MozFest posters: https://redpen.io/p/jh88919e683f7c860f
- 1 One Web english poster (multicolor pixel sort)
- 1 Hackable english poster (yellow, pink or blue? leaning towards yellow option since we don't have much yellow)
- 6 One Web language posters (teal w/ various textures)

I think we should keep the pen icon on the hackable posters since there will be other non-hackable posters around to make it more inviting/obvious.

@kristinashu @xmatthewx design feedback?

**Comment by xmatthewx** [comment]
Dropped feedback in Redpen. Summarized here:
- Main poster: It is awesome. 😍 Please let's print extras. 
- Hackable: I vote pink. I'd be happy with yellow too. I think blue won't pop enough.
- Localized: @kristinashu suggested a single pattern. I agree, though not opposed to the variety since it's already made. I'd remove Spanish option – it feels very different than the others.

**Comment by kristinashu** [comment]
@sabrinang and I chatted and have updated the posters: https://redpen.io/p/jh88919e683f7c860f

@marcwalsh they are all currently sized at A2, which I think will be a good size for both on the walls and for people to take home. 

What are thinking for quantities? We have these different version:
- 1 in English (want extras for people to take home)
- 1 Hackable in English
- one version in 6 different language

**Comment by kristinashu** [comment]
Here is a print PDF for all the posters - with 5mm bleed and trim marks: https://drive.google.com/open?id=0B2irLVDJivhLcHpwVWlmR3BhQWs
(it's a big file!)

@sabrinang could you please give it a once over? If everything looks good then we're good to print!

**Comment by sabrinang** [comment]
@kristinashu 
I think there are some localisation issues I am catching.
- Hindi: I think I had it backwards एक वेब (I think it says web one right now...)
- Arabic: I couldn’t copy and paste arabic numbers into illustrator (it should be 
  ٢٨-٣٠ أكتوبر ). I am still trying right now but it keeps on changing it into numbers so I have a feeling this is incorrect.
- Dates/Location in German/Spanish weren't given in the [localize ticket](https://github.com/MozillaFoundation/Mozfest2016_production/issues/124) and I got from google translate.

Overall, design wise it is looking good! For the localized posters, I'm think the language should be reviewed in context of the design now.

**Comment by edrushka** [comment]
Can you email heather (pm-ing you her address) when you are done so she can have her crew review the localized posters?

**Comment by kristinashu** [comment]
Amazing, thanks @edrushka and @sabrinang! 

We will print the localised posters at Ravensbourne since there won't be too many and this will give us more time to fix the languages.

@marcwalsh here is a PDF of the English poster: https://drive.google.com/open?id=0B2irLVDJivhLZjNELUpLcFZzeHc

I'm not sure how many to print? For the building, maybe 40 (10 floors with 4 per floor). For people to take home, maybe another 40 (plus people can take posters off the wall).

Does A2 seem like a good size?

**Comment by xmatthewx** [comment]
A2 would be good for localized and hackable poster. Consider A1 for main poster? Or some copies at that size?

**Comment by kristinashu** [comment]
Sounds good, so for the English posters: 40 at A1 and 40 at A2?

**Comment by sabrinang** [comment]
For the localised posters, Heather has been emailed so her team can help review the posters (I sent a separate [redpen](https://redpen.io/p/dx247add31f0157531) dedicated to collect language feedback or her team will reply via email).

**Comment by sabrinang** [comment]
The Arabic, Hindi, Italian, Spanish and French posters have been approved via email by the localisation team so far and I have exported the .pdfs here: https://drive.google.com/drive/u/1/folders/0B4Q8pzCpDS_eblZYMEpCcWQ1dDA

Just waiting for the approval of the German poster now.

**Comment by edrushka** [comment]
Try pinging @thornet for a quick review.

**Comment by marcwalsh-zz** [comment]
Printed and in the Production Office 107

**Comment by sabrinang** [comment]
## Post MozFest Documentation

The main festival poster, hackable poster and localized posters were printed and trimmed at Ravensbourne. The hackable posters needed to be lined with thick tape for pen ink not to bleed through to the walls. Various coloured sharpies were clipped to the hackable posters so attendees could write on them. They were posted throughout the space and localized posters were found in collections. The main and hackable posters were often found in pairs as well.

At the end of mozfest, we collected the posters and encouraged attendees to take some with them as souvenirs!  

![mozfest-documentation-festival-posters](https://cloud.githubusercontent.com/assets/2492510/20196080/edec8cde-a74d-11e6-8a24-ddbaf699910c.png)
