### ISSUE TITLE
Design photo consent poster - Print at Ravensbourne

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Mozfest2016_production#97]
#### Info:

Outline our photo consent policy. Need two different sizes - smaller version at registration desk and larger ones through the building. This will be printed on-site at Ravensbourne for both the A4/A3(?) and large formats.

Updated copy:
- If you do not wish to be photographed or videoed, please request a yellow lanyard from registration. These special lanyards signify that you do not wish to be captured by the onsite photography and video team.
- Mozfest’s official photographer and video team will stream all mainstage programming live on Air Mozilla.
- Our stage moments are live streamed on the 4th floor and in the Walker space. We advise to sit at the back of both areas to avoid being captured on camera or you can watch the live streams from other places around the venue- please ask the welcome desk for further details.
#### Last year's:
- Working files in Drive https://drive.google.com/open?id=0B4Q8pzCpDS_eeEVHZmZ4ZjJtYWc
- GitHub ticket https://github.com/mozilla/mozillafestival.org/issues/302

Smaller version:
<img width="514" alt="screen shot 2016-08-23 at 1 01 31 pm" src="https://cloud.githubusercontent.com/assets/1068783/17907818/685e7c98-6932-11e6-8423-d82ba290089a.png">

Poster size:
<img width="740" alt="screen shot 2016-08-23 at 1 46 27 pm" src="https://cloud.githubusercontent.com/assets/1068783/17909446/632aaf7e-6939-11e6-81e5-5bfa8397d01f.png">

<img width="419" alt="screen shot 2016-08-24 at 10 50 35 am" src="https://cloud.githubusercontent.com/assets/1068783/17941824/cffe1586-69e9-11e6-9355-7fbd79f73cf3.png">

**Comment by marcwalsh-zz** [comment]
This will be printed on-site at Ravensbourne for both the A4/A3 and large formats. 

We will need additional info for the D&D room as some of the content there will be used by MoCo.

cc @Saallen @edrushka

**Comment by Saallen** [comment]
We will need a different sign for D&D if 
- the content is used by MoCo for commercial use. Our policy is re-use for non commercial purposes so in this room we need to highlight that
- It is audio recording
- Live content so those who wish not to be seen need to know where to seat away from cameras

**Comment by kristinashu** [comment]
I've opened a new ticket for copy https://github.com/MozillaFoundation/Mozfest2016_production/issues/107

**Comment by Saallen** [comment]
Just updating here as seen an outdated copy in circulation- this years youth photo consent form has changed slightly here. New version and only version to be used 👍 
[Uploading MozFest2016 Parental consentform.pdf…]()

**Comment by kristinashu** [comment]
@edrushka I'm still not sure what content should go on these posters? Can we use the same copy as last year or do we need two different versions, one general version like last year and a different version for the Walker Space?

**Comment by Saallen** [comment]
I dont think we need separate posters here but would advise that we change the third point.
- Our stage moments are live streamed on the 4th floor and in the Walker space. 
  We advise to sit at the back of both areas to avoid being captured on camera or you can watch the live streams from other places around the venue- please ask the welcome desk for further details.

**Comment by sabrinang** [comment]
Photo & video consent poster on redpen here: https://redpen.io/p/jme7f6ca34eb277676

@Saallen Thanks for the copy! I have updated the third point and used the copy from last year for the other two. I revised the icons and have two layout iterations with various colours/patterns. @xmatthewx @kristinashu can you give me some design feedback on the redpen?

**Comment by edrushka** [comment]
Sarah and I reviewed this carefully together. Looks great! I added my +1 to one of the diagonal designs 👯 

We also adjusted the copy slightly - comments are in the last version, but will apply to any design.

**Comment by xmatthewx** [comment]
As I mentioned in Redpen, I suggest that we add something pointing to the yellow lanyard (a tl;dr for busy attendees) such as _Yellow = No Photos –>_

**Comment by sabrinang** [comment]
redpen: https://redpen.io/jd4920446db3d8ef62
- updated copy for 2nd and 3rd points
- changed last icon to question mark
- fixed spacing in title, text/wordmark/icon is now blue
- revised illustration to show yellow lanyard means no photo compared to regular

**Comment by kristinashu** [comment]
Lookin' good!

**Comment by sabrinang** [comment]
exported as .pdf (with 0.125" or 3.175mm bleed/trim marks) for print here: https://drive.google.com/drive/u/1/folders/0B4Q8pzCpDS_edk5HSmx6TmFHR0k

**Comment by sabrinang** [comment]
https://redpen.io/jd4920446db3d8ef62
@edrushka copy review? @xmatthewx design review?

**Comment by edrushka** [comment]
Capitalize Registration in the first bullet (I noted in the redpen). Otherwise, looks good 👍

**Comment by xmatthewx** [comment]
Hi team. If I didn't already know that the lanyard color had meaning, and I didn't read the whole poster (which I would never do), I wouldn't learn to avoid private people in my photos. I am probably not the only person like this. 

Please forgive this hasty mockup that will never win a design award. But, I think we should be more explicit and direct.

<img width="507" alt="screenshot 2016-10-19 12 44 09" src="https://cloud.githubusercontent.com/assets/53411/19528408/e4e30e5c-95f9-11e6-9c6d-8c5e445b3e15.png">

**Comment by kristinashu** [comment]
I realize now the copy in the poster is more about telling people who don't want to have their photo taken what to do. It should be more about informing everyone not to take photos of people wearing a yellow lanyard.

Can we update the title or add a sub title? Something about - Do not take photos of people wearing a yellow lanyard.

We should still include the 3 points but it should be secondary to the main info.

@xmatthewx @edrushka any copy suggestions?

**Comment by edrushka** [comment]
Here is what we have drafted for the email:

Photo Consent Notice

There will be official Mozilla photographers and videographers on-site working to capture all of the weekend’s amazing activity under the Creative Commons Attribution license 4.0. 

If you do not wish to be photographed or filmed, please request a yellow lanyard from the registration desk when you arrive at the festival, which signifies you do not want your image to be used. Please also be mindful of others when taking photos, especially of youth and those wearing the yellow lanyard.

**Comment by xmatthewx** [comment]
How about this heading...

Privacy Alert [big font]
Please don't photograph people with yellow lanyards [medium font]

We could bump the Mozfest logo to the bottom and make it smaller. 

Or... we could just do a note "Yellow = don't photograph -->" pointing to the illustration.

**Comment by sabrinang** [comment]
@xmatthewx @edrushka @kristinashu Check out the revised redpen: https://redpen.io/jbf8da498af93169d3

I used Matthew's suggestion and changed headings:
- Privacy Alert
- Please don't photograph people with yellow lanyards 
- and I adjusted yellow lanyard/name card larger to give it more prominence and to fit with the headings

**Comment by sabrinang** [comment]
I updated the changes: https://redpen.io/jbf8da498af93169d3
- made the body copy smaller and this made room for more white space above to make the wordmark less busy/squished (I kept the size of the wordmark though it balanced out with the sizes of the icons below)
- capitalized Registration

**Comment by sabrinang** [comment]
@edrushka Do the new headings look okay to you? https://redpen.io/jbf8da498af93169d3

**Comment by edrushka** [comment]
R+ from Sarah and I

**Comment by sabrinang** [comment]
The print files (.pdf & .eps)(with 0.125" or 3.175mm bleed/trim marks) are located in the For Print folder here: https://drive.google.com/drive/u/1/folders/0B4Q8pzCpDS_edk5HSmx6TmFHR0k

**Comment by marcwalsh-zz** [comment]
Printed!

**Comment by sabrinang** [comment]
## Post MozFest Documentation

The privacy alert posters were placed behind the registration table, in the Dialogues and Debates area in the Walker Space on level 0 and on level 4 in the Big Space.
![mozfest-documentation-privacy-alert](https://cloud.githubusercontent.com/assets/2492510/20195148/2bf62570-a74a-11e6-883a-86058c76cd4b.png)
