### ISSUE TITLE
Design main festival banners and flags

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Mozfest2016_production#99]
#### Info:

Last year we reused them and we could probably do the same this year. 

<img width="516" alt="screen shot 2016-08-23 at 12 56 51 pm" src="https://cloud.githubusercontent.com/assets/1068783/17908332/e78ee0f0-6934-11e6-9c8b-b2fb79cfb941.png">

**Comment by edrushka** [comment]
Last year we used these on each floor by the info booths and at registration.

**Comment by kristinashu** [comment]
We will re-use last year's.
